bin/p2-watch/main.go
pkg/intent/intent.go
pkg/intent/intent_test.go
pkg/preparer/orchestrate.go

This PR changes the path for keys in the intent store to `/intent/<node>/<manifestid>` as we discussed on Friday.

Intent key/value path

---

pkg/intent/intent.go

moral of the story: path.Join is correct, string concatenation is incorrect https://github.com/armon/consul-api/blob/master/kv.go#L171
I looked at all the references to INTENT_TREE and they all look safe to me with the leading slash removed, but I've already screwed up twice on this change, so some extra eyes would be welcome.

Remove leading slash on intent path

---

pkg/reality/reality.go

Because consul API is using concat instead of path.Join

Remove leading slash on reality path

---

pkg/logging/logging_test.go

Sometimes this test fails because the scheduler doesn't execute the
net.Listen right away. Then the logger fires the hook expecting the
socket to be there, and it isn't yet (because nobody is listening).
To eliminate these sporadic errors, we can just move the Listen call
out of the goroutine, so that the test is blocked until the socket is
ready.

Block on net.Listen in logger socket test

---

bin/p2-launch/main.go

Encountered this issue while bootstrapping a new universe cluster, because I use `p2-launch` to start consul as opposed to `p2-bootstrap`. Pretty straightforward fix

Allow p2-launch to specify user

---

pkg/pods/hoist_launchable.go

This removes the warning that happens when `runit.Restart` fails due to the usage of a TERM handler, which is very common and recommended practice.

Remove restart checking

---

bin/p2-bin2pod/main.go
bin/p2-bootstrap/bootstrap.go
bin/p2-inspect/main.go
bin/p2-launch/main.go
bin/p2-schedule/main.go
bin/p2-watch/main.go
pkg/version/version.go

Now that we tagged 0.0.1, we should probably bump to 0.0.2.

version bump

---

pkg/pods/fake_chpst
pkg/pods/hoist_launchable.go
pkg/pods/pod.go
pkg/pods/pod_test.go

The fake_chpst fix was because, for some reason, there were unreadable files in my $TMPDIR. The test was setting ConfigDir to $TMPDIR and fake_chpst was trying to read them, then throwing exceptions.

POD_HOME exports in p2

---

Rakefile
bin/p2-preparer/main.go
integration/single-node-slug-deploy/check.go
integration/suite.rb
pkg/hooks/hooks.go
pkg/kp/kv.go
pkg/preparer/orchestrate.go

This commit replaces the use of user.CreateUser with a
simple create_user shell script that is launched as a before_install
hook pod. This has the effect of verifying that the hook is
found in the intent store, installed correctly, and launched at
the correct time during the install / launch.
This commit includes a number of small fixes and changes to facilitate
that goal.

Test hooks in the integration test

---

Rakefile
pkg/version/version.go

Variables can be set at link time with the -X flag, where as constants are fixed at compile time and therefore cannot be reconfigured later. I plan to put this in my universe script because I usually check out a new branch every time I build a new universe.
Use case:
```bash
$ touch pkg/version/version.go
$ godep go install -ldflags "-X github.com/square/p2/pkg/version.VERSION $(git describe --tags)" ./bin/...
$ p2-inspect --version
0.0.01-47-g123abcd
```

VERSION should be a variable, not a constant

---

pkg/pods/hoist_launchable.go

This ensures that a new temporary directory serves as the download
destination for Hoist artifacts, even when installing artifacts
of the same name and verison. In practice this won't affect day-to-day
operations of the preparer, but does have a meaningful impact on
test cases.

Prevent races when downloading the same artifact

---

bin/p2-preparer/main.go
pkg/pods/hoist_launchable.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/pods/test_helper.go
pkg/util/mkdir.go
pkg/util/mkdir_test.go

This addresses three of the four main tasks I mentioned on the trello card:
- create /data/pods explicitly
- add mkdirchownall
- use mkdirchownall in all pod-related contexts.
The missing first task (parameterizing /data/pods) will probably need a bit more work. Implicit use of pods.DEFAULT_PATH is threaded through our code and refactoring that might get messy, but for now this functionality is all we really care about, and it simplifies deploys of some existing applications.

Chown pod dirs correctly

---

bin/p2-bootstrap/bootstrap.go

This feature is useful when bootstrapping in universe, where sometimes one node takes forever to `go get github.com/tools/godep` and it ends up 15-20 seconds behind all the others. We can use this flag to extend the timeout and smooth over those delays.

Bootstrap timeout

---

bin/p2-inspect/main.go

Instead of this output:
```json
{
"p2-preparer": {
"aws1.neat-policy.universe.square": {
"intent_manifest_sha": "57b0e6caeeb06b665527b0c907c2c2b2f002299e",
"reality_manifest_sha": "57b0e6caeeb06b665527b0c907c2c2b2f002299e"
}
}
}
```
Now you get this output:
```json
{
"p2-preparer": {
"aws1.neat-policy.universe.square": {
"intent_locations": [
"/home/sjung/p2-preparer_rxnowrkttihmszuizjywqlwywtkrujgqyuqysyzp.tar.gz"
],
"intent_manifest_sha": "57b0e6caeeb06b665527b0c907c2c2b2f002299e",
"reality_locations": [
"/home/sjung/p2-preparer_rxnowrkttihmszuizjywqlwywtkrujgqyuqysyzp.tar.gz"
],
"reality_manifest_sha": "57b0e6caeeb06b665527b0c907c2c2b2f002299e"
}
}
}
```

List locations in p2-inspect

---

pkg/preparer/orchestrate.go

This is definitely the least useful and noisiest of our log messages

Lower log level for "new manifest received"

---

pkg/pods/hoist_launchable.go

We weren't reacting to the symlink type before, so we just created an empty file and left it that way.
In the future, any types we don't recognize should result in errors rather than silent coercion. This clearly indicates we can't handle the tarball and we can then implement a proper response for that type.

Handle symlinks in a hoist artifact tarball

---

pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go
pkg/preparer/setup.go

Original:
OK, this has the replicator check the intent store for allowed_deployers before writing to the intent store.
This works, but we also need to do this for p2-schedule, don't we?
I've a mind to write tests for this, if I hear that this is the direction we want to take.
Now it's the simplified version for preparer only.

Allowed deployers

---

pkg/kp/service.go
pkg/pods/pod_manifest.go
pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go
pkg/preparer/setup.go

This commit adds support for https health checks. Pods have to opt into https in their manifests. The CA for the HTTPS endpoint is in consul's `$SECRETS_PATH`.
pretty icky code to be putting in an open source project but we can improve the usability later

HTTPS health checking

---

pkg/hooks/hooks.go
pkg/preparer/orchestrate.go

as requested. I'm gonna go test it but take a look at the code.
One thought I just had: it would be nice if we could pass more information to hooks of this type, specifically to communicate how the auth failure occurred. We don't really have a mechanism for this right now (the hook basically has to parse the manifest itself and check the signature by somehow reading the preparer's public keyring) but it would be cool.

Add AFTER_AUTH_FAIL hook type

---

README.md
bin/p2-bin2pod/main.go
pkg/hoist/fake_contain
pkg/hoist/hoist_executable.go
pkg/hoist/hoist_executable_test.go
pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/hoist/test_helper.go
pkg/pods/pod.go
pkg/pods/pod_manifest.go
pkg/pods/pod_test.go
pkg/runit/servicebuilder.go

Introduces a dependency on our [contain](https://github.com/square/prodeng/tree/master/cgroup-container) script. I was planning to use libcontainer for this, but there are too many moving parts in their top-level API, and their internal packages are clearly not intended for third-party consumption.
I kind of dislike the code surrounding "insert this binary into the runit script for this hoist executable". This has me thinking about a better API for that area, but it can wait for now.

Cgroup limiting

---

integration/single-node-slug-deploy/check.go

since we now default hooks to run as the pod ID, we need to allow this user creation hook to run as root

allow hook in integration test to run as root

---

bin/p2-replicate/main.go
pkg/health/health.go
pkg/health/health_state.go
pkg/replication/replication.go
pkg/replication/replication_test.go
pkg/replication/rollout_order.go

Verified in universe - I set the wrong status port so all the health checks would be critical, then I set the replicate threshold to critical, and the rollout completed successfully.

Allow degraded health checks in replication rollouts

---

pkg/health/health.go
pkg/kp/kv.go

Prevents ACL leakage. Unfortunately consul does not return typed errors, so there's really no way to get at the contents of the error value and take out the things we don't want. We just have to throw the whole thing away.

Do not return errors directly from consul API

---

bin/p2-inspect/main.go

when scrolling through a huge list of p2-inspect output for a given pod, it's much easier to figure out which location you care about if they're in a consistent order.

Sort inspect locations

---

bin/p2-bootstrap/bootstrap.go

Verifies that the Preparer and Consul both make it into the reality store. If ACLs are misconfigured for the preparer, this step will catch such an issue.

Verify reality store during bootstrap

---

bin/p2-inspect/main.go
bin/p2-replicate/main.go
bin/p2-schedule/main.go
pkg/health/health.go
pkg/kp/config.go
pkg/kp/kv.go

I was originally going to add it as a scheme (eg `127.0.0.1:8500` vs `https://127.0.0.1:8500`) but it turns out that doesn't really work. Consul supports unix sockets in the address field (ie instead of `127.0.0.1` you can say `unix:///var/run/consul.sock`), and the unix socket scheme kinda gets in the way of the https part. So you have to pass it as a boolean.
The changes to health.NewConsulHealthChecker will be useful if we refactor the reality-checking out of pkg/health later on.

HTTPS in p2 binaries

---

bin/p2-replicate/main.go

don't replicate to hosts that don't have a preparer. (btw not yet tested, gonna test tomorrow in universe. I think they've been down for most of the day)

Check reality store before replicating

---

bin/p2-bootstrap/bootstrap.go

Consul server nodes register a service for themselves automatically. Consul client nodes do not, but we end up registering one for them anyway as part of the reality-updating process. So we should probably do that in bootstrap too.

Register consul service during bootstrap

---

pkg/kp/kv.go

This error comes from the consul API package, so it cannot be exposed to the caller

Hide error from SetPod when writeMeta != nil

---

pkg/hoist/hoist_launchable.go

If the error was nil, it would be returned after the first executable, and the others would still be down. (Probably wasn't as obvious of an issue before because we only recently started stopping AND starting)

Restart all executables

---

pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go

GPG short IDs are only 4 bytes long and can risk collisions. Using the entire fingerprint (20 bytes) is more predictable.
http://security.stackexchange.com/questions/74009/what-is-an-openpgp-key-id-collision

Use full 20-byte GPG fingerprints

---

pkg/hoist/hoist_launchable.go
pkg/pods/pod.go

Note that you can still get some undesired behavior when scheduling an empty manifest (eg the service check will still be created if the status_port is in the manifest), but that's a separate issue

Allow zero launchables or zero executables

---

pkg/artifact/app_manifest.go
pkg/artifact/artifact.go
pkg/artifact/artifact_test.go
pkg/cgroups/cgroups.go
pkg/digest/verification.go
pkg/hooks/hooks.go
pkg/kp/kv.go
pkg/kp/service.go
pkg/runit/runit_service.go
pkg/runit/servicebuilder.go

This commit contains a variety of small tweaks, cleanups, fixes, and
clarifications. The only motivation behind these changes is the thought, "This
doesn't look quite right," as I read through the source code.

Misc fixes and cleanup

---

pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/hoist/test_helper.go
pkg/pods/pod.go
pkg/uri/uri.go
pkg/uri/uri_test.go

The "uri" module presented a nice interface for copying a file from an
arbitrary URI to a local file. But what if you just want to consume the data
stream and not store it? This commit refactors the `uri.Copier` type into the
`uri.Fetcher` interface, which exposes the URI data stream directly (you can
still make a local copy if you want).
By accessing the data stream, users can avoid allocating a temporary directory,
writing a file to it, operating on the file, then deleting it.

Refactor URI fetcher to support streaming

---

pkg/uri/uri.go

HTTP allows meaningful data in the body of HTTP responses for many status
codes. As far as `uri.BasicFetcher.Open()` is concerned, anything except a 200
status means the data can't be accessed, so it should return an error.

Return an error when BasicFetcher gets an HTTP error

---

pkg/uri/uri.go
pkg/uri/uri_test.go

Fixes a bug in the handling of `file://` URIs; the leading slash on an absolute path was being stripped off (notably our integration test uses these). Question marks in the URL path will have to be query-escaped.

Parse URIs for fetching

---

pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/hoist/test_helper.go
pkg/pods/pod_test.go
pkg/runit/runit_service.go
pkg/runit/runit_service_test.go

This change makes sure that any operations performed with the `sv` utility wait for the existence of the supervise directory, which indicates that `runsv` is currently running.

wait for the supervise directory to appear

---

pkg/cgroups/cgroups.go
pkg/hoist/hoist_launchable.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/runit/fake_servicebuilder
pkg/runit/servicebuilder.go
pkg/runit/servicebuilder_test.go
pkg/util/write.go
pkg/util/write_test.go

Managed to PR this before leaving the office for the last time! Summary:
- no dependency on external servicebuilder script
- the new servicebuilder does not explicitly stop and start services like the old one did. runsvdir does that already when new directories are added or removed.
- I was considering writing the down file to make all services downed-by-default, which would give p2 more control over the moment that the service starts, but I don't think the distinction is particularly significant here, because the next thing we do (right after creating the service directory) is starting the service.
- servicebuilder functionality invoked as part of hoist launchable.Launch, removed from pod.Launch.
- To preserve the behavior of servicebuilder wrt cleaning up old services, pod invokes the …

Move servicebuilder functionality into p2

---

bin/p2-preparer/main.go
pkg/auth/policy.go
pkg/auth/policy_test.go
pkg/preparer/orchestrate_test.go
pkg/preparer/setup.go
pkg/preparer/setup_test.go
pkg/preparer/test_preparer_config.yaml
pkg/util/watcher.go

Adds a new deploy authorization policy to the preparer based on an external
user-based policy file.  This PR consists of a two commits that are pure
refactors and one commit to implement the new policy.

Add user-based authorization policy

---

pkg/preparer/orchestrate_test.go
pkg/preparer/setup.go

Uses an `interface{}` type when parsing the preparer's "auth" section. `string`
is too restrictive because `KeyringAuth` needs to encode a list of strings.

Use generic types when parsing authentication settings

---

pkg/cgroups/cgroups.go
pkg/pods/pod.go
pkg/runit/fake_servicebuilder
pkg/runit/servicebuilder.go
pkg/runit/servicebuilder_test.go
pkg/util/write.go
pkg/util/write_test.go

The first two commits are the same as in the original branch. For the third commit, the original branch moved servicebuilder into the hoistlaunchable, which caused one file to be created for each launchable. This causes conflicts with existing servicebuilder files.
This new branch instead uses the new servicebuilder in the existing pod.buildRunitServices. This preserves the one-file-per-pod behavior that we were using before, which means conflicts will not be created between old p2 servicebuilder files and new ones.
Thorough testing is in progress, but the code is ready for review. My travis branch will be rebased back on top of this after merge.

servicebuilder reimplementation, round 2

---

pkg/auth/policy_test.go

Some slight fixes to 653cf1e to preserve the common usage of `testHarness`.

Reuse error handling logic in policy test

---

bin/p2-preparer/main.go
pkg/preparer/setup.go

This implementation counts consecutive errors from either hooks or pods. Status goes critical if the number of consecutive errors >= 10 (the constant tooManyErrors).
I have been testing on a universe by stopping consul in the universe and seeing the errors count up. I then restart consul to see if it goes healthy again. I'm not 100% clear on whether I have the "OK I'm healthy again" part right. Going to do some more testing and report back on this PR.

Add status port for p2-preparer

---

bin/p2-preparer/main.go
pkg/auth/policy.go
pkg/auth/policy_test.go
pkg/preparer/listener.go
pkg/preparer/orchestrate.go
pkg/preparer/setup.go

Hooks are not the same as apps: they are the method of extending the preparer,
not something that users will use for pushing apps. This commit separates
`auth.Policy.AuthorizePod()` into `AuthorizeApp()` for use on apps and
`AuthorizeHook()` for use on hooks. In most policies, the two are treated the
same. In `UserPolicy`, hooks are authorized using the name of the preparer, not
the name of the hook's pod.

Authorize hook deployment as if they were the preparer

---

bin/p2-schedule/main.go
pkg/kp/kv.go
pkg/kp/lock.go

Also exposes an `UnsafeError` field on the KVError type. Consul's
errors are not safe to print since they frequently include ACL tokens
in the text, so this can be selectively inspected during triage.

Force `p2-schedule` to terminate if a manifest is unschedulable

---

bin/p2-inspect/main.go
pkg/hooks/hooks.go

Allows callers of p2-inspect to read the unsafe error instead of
the sanitized one (assumes that all callers of p2-inspect are human)
Prints name of hook executed instead of an unqualified name.

small logging improvements

---

pkg/auth/policy.go
pkg/auth/policy_test.go
pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go
pkg/preparer/setup.go

Changes the UserPolicy authorization policy to look for authorization based on
the user the pod will run as, not the name of the pod. This makes the tool more
similar to "sudo", in that users are authorized to run commands (deploy
software) as other users.
This commit also renames the configuration parameter "forbidden_pod_ids" to
"forbidden_users".  Even before this commit, it was blocking users in the
"run_as" field, but its name did not convey this.

Authorize a pod based on its manifest's user, not its name

---

bin/p2-sum/main.go

p2-sum is a CLI tool for printing the canonical hash of a P2 pod manifest. It
is similar in usage to standard "md5sum" and "shasum".
See the documentation in _bin/p2-sum/main.go_ for more information.

Adds p2-sum tool to show the canonical P2 manifest hash

---

pkg/util/net/client.go

This method enables the creation of a p2 headerTransport
object. This lets you set the Transport field of an
existing http.Client object

Adds GetTransport method

---

pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go
pkg/preparer/setup.go

The "forbidden_users" option was an extra authorization check performed after
the normal authorization policy allowed an app to be installed. It allowed
certain "run_as" usernames to be blacklisted. Since the "user" policy is
already verifying the "run_as" user, the extra check is redundant.
This commit removes the "forbidden_users" option from the config struct and all
internal uses of it. It can continue to be specified in the preparer's config
without error; it will simply have no effect.

Remove "forbidden_users" preparer option

---

integration/single-node-slug-deploy/check.go
pkg/watch/health.go
pkg/watch/health_test.go

Had to fix logging in the watch package. Was trying
to reference nil pointers because PodWatch's logger
field was nil.
The manifest for hello which is populated in check.go
did not have the StatusPort or StatusHTTP fields set.
Integration test for watch pkg now asserts that all
services being health checked are passing. I don't
know why I didn't do that before...

fix integration test for health check

---

pkg/preparer/setup.go
pkg/preparer/setup_test.go
pkg/preparer/test_preparer_config.yaml

The support is there in `kp.Options`, we just were not exposing the option in preparer config.

preparer: Support HTTPS

---

pkg/preparer/orchestrate.go
pkg/preparer/setup.go

Adds the `cert_file`, `key_file`, and `ca_file` configuration options for the
p2-preparer.  These options are used to configure the TLS transport options for
the client used to communicate with the Consul agent.

Add TLS configuration options for Consul connection

---

pkg/pods/pod_test.go
pkg/runit/servicebuilder.go
pkg/runit/servicebuilder_test.go
pkg/runit/test_helper.go

Updates the servicebuild clone to fix a couple of discrepencies compared with
the canonical version:
* Didn't create the "app/log/main" directory
* Used timeout value in "run" and "log/run" scripts instead of "2"
Also makes the following improvements:
* Make it harder to accidentally remove mandatory trailing whitespace when
using editors that remove trailing whitespaces
* Simplify some of the logic in the unit tests

Fix servicebuilder discrepencies

---

bin/p2-preparer/main.go
pkg/kp/kv.go
pkg/kp/lock.go

We don't want to show Consul errors all the time—they can leak ACL tokens—but
when debugging a problem involving Consul, that kind of information is very
important to understanding what's going on. This commit adds a command line
flag that will enable detailed log messages, to be used only when needed.

Add "--show-consul-errors-unsafe" flag to show Consul errors

---

pkg/replication/replication.go

Currently any error when checking for the reality store entry
for a preparer pod will indicate that no preparer is present. This
commit improves the error message so that communication errors are
more apparent.

Better error message regarding absent preparers

---

pkg/kp/service.go

Commit f3658d76 reordered parameter arguments in a call to Sprintf(). This
commit fixes the bug.

Fix bug in f3658d76

---

pkg/health/health.go
pkg/health/health_test.go
pkg/kp/kv.go
pkg/watch/health.go

In some cases findWorstResult and findBestResult were being
passed empty result slices. This was cause panics. Now when
they are passed an empty slice they return a HealthEmptyError.
HealthEmptyError wraps an error and allows callers to handle
it as they see fit.
Updates health_test to reflect these changes and includes a
test for empty slices passed to the aformentioned methods.

find*Result in health package handles empty slice inputs

---

pkg/util/stream/publisher_test.go

The unit tests for the "stream" package failed with output:
--- FAIL: TestUnsubscribeIndependence-2 (0.00s)
publisher_test.go:251: sub2 got unexpected sequence: []
The unit test created a StringValuePublisher, subscribed to it. A value was
sent to the publisher, and afterwards the subscription was canceled. It was
expected that "[]" would not be received because the send of the value would
block until the subscriber had received at least the initial value.
After taking a second look at the synchronization, that behavior wasn't
accurate. Even if it was, the test was flaky because it depended on the
implementation details of the publisher rather than its high-level behavioral
contract. The only truly buggy behavior is if the subscription receives a value
that was published after the …

Fix buggy unit test

---

pkg/kp/lock.go

Unit tests were failing with the following abbreviated output:
panic: close of closed channel
goroutine X [running]:
github.com/square/p2/pkg/kp.Lock.Destroy()
lock.go:148
github.com/square/p2/pkg/kp.Lock.continuallyRenew()
lock.go:128
created by github.com/square/p2/pkg/kp.consulStore.NewLock
lock.go:75
goroutine Y [runnable]:
....
github.com/square/p2/pkg/kp.(*ConsulTestFixture).Close()
fixtures_test.go:40
github.com/square/p2/pkg/kp.TestLock()
lock_test.go:39
testing.tRunner()
testing.go:447
created by testing.RunTests
testing.go:555
...
FAIL    github.com/square/p2/pkg/kp
There is a race between renewing a lock's session and a caller calling
`Destroy()` manually. Both execution paths try to close `quitCh`. This isn't
necessary to do when renewal fails, so this commit fixes the race by …

Fix bug in Lock manager

---

pkg/health/health.go

The GetHealth method is defined as:
GetHealth(service, node string)
but was being called with (node, service).

Fix replication bug

---

pkg/kp/healthmanager.go

Some services include unique output in their status checks, e.g., a current
timestamp, and this was causing the services' KV health checks to be updated on
every check. With this commit, a new health check will be written only when
"Status" changes in a check result. "Output" is still present, but it cannot be
relied upon to be the most recent value.

Only update KV health for status changes

---

pkg/watch/health.go
pkg/watch/health_test.go

Changes the behavior of the health manager in "pkg/watch" so that health
updaters are restarted whenever a manifest's status polling method (port or TLS
settings) changes.

Refresh health watchers when status info changes

---

pkg/watch/health_test.go

Changes the status handler in the "pkg/watch" unit test to only bind to the
"localhost" address. This change prevents the Mac OS X firewall from prompting
me "Do you want the application 'watch.test' to accept incoming network
connections?" every time I ran unit tests.

Remove OS X firewall message

---

pkg/cgroups/cgroups.go

An extra 10% appears to be too restrictive in practice. It would be nice to
make this configurable, but that can come later.

Increase headroom for cgroup memory limits

---

bin/p2-preparer/main.go

If the preparer is unable to correctly report its health, it isn't functioning
properly. This commit causes the whole preparer to die when its HTTP status
server dies, so that the preparer has a chance of fixing itself when it starts
up again.

Kill the preparer when its status server dies

---

pkg/hoist/hoist_launchable.go
pkg/pods/manifest.go
pkg/pods/pod.go
pkg/preparer/orchestrate.go
pkg/runit/runit_service.go

All restarts are now forcible by default with a 60 second timeout, except for the preparer pod, which will never use forcible restart to ensure that bootstrapping continues to function correctly.
Each launchable section now supports an optional `restart_timeout` flag which can express a `time.Duration` that will be passed (in seconds) to the `sv force-restart` command. If no restart duration is provided, we continue to use `sv restart` and do not use KILL.

Support forceable restarts after timeout

---

integration/single-node-slug-deploy/check.go
pkg/hoist/hoist_launchable.go
pkg/runit/runit_service.go

Since we currently do an `sv stop` followed by an `sv restart`, it makes sense that we should pass the time out to stop.

Also use force timeouts on pod.Halt()

---

pkg/labels/http_applicator.go
pkg/labels/http_applicator_test.go

This allows using an HTTP server that accepts GET requests and returns
JSON lists of strings representing the nodes that match the query.

Add HTTP Applicator and tests

---

bin/p2-schedule/main.go
bin/p2-watch/main.go
pkg/hooks/hooks.go
pkg/hooks/hooks_test.go
pkg/kp/constants.go
pkg/preparer/listener.go

next step would be disabling typed hooks, but we'll have to do that after we migrate all our hooks (including those from other teams) to the new system.

Enable global hooks

---

pkg/hoist/hoist_launchable_test.go

We should also have tests for the key exported methods, Launch and Halt. Unfortunately I think there's a lot of lifecycle code in Pod that doesn't have test coverage. Still thinking about how to attack those.

Add more tests to pkg/hoist

---

bin/p2-exec/main.go

Adds a new --workdir (short: -w) flag to the p2-exec command that allows it to
change the working directory before exec-ing its main command.

Add --workdir flag to p2-exec to change working directory

---

bin/p2-preparer/main.go
pkg/kp/healthmanager.go
pkg/preparer/setup.go
pkg/util/param/param.go

Adds a new "params" package which provides a less-formal way to specify
configuration parameters.  Each parameter can be declared in the package where
it's needed, and a single call to `params.Parse()` will set all defined
parameters.
This is mainly intented to permit some configurability for values that would
otherwise be declared as a package constant, or where there are too many layers
between a program's main configuration parser and the use of that configuration
value.

Add params package

---

pkg/preparer/result_set.go
pkg/preparer/result_set_test.go

Luckily this panic is only encountered when trying to DELETE a manifest (since intent has to be shorter than reality to cause the panic, vice versa does not cause it) so it won't be triggered in production conditions any time soon.
I'm going to try and write some fuzz tests for this before merging, because this is the third time I've had to modify a logically straightforward function...

Fix ZipResultSets conditions

---

bin/p2-install-hook/main.go
pkg/hooks/install.go
pkg/preparer/listener.go

Moved the most logically complex part of hook installation (writing hook scripts) into the hooks package, and created a corresponding binary that uses it. Will be useful for distributing hooks without hitting everything.

Refactor hook install

---

pkg/kp/rcstore/consul_store.go
pkg/labels/applicator.go

Let's talk a bit about how this should work. What labels should the RC put on itself?
Currently just pod_id. Should we apply the same labels as in the `podLabels` set? I think we earlier decided that the answer to that question should be "no". Should it be a separate parameter?
Perhaps we should also remove all labels when the RC is deleted?
Should that be coupled with the RC store?
By this I mean: should there be a `func (*rc replicationController) Delete()` that does `rc.rcStore.Delete(rc.RC)` and also `rc.DeleteLabels()`? My own suspicion is that there should be, to prevent someone from forgetting
If the answer to the previous question is yes, does that seem inconsistent given that `New()` doesn't perform `rcStore.Create`? It's this way because `New()` could be passed the results of …

Replication Controllers label themselves

---

.travis.yml
Rakefile
bin/p2-replicate/main.go
pkg/kp/fixtures_test.go
pkg/replication/common_test_setup.go
pkg/replication/replication.go
pkg/replication/replication_test.go
pkg/replication/replicator.go
pkg/replication/replicator_test.go

1) kp.NewLock() now will auto renew the lock in consul until explicitly
stopped
2) The functionality of Replicator was split into two structs,
Replicator and Replication. Replicator has an InitializeReplication()
function that returns a single-use instance of Replication, which has
the necessary data to perform a replication of a pod to a set of nodes.

Rework pkg/replication to be easier for clients to work with.

---

pkg/kp/constants.go
pkg/kp/rcstore/consul_store.go
pkg/kp/rcstore/fake_store.go
pkg/kp/rcstore/store.go
pkg/rc/replication_controller.go
pkg/replication/replication.go
pkg/replication/replication_test.go
pkg/replication/replicator_test.go

None of this code has been tested yet, requesting review for concepts and structure.
There are a few goals being covered here:
- RCs should use their ID label to find their "current" nodes, rather than their set of pod labels. Otherwise it becomes impossible for two RCs to have the same set of pod labels.
- rcstore should be capable of taking locks on replication controllers. To avoid collisions, we move intent-tree locks to `/lock/intent/<node>/<pod>` and put the new locks under `/lock/replication_controller`. I would have also liked to do some refactors to lock and session management to make the API better (essentially I would have created a new package `store/lockstore` for it), but I don't have a good idea of how long that would take right now and I'm still getting familiar with the …

Orchestration-related refactors part 1

---

pkg/kp/constants.go
pkg/kp/rcstore/consul_store.go
pkg/kp/rcstore/fake_store.go
pkg/labels/consul_applicator.go
pkg/rc/fields/fields.go
pkg/rc/fields/fields_test.go
pkg/rc/replication_controller.go
pkg/rc/replication_controller_test.go

Replication controllers are stored in a single key now with CAS mutation. The similarity to the pkg/labels API is remarkable.
Might have other stuff incoming on this PR. Have not tested yet, but am about to do so.

Orchestrator-related refactors round 2

---

pkg/gzip/gzip.go
pkg/hoist/hoist_launchable.go

Changes the ExtractTarGz() function to create each file with its original
owner, as recorded in the TAR file, when no owner is specified. This will
be used when extracting container filesystems.

Let tgz extractor preserve tar ownership info

---

pkg/hoist/hoist_launchable.go
pkg/hoist/test_helper.go
pkg/p2exec/p2_exec.go
pkg/p2exec/p2_exec_test.go
pkg/pods/pod.go
pkg/pods/pod_test.go

This allows code utilizing the hoist.Launchable struct as a library to
determine whether p2-exec commands run with the -n (no-limit) flag. This
is useful because the -n flag requires root privileges.

Make the -n flag to p2-exec configurable via hoist.Launchable struct

---

bin/p2-rctl/main.go
pkg/kp/constants.go
pkg/kp/kv.go
pkg/kp/lock.go
pkg/kp/rcstore/consul_store.go
pkg/kp/rcstore/fake_store.go
pkg/kp/rcstore/store.go
pkg/kp/rollstore/store.go
pkg/rc/farm.go
pkg/roll/farm.go
pkg/roll/run_update.go

Fixes various lock-related things in rolling updates and RCs. Implements farm for rolling updates and associated p2-rctl commands. Verified in staging.

Rolling update farms

---

bin/p2-preparer/main.go
pkg/preparer/orchestrate.go
pkg/preparer/setup.go
pkg/preparer/status.go

Allows the preparer to publish its status on a socket instead of a port.

Extract status server, enable socket status reporting

---

pkg/kp/kv.go

The `showConsulErrors` flag was created before the "param" package was written,
and it used the tool it had available at the time: command line flags. These
have been awkward to work with, so this commit migrates variable from being a
Kingpin flag to being a parameter.
With this change, the library functionality of P2 (e.g., nearly everything in
"pkg") no longer depends on any particular CLI framework.

Use params to control Consul detailed errors

---

bin/p2-rctl/main.go
pkg/kp/rcstore/consul_store.go
pkg/rc/farm.go
pkg/rc/fields/fields.go
pkg/roll/farm.go
pkg/roll/run_update.go

If a rolling update is deleted from Consul, the farm automatically
releases the lock that it took on that update, under /locks/rolls/id.
But the update itself also claimed locks on the two RCs it was using.
Those locks also have to be released, or otherwise the update cannot
be Prepare()d by someone else.
To fix this, we make Update.Run() a long-lived function with an error
channel return (instead of bailing on the first error). Then, when Run()
terminates, we release the locks claimed by Prepare(). The caller would
have to call Prepare() again before resuming Run().

Release RC write locks on Run() termination

---

pkg/preparer/orchestrate.go

When receiving an error reading from reality in certain cases, we would block forever. This explains why during a Consul reset, a number of preparers would suddenly hang forever. Follow up work should alter the status checker to perform a liveness check of the various routines we care about.

remove deadlock case

---

pkg/hooks/hook_env.go
pkg/hooks/hooks.go

This makes it easier for hooks to locate a pod's env directory via
environment variables. It is essential for hooks to compute a pod's env
directory in this manner so that hooks will maintain compatibility with
a preparer change that moves the env directory

Add a EnvPath() function to HookEnv

---

bin/p2-exec/main.go
pkg/cgroups/cgroups.go

This commit changes p2-exec to use a different method for changing its cgroup
membership: it will write "0" to the cgroup's "cgroup.procs" file. Writing to
this file will change membership for the current thread group (e.g., the entire
process) instead of an individual thread. This may be a fix for a bug wherein a
launched service is observed to be running in the root cgroup.

Use "cgroup.procs" for cgroup membership

---

bin/p2-rctl/main.go
pkg/kp/rcstore/consul_store.go
pkg/rc/replication_controller.go
pkg/replication/replication_test.go
pkg/roll/farm.go
pkg/roll/run_update.go

See commit message. This simplifies the semantics of the function a bit and avoids potential races against program exit (where the program might live long enough to accidentally delete an update that wasn't finished yet, if asked to quit the update on termination). Particularly cc @bwester since I went over this code with you and you might be better positioned to review it.

Handle errors inside Update.Run

---

pkg/pods/pod.go
pkg/watch/health_test.go

This shouldn't be in the logrus message in the first place; parametric data should be in fields.

Move post-activate output to logrus field

---

pkg/rc/fields/fields.go
pkg/rc/fields/fields_test.go

Adds documentation to the main Resource Controller data structure. Also
provides a concrete specification of its JSON-encoded format, which will be
used to store the structure into Consull.

Documents pkg/rc/fields.RC and specifies its JSON format

---

pkg/kp/consulutil/safe.go
pkg/kp/consulutil/watch.go
pkg/kp/consulutil/watch_test.go
pkg/kp/kv.go
pkg/preparer/listener.go

There are already several implementations of code that watches Consul for a list of keys and does something with the changed ones.  Each implementation has its own quirks in how it polls Consul (unnecessary) and its own way of processing the results into specific object types (necessary).  The intent of this PR was to write a more uniform, robust implementation of this procedure that could be re-used by other methods inside `pkg/kp/...` and still allow them to add type-specific behavior.
The changes to `"pkg/kp".consulStore.WatchPods()` is illustrative of the kind of change that I intent to make on other stores.  It doesn't reduce the line count, but I think the result is more robust and has cleaner separation into generic and type-specific parts.
The PR isn't quite complete in that I …

Generic prefix watcher

---

bin/p2-inspect/main.go
pkg/health/checker/checker.go
pkg/kp/consulutil/safe.go
pkg/kp/healthmanager.go
pkg/kp/kv.go
pkg/kp/lock.go
pkg/kp/rcstore/consul_store.go
pkg/kp/rollstore/store.go

Changes SafeList() to only return errors that have already been wrapped in the
KVError type. This greatly simplifies error handling around the WatchPrefix()
function.
To do this, I had to move the KVError type into the "consulutil" package to avoid
a circular import.

Emit KVErrors directly from SafeList()

---

pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/launch/launchable.go
pkg/opencontainer/containers.go

as observed by @bwester , the type aliasing doesn't work for interface type assertion. We need real structs to wrap around the errors. (cough sum type cough)

Use wrapper structs around typed errors

---

.travis.yml
Rakefile

Silences a new linker warning for the -X flag:
```
$ rake install
go install -a -ldflags "-X github.com/square/p2/pkg/version.VERSION $(git describe --tags)" ./...
link: warning: option -X github.com/square/p2/pkg/version.VERSION 0.0.10-49-gc46c850 may not work in future releases; use -X github.com/square/p2/pkg/version.VERSION=0.0.10-49-gc46c850
```

Update to go1.5.1

---

pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/hoist/test_helper.go
pkg/launch/launchable.go
pkg/opencontainer/containers.go
pkg/pods/pod.go
pkg/pods/pod_test.go

this will allow us to export an environment variable to launched
processes that will allow them to find the root of the launchable
easily.

write an 'env' dir in the launchable root with LAUNCHABLE_HOME var

---

bin/p2-exec/main.go

This will allow us to provide environment variables from multiple
directories to a process. The immediate motivation is to combine
pod-wide environment variables with launchable-specific environment
variables.

Allow multiple --env arguments to be passed to p2-exec

---

pkg/hoist/hoist_launchable.go
pkg/launch/launchable.go
pkg/opencontainer/containers.go
pkg/pods/pod.go
pkg/pods/pod_test.go

The variable used to point to the top level directory for a launchable,
e.g. /data/pods/<pod>/<launchable> in a default preparer configuration.
It's more useful to have a variable that tells the launchable where it
has been installed, e.g.
/data/pods/<pod>/<launchable>/installs/<launchable>_<version>/

Modify the LAUNCHABLE_HOME variable to be LAUNCHABLE_ROOT

---

pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go

Adds a quick fix for a bug in which app will be installed twice. More details
are in the patch itself.
Tested manually by watching scheduling a manifest, waiting for the preparer to
pick it up, then scheduling the same thing again. This procedure is sufficient
to get the earlier version to install twice. With this change, it doesn't.

Fix double-launch bug

---

pkg/util/size/bytes.go
pkg/util/size/bytes_test.go

This will be used for parsing cgroup memory sizes as well as configuring the p2-preparer with a max `installs` directory size per pod.

add byte string converter

---

pkg/hoist/hoist_launchable.go
pkg/hoist/prune.go
pkg/hoist/prune_test.go
pkg/launch/launchable.go
pkg/opencontainer/containers.go
pkg/pods/pod.go
pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go
pkg/preparer/setup.go

This change prevents launchable directories from exceeding a
configurable size limit by removing cached installations from oldest
to newest until the limits have been overcome. This pruning facility
ignores directories pointed at by the `current` and `last` symlinks.

Prune launchable directories over specified size limit.

---

bin/p2-launch/main.go
pkg/auth/policy.go
pkg/preparer/setup.go

Adds --auth-type, --keyring, and --deploy-policy flags.
If launching a signed manifest from an untrusted source, a user of
p2-launch may wish to verify the signature of the manifest against a
deploy policy just as the preparer does.

Add flags to p2-launch to support user auth policy

---

pkg/hoist/hoist_launchable.go
pkg/p2exec/p2_exec.go
pkg/p2exec/p2_exec_test.go

This allows us to utilize the launchable-specific env directory and
export the variables within it to the launched process(es)

Pass multiple env dirs to p2-exec when launching a launchable.

---

pkg/cgroups/cgroups.go
pkg/cgroups/config.go
pkg/cgroups/config_test.go
pkg/pods/manifest_test.go
pkg/pods/pod_test.go

This change allows manifest authors to specify a shorthand for
the byte limits of their cgroups. Previously, all `memory` entries
for the `cgroup` stanza had to be in the form of an integer
number of bytes. Authors may now use a shorthand as defined by
the package `github.com/square/p2/pkg/util/size`.
An author wishing to limit their launchable to a maximum resident
memory limit of 4 Gibibytes may use the shorthand `4G` instead of
`4294967296`.
The old form of specifying an integer limit of bytes is also supported.

Allow shorthand for memory limits.

---

pkg/cgroups/cgroups.go
pkg/cgroups/config.go
pkg/cgroups/config_test.go
pkg/pods/manifest_test.go
pkg/pods/pod_test.go
pkg/util/size/bytes.go
pkg/util/size/bytes_test.go

Changes the cgroup.Config struct so that it preserves its old serialization.
For example, an input of "4K" is valid and parses to 4096, but regardless of
the input format, it will always serialize as 4096. This will allow older tools
to continue to work with the update input format, and it will ensure that there
is a single canonical representation of any manifest.

Preserve cgroup serialization

---

pkg/hoist/hoist_launchable.go
pkg/runit/runit_service.go

Fixes two bugs involving forcible termination of runit services. In both cases, a reliance on SIGKILL to terminate a process would incorrectly prevent other services from being killed or started.

handle kills correctly

---

bin/p2-rctl/main.go

Increases the "LockDelay" timeout in the Consul session used in p2-rctl rolling
update operations. This change gives p2-rctl a little time to detect that its
lease on the RCs has expired and cease its modifications before another p2-rctl
(in Farm mode) thinks it has exclusive access. It doesn't technically improve
the correctness of the rolling update, but hopefully it makes it harder for a
bad execution to occur.

Give p2-rctl time to clean up

---

bin/p2-rctl/main.go
pkg/roll/fields/update.go
pkg/roll/run_update.go

Changes the rolling update execution logic to always delete pods from the old
RC. The existing use case, "when scheduling a new pod on a node will also stop
the old one (eg hoist artifacts)," turns out to be a bad example. If the old RC
isn't kept up-to-date and later becomes re-enabled (e.g., by reversing the
update), it will instantly re-deploy all its nodes, probably violating the
update's minimum replicas constraint. It's better just to update all the time.
Other resulting changes: remove the "DeletePods" field from the Update struct
and the "-delete" flags from the p2-rctl command.

Always delete pods in a rolling update

---

bin/p2-rctl/main.go

Adds a node-identifying description to Sessions created by the p2-rctl command.
Without this information, it's difficult to trace back and query which nodes
has opened which session.

p2-rctl: Name new Consul sessions

---

pkg/preparer/setup.go
pkg/watch/health.go

Services should always be able to respond to a healthcheck within
five seconds of the connection initiation. If longer-running status
checks are required, they should be backgrounded and cached.

Limit healthchecks to 5 seconds

---

pkg/kp/healthmanager.go

Small change, makes it easier to identify healthchecking in logs.

add pod to the healthchecker logger

---

bin/p2-log-bridge/main.go
pkg/logbridge/doc.go
pkg/logbridge/logbridge.go
pkg/logbridge/logbridge_test.go
pkg/pods/manifest_test.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/preparer/orchestrate.go
pkg/preparer/setup.go
pkg/runit/servicebuilder.go
pkg/runit/servicebuilder_test.go

A generic bridge from an io.Reader to an io.Writer. This also allows us to configure a log executable on a per pod basis. Internally, we'll use this to catch logs from stdout and route them into our logging infrastructure.
Please pay special attention to style, logging convention and testing convention. This is my first PR into this repo.

p2 log bridge

---

bin/p2-preparer/main.go
pkg/preparer/listener.go
pkg/preparer/listener_test.go
pkg/preparer/orchestrate.go

This avoids a race condition where simultaneous pod updates and hook
updates are scheduled while the preparer is stopped. We want to
guarantee that when it is started, hooks are processed before any other
pods so that th epod will benefit from any hooks being installed

Sync hooks once before starting normal pod management

---

pkg/labels/applicator.go
pkg/labels/consul_aggregator.go
pkg/labels/consul_aggregator_test.go
pkg/labels/consul_applicator.go
pkg/labels/consul_applicator_test.go
pkg/labels/fake_applicator.go
pkg/labels/http_applicator.go

This change introduces watches for label selectors. This is especially useful for forming abstractions around label selectors, such as Kubernetes-style Services.
This implementation attempts to cache the result of the label tree, with a watch in place to get updates over time. Watches share the same cache result. See function documentation for details.

Add watches for label selectors

---

pkg/pods/manifest.go
pkg/pods/manifest_test.go

This is for convenience so that callers modifying a manifest's config do
not need to check if it is nil before doing so

Instantiate empty config map in GetConfig() if necessary

---

bin/p2-bin2pod/main.go
integration/single-node-slug-deploy/check.go
pkg/pods/manifest.go
pkg/pods/manifest_test.go

This avoids modification of config maps returned by GetConfig() from
mutating the underlying manifest or eachother.
Copying is done by marshaling to yaml and then unmarshaling into a new
map. This introduces a chance for an error, but by doing error checking
when configs are set we can guarantee that in practice these errors
should not occur, and if they do then something is very wrong and thus
we panic.

Make manifest.GetConfig() return a deep copy of the config map

---

bin/p2-log-bridge/main.go
pkg/logbridge/logbridge.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/preparer/orchestrate.go

When https://github.com/square/p2/pull/319 was merged, we were not sure how log-bridge would be installed on our systems. It turns out that it fits naturally as a secondary launchable for p2-preparer.

Update p2 log bridge path

---

pkg/logbridge/logbridge.go
pkg/logbridge/logbridge_test.go

The output delivered to the lossy logger is stripped of its newlines by the
default scanner. This change adds a new splitter that preserves newlines so
that the output stream of the lossy logger is the same as stdin.
---
After digging into the implementation of bufio.Scanner, it turns out that it
maintains one internal array as a large input buffer, and all the tokens it
returns are slices from that shared array. This works fine if the application
fully-handles each token as it's encountered, but logbridge asynchronously
sends them to the lossy writer. If the lossy writer is slow, there is the
potential for the array's data to have been overwritten by the Scanner by the
time a slow lossy writer gets to the slice. The data handled would not be the
same as the data sent.
This commit copies …

logbridge: Preserve newlines and copy data

---

pkg/kp/kv.go
pkg/kp/rcstore/consul_store.go
pkg/kp/rollstore/store.go
pkg/labels/consul_aggregator.go
pkg/labels/consul_applicator.go
pkg/preparer/listener.go
pkg/preparer/listener_test.go
pkg/preparer/orchestrate.go

Changes all callers of api.KV.List(), consulutil.SafeList(), or
consulutil.WatchPrefix() to append an extra "/" to the end of the watched
string.  Also changes kp.Store.ListPods() and kp.Store.WatchPods() to accept a
"path" to a Consul subtree, not an arbitrary "prefix." All existing callers of
of these two methods already pass subtree paths, e.g., `kp.*_TREE` or
`kp.*Path(hostname)`, so this shouldn't change any existing behavior.
These changes are an extra safeguard to make sure that a List operation returns
the right results in the presence of path components that are subsets of each
other. For instance, if two nodes were named "node1" and "node10", listing all
of node1's pods (e.g., List("intent/node1")) would previously have returned
node10's pods too (e.g., …

Always list keys with an extra "/"

---

pkg/roll/fields/update.go

It stated that DesiredReplicas should be at least equal to the value for
MinimumReplicas. However, in a use case where only part of a cluster
should be updated, it may be desired to deploy only to a subset while
maintaining a level of health greater than the number of nodes being
updated.

Change comment about DesiredReplicas on fields.RC

---

.travis.yml

The old download location quit working. At the time of this commit, the
official Consul website lists the included URI as the location to find
consul-0.5.2.

travis-ci: Download consul binary from Hashicorp

---

bin/p2-bootstrap/bootstrap.go
bin/p2-inspect/main.go
bin/p2-schedule/main.go
bin/p2-watch/main.go
pkg/kp/constants.go
pkg/kp/constants_test.go
pkg/kp/kv.go
pkg/kp/rcstore/consul_store.go
pkg/kp/rcstore/store.go
pkg/kp/rcstore/store_test.go
pkg/kp/rollstore/store.go
pkg/kp/rollstore/store_test.go
pkg/preparer/listener.go
pkg/preparer/listener_test.go
pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go
pkg/preparer/setup.go
pkg/rc/farm.go
pkg/rc/replication_controller.go
pkg/rc/replication_controller_test.go
pkg/replication/replication.go
pkg/replication/replication_test.go
pkg/replication/replicator.go
pkg/replication/replicator_test.go
pkg/roll/farm.go
pkg/roll/run_update.go
pkg/types/types.go
pkg/watch/health.go

Previously the kp package provided functions (e.g.
kp.IntentPath(string...)) that would simply join the passed strings
with a "/" in between and return a consul path that would be used. This
means all callers need to know the structure of consul keys and do
sanity checking against bad things happening.
These functions are replaced with functions that are named more
explicitly to indicate what the caller wants.

Add type safety when computing consul key paths

---

pkg/health/health_state.go
pkg/hooks/hooks.go
pkg/kp/healthmanager.go
pkg/preparer/orchestrate.go
pkg/types/types.go

* Adds messages when we're about to install, launch, or execute a hook.
* Adds messages when a pod has changed health or is flapping.

Add some useful log messages

---

pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/launch/launchable.go
pkg/runit/test_helper.go

The log process is not bound by the RestartPolicy because we need to be
restarted in case of a crash regardless of what the service does.

Restart a log agent whenever we restart a service

---

pkg/hoist/hoist_launchable.go
pkg/runit/runit_service.go

7 seconds is runit's default wait period for stopping processes: http://smarden.org/runit/sv.8.html
We are less friendly to the log agent than the service it is paired with
primarily because we need the log agent to boot before the service does. Not
having a log agent on the reading end of STDOUT, STDERR may result in
indigestion for the service.

Reduce restart timeout period for log agent

---

pkg/hoist/hoist_launchable.go
pkg/launch/launchable.go
pkg/opencontainer/containers.go
pkg/pods/manifest.go
pkg/pods/pod.go
pkg/pods/pod_test.go

This is a useful feature that is mostly, but not entirely,
solved by CONFIG_PATH. There are occasions where code
cannot conveniently use the exported YAML file for config,
despite being a more flexible configuration system. This
is especially true for legacy or 3rd party software that
is conventionally configured with environment variables.
A bug I discovered while implementing this: the current
implementation of the opencontainer launchable does not
support pod-supplied variables.

Launchables may specify environment variables

---

pkg/roll/fields/update.go
pkg/roll/run_update.go
pkg/roll/update_test.go

RollDelay establishes a required period of inactivity prior to
altering any underlying RCs. See the documentation for more
information.

Adds RollDelay to rolling updates

---

pkg/labels/applicator.go

This will allow labels to be applied to rolling updates so they can be
located using label selectors

Add label type for rolling updates so that they may be labeled

---

pkg/rc/replication_controller.go
pkg/rc/replication_controller_test.go
pkg/roll/run_update.go

Adds a consistency check to replication controllers so that they will ensure
that their nodes are running the same pod manifest specified in the RC.

Make replication controllers ensure consistency of their nodes

---

pkg/logging/logging.go
pkg/logging/logging_test.go
pkg/logging/process_counter.go
pkg/logging/process_counter_test.go
pkg/preparer/setup_test.go

This change refactors the logging package to be little more than a thin wrapper
around Logrus's native data structures. The wrapper allows P2 to add some extra
functionality to Logrus, like recording more information about errors and
attaching a sequential counter.
With this refactor, a couple bugs are also fixed:
* Use atomic increments in the ProcessCounter type to avoid data races
* Allow WithError() calls to work correctly when given as a second field, e.g.:
`logger.WithField(...).WithError(e)`

logging: Defer most operations to Logrus

---

pkg/uri/uri.go

Several command line tools use the generic URI parsing library to fetch their
arguments. These tools are painful to use interactively due to their insistence
on using only absolute file paths. This change allows relative paths to be used
for schemaless URIs (local files) to make commands easier to type.

Allow fetching from relative file paths

---

pkg/kp/lock.go
pkg/rc/farm.go
pkg/roll/farm.go

code using pkg/kp as a library will have a much easier time testing
functionality that relies on locking if the implementation can be
mocked. Furthermore, the underlying (consul) api.Client that the kp.Lock
struct contains is also a struct type and cannot be mocked.

make kp.Lock into an interface so that tests may mock it

---

bin/p2-replicate/main.go
pkg/replication/common_setup_test.go
pkg/replication/replication.go
pkg/replication/replication_test.go
pkg/replication/replicator.go
pkg/replication/replicator_test.go

Now that replication controllers are actively managing their pods' intent
manifests, the only effective way to change a pod's manifest is by going
through its controller. Simply changing the intent store, like what a
replicator does, will succeed, but the controller will reset the node later.
That probably isn't what was intended.
This commit changes the replicator to check whether its targeted pods are
already managed. If so, the replication is aborted.

Prevent replicator from overwriting managed pods

---

bin/p2-rm/main.go

This commit adds the "p2-rm" command, which can be used to remove/unschedule a
pod from a node. It will delete the pod's manifest from intent and remove any
labels attached to the pod. If the node pod is being managed by a controller,
it will print a warning message but allow the deletion.
Sample execution:
$ p2-rm --node mynode mypod
warning: mynode/mypod is managed by replication controller: 12345678
To reduce the controller's capacity, use "p2-rctl set-replicas"
mynode: successfully removed mypod
$ p2-rm --node mynode unmanagedpod
mynode: successfully removed unmanagedpod

Add p2-rm command

---

bin/p2-rctl-server/main.go
bin/p2-rctl/main.go

Moves the "p2-rctl farm" command into its own binary, "p2-rctl-server". This
separates the resource controller functionality into two distinct parts: CLI
tools and long-running services. This makes it easier to give end users only
the parts that might be relevant to them.

Move farm command from p2-rctl to p2-rctl-server

---

bin/p2-rctl-server/main.go
bin/p2-rctl/main.go
pkg/kp/consulutil/session.go
pkg/kp/consulutil/session_test.go
pkg/kp/healthmanager.go
pkg/rc/farm.go
pkg/roll/farm.go

Adds the `WithSession()` helper method for working with Consul sessions. Launches a function in a goroutine when a session appears; asks the function to exit when the session dies. This method provides a simple model for processes that require sessions but don't want the added complexity of handling session refreshes.
This helper is used to simplify the main "farm" loops for resource controllers and rolling updates so they don't need cases for lock management. It doesn't save on lines of code, but the new farms have a better separation of concerns and `WithSession()`'s session handling is more robust (incidentally implementing the "TODO: restart the watch so that you get updates right away?" functionality).
This was part of a larger planned refactor/generalization of the resource …

Refactor session locking out of RC/RU farms

---

pkg/preparer/orchestrate.go
pkg/preparer/setup.go

This is based on several weeks of testing.
Editorially: I'd like to refactor this to be encapsulated inside of pod and to use the P2.ExecArgs type. I've started on that work here[1] and hope to deliver it soon.
https://github.com/square/p2/compare/master...rudle:rudle.implement-finish?expand=1

All pods get logBridgeExec

---

pkg/hoist/hoist_launchable.go

This fixes a case where forcibly terminating the log agent would prevent the `enable` part of the Hoist launchable lifecycle from executing. This allows this case to proceed without error.

don't warn if log agent is KILLed

---

bin/p2-rctl-server/main.go
pkg/roll/farm.go
pkg/roll/update_test.go

Roll farms may now take an RC selector to decide whether it should
pick up a particular RU request. This can be used to assist in RU
partitioning of work or to create test environments.
Note that this is _not_ required for RU farms to cooperatively schedule work.

Allow RU farms to limit which RCs they operate on.

---

pkg/kp/rcstore/consul_store.go
pkg/kp/rcstore/fake_store.go
pkg/kp/rcstore/store.go
pkg/kp/rcstore/store_test.go
pkg/rc/farm.go
pkg/roll/run_update.go
pkg/types/types.go

There are 3 kinds of locks that are applied to a replication controller:
1) an "ownership" lock, which should be held by the goroutine that
carries out the intent of the replication controller. These goroutines
are spawned by an rc farm.
2) a "mutation" lock. This should be held by any tool that intends to
modify a replication controller. This could be a commandline tool, or an
rolling update goroutine spawned by the roll farm, for instance.
3) an "update creation" lock. This is not currently used, but is useful
for guaranteeing that no conflicting rolling updates are admitted to the
store. A process trying to schedule a rolling update should first grab
the update creation lock for each replication controller it will operate
on, then confirm there are no rolling updates that refer to …

Add functions to rcstore for various rc locks

---

pkg/roll/run_update.go
pkg/roll/update_test.go

If it's a value receiver instead of pointer receiver, the struct fields
for the kp.Unlockers don't get updated, and we never end up unlocking
the held locks.

Make update.LockRCs have pointer receiver in pkg/roll/run_update.go

---

pkg/kp/rollstore/consul_store.go
pkg/kp/rollstore/store.go

This was the only operation provided in the past for creating rolling
updates. Its use is discouraged because it does not provide any safety
guarantees around consistency of data (e.g. a RU being created with
references to RCs which don't exist).
It is being resurrected to ease clients of this library onto the new
functions without forcing.

Replace rollstore.Put() function

---

pkg/roll/run_update.go

Sorry for making a mistake in ef9e8fcc4c80d4231c30a154ecaedc44c6946efc

roll: log message change, blocking for NEW nodes not OLD

---

pkg/roll/run_update.go

This helps when we are in a canary deploy. Imagine a canary deploy with
2 minimum health but only 1 canary desired.
The RU will move 1 node to the new side, then wait for 2 nodes to be
healthy on the new side, which is impossible.
The old side is allowed to contribute toward health too. This will allow
the above-mentioned canary deploy to terminate.

roll: terminate when OLD + new healthy exceed minimum health

---

pkg/pods/manifest.go
pkg/preparer/setup.go
pkg/watch/health.go
pkg/watch/health_test.go

Since p2-preparer runs on the same node, it can talk to the app on
localhost in order to check its health. This way apps can serve the
status port on the loopback interface only. In many cases, it's not
necessary to expose it to the outside world. Closes #392.

Query health through localhost

---

pkg/health/checker/test/fake_checker.go
pkg/replication/common_setup_test.go
pkg/roll/run_update.go
pkg/roll/update_test.go

Note for reviewers that the first four commits in this PR are the same as #414 (Except rebased off of master and I switched around the order of values in the `rollAlgorithmsParams` test). This is because for various reasons I don't want to merge #414 yet, but want these commits because they're necessary to write the tests I want for this bugfix.
So the only commit that is new is the last commit in the sequence: https://github.com/square/p2/commit/d72fedd0b7e114f8278cbac82c2a714a3f74d8e4

roll: Safe behavior if old desired < old healthy

---

pkg/p2exec/p2_exec.go
pkg/p2exec/p2_exec_test.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/preparer/orchestrate.go
pkg/preparer/setup.go
pkg/preparer/setup_test.go
pkg/preparer/test_preparer_config.yaml
pkg/runit/servicebuilder.go
pkg/runit/servicebuilder_test.go

Here's a first cut at configurable finish executables for our runit integration. Pay special attention to the changes to to servicebuilder.go wrt the process _shell_ for the call to finish (keeping in mind that the app's env will also be present at this time).
This PR assumes we will ship one version of finish for all pods. I could imagine a world in which pod's could override finish but I can't imagine the use case just yet.
I hope to write some more tests for this - though I'm hoping to get feedback on the direction first. I've verified that this works in a testing environment.

Implement basic finish functionality

---

pkg/roll/run_update.go
pkg/roll/update_test.go

The health check would have always been true assuming rollAlgorithm had
correct operation. But we should block until the RC has labeled enough
pods so that post-update operations can examine the nodes just-deployed
to by calling newRC.CurrentPods()

roll: Terminate when current >= desired

---

pkg/roll/run_update.go
pkg/roll/update_test.go

We wish to be conservative because we don't want to mistakenly take down
a node of unknown health only to find out that it is healthy. The other
advantage of this is that it supports easily migrating apps from other
deployment systems which may not report health.

roll: conservatively treat unknown-health nodes as healthy; support capacity increase

---

pkg/roll/run_update.go
pkg/roll/update_test.go

This reverts commit 0ffe7f9987a432451a241fb7a394762c22848a3a.
The reason we thought we wanted that commit was because enables the case
of a migration from a different deployment tool onto p2. For example, if
we have three unknown nodes on the old side and minimum health is 2, we
want to roll one node at a time.
However, this code is inapplicable in a migration from a different
deployment tool, because the nodes simply will not exist on the old RC.
The old RC's desired node count will be 0, since that is the default
number for an old RC. So the unknown health code path never gets
triggered.
The proper way to support migrations from another deployment tool is
d045410ce859ab06b5c1ad46904e108de5912754.
We ran into a case today where we mistakenly rolled a node under this
condition:
```json
{ …
```

Revert "roll: conservatively treat old unknown-health nodes as healthy"

---

bin/p2-rctl-server/main.go
pkg/rc/farm.go

Previously only roll farms supported a selector to use to partition work
into a test environment. It's also useful to have this capability for RC
farms.

Support rcFarmSelector in RC farm

---

pkg/kp/rollstore/consul_store.go
pkg/kp/rollstore/consul_store_test.go

Some rollstore operations depend on member fields that were not being
set in the rollstore constructor. This commit fixes that.

Fix rollstore by populating all member fields in constructor

---

pkg/kp/rcstore/consul_store.go
pkg/kp/rcstore/consul_store_test.go
pkg/kp/rollstore/consul_store.go
pkg/kp/rollstore/consul_store_test.go
pkg/roll/fields/update.go

Previously, if the consumer of the RC watch was very slow, we might
receive new updates from consul while we're still blocking on writing
the previous update. Now, if we receive a new update while still
attempting to write the old one, we just move on to the most recent
update.

Only write the latest RC list to consumer of rcstore.WatchNew

---

pkg/rc/farm.go
pkg/rc/farm_test.go

This PR adds two failsafes to the RC farms to prevent
catastrophic unscheduling of pods across the cluster. This
situation is generally hypothetical, but I'd rather be safe
than sorry.
The first situation is - the farm will panic if zero RCs have
been scheduled in Consul. This currently doesn't prevent any
specific behavior other than the farm abandoning working on RCs,
but is worth signaling that it has occurred.
The second situation would be genuinely catastrophic. If replica
counts were all 0, the RC farm would go on a killing spree across
the cluster, unscheduling all services. In practice this should
never happen.

Failsafes for rc farms

---

pkg/roll/run_update.go
pkg/roll/update_test.go

We experienced the following with a deploy with desired 3 nodes and
minimum 1 node.
```json
{
"msg": "Adding 2 new nodes and removing 2 old nodes",
"new": {
"Desired": 0,
"Current": 0,
"Real": 0,
"Healthy": 0,
"Unhealthy": 0,
"Unknown": 0
},
"nextAdd": 2,
"nextRemove": 2,
"old": {
"Desired": 3,
"Current": 3,
"Real": 3,
"Healthy": 3,
"Unhealthy": 0,
"Unknown": 0
},
"pod": "censored",
},
{
"msg": "Adding 2 new nodes and removing 2 old nodes",
"new": {
"Desired": 2,
"Current": 2,
"Real": 2,
"Healthy": 1,
"Unhealthy": 1,
"Unknown": 0
},
"nextAdd": 2,
"nextRemove": 2,
"old": {
"Desired": 1,
"Current": 1,
"Real": 1,
"Healthy": 1,
"Unhealthy": 0,
"Unknown": 0
},
"pod": "censored",
}
```
The first is OK, but the second represents a serious error since now
there are four desired nodes which is …

roll: set remaining as target desire - new desire, not new healthy

---

pkg/labels/consul_aggregator.go
pkg/labels/consul_aggregator_test.go

This change makes it possible for many label watchers to be subscribed to the same aggregator without incurring penalties due to individual watches being slow.

Allow updates to other clients to proceed

---

pkg/labels/applicator.go
pkg/labels/consul_aggregator.go
pkg/labels/consul_aggregator_test.go
pkg/labels/consul_applicator.go
pkg/labels/fake_applicator.go
pkg/labels/http_applicator.go

These are two commits that improve the performance of label watches, see commit messages for details.

Label watch optimizations

---

pkg/kp/rollstore/consul_store.go
pkg/kp/rollstore/store.go

One way to specify the old RC to use when creating an RU is by using a
label selector. If the selector matches more than one RC, an error is
returned.
This commit makes the roll store return a special error type in this
case so that callers can detect this error type and generate more useful
error messages. In Square's application of this function, an error of
this type means that a deploy is already in progress and thus there are
two RCs that match the selector.

Return a specific error type if oldRCSelector is ambiguous

---

bin/p2-rctl/main.go
integration/single-node-slug-deploy/check.go
integration/travis.sh
pkg/labels/consul_applicator.go
pkg/rc/replication_controller.go

This change expands the role of the integration test to run
a p2-rctl-server. Instead of scheduling a `hello` pod directly
on the host, we instead create a `hello` replication controller
and verify that hello gets correctly scheduled on the host
running the integration test.
One of the new conditions verified is that the `hello` pod gets
labeled with the RC that scheduled it in the label tree. This
exercises the relatively new label aggregation and watch behavior.
This change was relatively painless. The next step is to actually
attempt a rolling update through the same p2-rctl-server.

Add p2-rctl-server to integration test

---

pkg/rc/farm.go

In steady state, all RCs are locked and the RC farm was emitting a log
message for each RC it encounters that is already locked. This
contributes to a lot of log lines that are not very informative. This
commit removes that

Remove a common log line in rc farm

---

pkg/kp/rollstore/consul_store.go
pkg/kp/rollstore/consul_store_test.go

Since we expect the old RC to be a copy of the new one, then we should
copy the labels as well, except that was not done.
Not copying the labels results in some schemes that assume the label
presence to not be able to find the old RC (since it has no labels).

rollstore: If created an old RC, apply new RC's labels

---

pkg/rc/farm.go
pkg/rc/farm_test.go
pkg/rc/rcmetrics/metrics.go

This means less work for callers using the RC Farm library for setting
up metrics, and it means that the RC farm can add metrics at any time
without callers needing to write any code.

Use the metrics.Registry interface for rc farm metrics

---

pkg/kp/constants.go
pkg/kp/consulutil/session.go
pkg/kp/kptest/fake_session.go
pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go
pkg/kp/pcstore/pcstoretest/fake_pcstore.go
pkg/kp/pcstore/store.go
pkg/kp/rcstore/consul_store.go
pkg/kp/rcstore/store_test.go
pkg/kp/rollstore/consul_store.go
pkg/kp/rollstore/consul_store_test.go

This adds a required Session argument to pod cluster creation, ensuring that the pod cluster for a given 3-ple of pod ID, availability zone, and cluster name does not already exist.

Check for existing Pod Clusters on creation

---

pkg/kp/consulutil/watch.go
pkg/kp/kptest/fake_kv.go
pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go
pkg/kp/pcstore/pcstoretest/fake_pcstore.go
pkg/kp/pcstore/store.go

This is an early pass at implement Watch() for pcstore. It is explicitly missing a filter on the ID parameter inside of the watch function. I'm likely to do the naive thing unless someone suggests something more clever.

pcstore implements Watch()

---

pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go
pkg/kp/pcstore/pcstoretest/fake_pcstore.go
pkg/kp/pcstore/store.go

the full set of all pod clusters, not just individuals.
This makes the pc store match the same pattern as the
preparer's pod watch, allowing both addition and deletion
to be supported.

When watching the pod cluster tree, return the full set of pod clusters

---

pkg/kp/pcstore/pcstoretest/fake_pcstore.go

The Create() function on the fake pcstore does not check if a watcher
exists before attempting to write to it, which can cause deadlocks in
tests that depend on it.

Fix a potential deadlock in fake pcstore

---

pkg/runit/servicebuilder.go

```    finish_exec:
- /data/pods/p2-preparer/p2-finish/current/bin/extract_from_env.rb
- '$1'
- '$2'
- '|'
- base64
- '-w0'
- '|'
- socat
- '-'
- UNIX-CONNECT:/data/pods/p2-preparer/tmp/p2-finish.sock```
Is what we're using in production.

remove unused variable

---

pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/preparer/setup.go
pkg/runit/servicebuilder.go

If we don't do this, we end up running a process as the root user.

Drop privs in the default log exec

---

bin/p2-inspect/main.go

`p2-inspect` could be a lot faster if we don't assume we're always querying for everything

if --node specified, don't query for everything

---

pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go
pkg/kp/pcstore/pcstoretest/fake_pcstore.go
pkg/kp/pcstore/store.go

The code to watch both pod cluster definitions / annotations and their
labeled pods is complex enough that it warrants being factored into a
common library. Clients need only implement the `pcstore.ConcreteSyncer`
interface and pass it to `store.WatchAndSync(syncer, quitCh)` to implement
a concrete implementation of a pod cluster synchronization loop.

Implement `WatchAndSync` for pcstore

---

pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go

Watch() gives a list of *pcfields.PodCluster, but was unintentionally
populating the list with a pointer to a loop variable that gets
rewritten so that all values passed would be pointers to the same value
(the last value in the for loop).

Fixes bug in pcstore.Watch()

---

pkg/health/checker/checker.go
pkg/health/checker/checker_test.go
pkg/health/checker/test/fake_checker.go
pkg/replication/common_setup_test.go

With a single watch, we can observe all changes to the health tree.
Discerning the delta is left up to the caller. In the use case I have, computing the delta is not interesting but presenting fresh data is. I chose to keep this simple to minimize consul load and code complexity.

Implement checker.WatchHealth

---

pkg/kp/pcstore/consul_store_test.go

The test would flake because we start a watch before creating the
watched objects, and depend on the length of the returned results.
However the watch might return before the creations and result in
flakes.

fix a test flake

---

pkg/kp/consulutil/session.go
pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go
pkg/kp/pcstore/pcstoretest/fake_pcstore.go
pkg/kp/pcstore/store.go

This will allow multiple copies of the same implementation of
ConcreteSyncer for pod clusters to run and use locking to ensure that
only one instance is handling an update for a given pod cluster.

add function to pcstore to allow locking a pod cluster for sync

---

pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go
pkg/kp/pcstore/store.go

This change requires implementations of `pcstore.ConcreteSyncer` to implement `GetInitialClusters()`. 
The use case for this function is to enable concrete syncers to be notified of potential deletions that may have occurred during period of downtime or lack of connectivity. Assume the following scenario:
1. Pod cluster A is created
2. ConcreteSyncer S synchronizes A
3. S shuts down for maintenance
4. A is deleted
5. S resumes, unaware of A's deletion
The desired behavior above is to synchronize the deletion of A, but this is not possible because the `WatchAndSync` function can only watch the generic pcstore as defined in this project. Syncers track their own status information in their own implementation-specific ways. Soon we'll be adding a `StatusStore`, but that too must allow …

implement GetInitialClusters()

---

pkg/health/checker/checker.go
pkg/health/checker/checker_test.go
pkg/health/checker/test/fake_checker.go
pkg/health/store/store.go
pkg/health/store/store_test.go
pkg/kp/consulutil/watch.go
pkg/replication/common_setup_test.go

This allows clients to lookup health without introducing load on the
datastore.
Also improve the channel semantics in &checker.WatchHealth().
We value fresh values over the durability of messages in this channel.
The `types.NodeName` references are as small as possible now, I will follow up with a better rename in a subsequent PR.
Additionally, we have discussed changing the pattern of channels as arguments. Since this change will affect all of health on its clients it is a little risky. I will introduce this in a subsequent PR.

Implement cached health store

---

pkg/kp/constants.go
pkg/replication/replication.go
pkg/replication/replication_test.go
pkg/replication/replicator_test.go

When using `p2-replicate` for large numbers of pods it quickly becomes burdensome to use a per-node pod lock. The original intent of per-node locking was to allow parallel deployments to multiple environments simultaneously. Now that our recommended deployment system is to use rolling updates + replication controllers, which do not use pkg/replication to achieve their work, we can focus on making `p2-replicate` effective for today's primary use cases (deploying agents).

Use pod-wide lock in replication

---

pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go
pkg/kp/pcstore/store.go

`SyncCluster` would previously be called on every return from the
label watch. Clients were implementing their own variation of rate
limiting and throttling to deal with the flow of calls. This change
reduces the frequency of unnecessary calls to `SyncCluster`.
`SyncCluster` is still expected to be idempotent. It is still guaranteed
to be called (possibly redundantly) when the watch against the pcstore
expires.

Only call `SyncCluster` if pods or cluster change.

---

pkg/kp/pcstore/consul_store.go

This makes it consistent with our other store types instead of being the
single case that takes a value instead of a pointer.

Make the pcstore constructor take api.Client as a pointer

---

pkg/kp/pcstore/consul_store.go
pkg/pc/fields/fields.go
pkg/pc/fields/fields_test.go

We now only call `SyncCluster` when the pod cluster object itself
has changed. When `WatchAndSync` is first called it will proceed
to call `SyncCluster` for all returned pod clusters and will only
submit differences following that.

Further optimize calls to SyncCluster

---

pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/store.go

This allows callers to attempt to create pod clusters and have custom
handling for the case where a pod cluster creation fails due to the pod
cluster already existing. This is useful when relying on idempotent
creation for example.

add a PodClusterAlreadyExists error type

---

bin/p2-log-bridge/main.go
pkg/logbridge/logbridge.go
pkg/logbridge/logbridge_test.go

logbridge needs a metric registry so we can understand log lines per unit time and log bytes per unit time.

Log bridge metrics

---

bin/p2-watch/main.go
pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go
pkg/kp/pcstore/store.go

For certain syncer types, it may take non-negligible amounts of time to
sync a pod cluster. This commit adds support for providing a metrics
registry to the pod cluster store. If a registry is set, a metric will
be added for pod cluster sync time and data points will be collected.

Collect metrics on SyncCluster() time

---

pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/pcstoretest/fake_pcstore.go
pkg/kp/pcstore/store.go

This makes it usable by code that doesn't have access to the concrete
type.

add SetMetricsRegistry to the pcstore.Store interface

---

pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go

pcstore.WatchAndSync() calls the concrete syncer's GetInitialClusters()
function in order to notify the syncers of pod cluster deletions that
occurred when the syncer wasn't running.
However, handlePCUpdates only begins a label query on the pod cluster's
pod selector if something has changed, and there was no apparent change
since we were seeding the data with the GetInitialClusters() call.
This commit fixes that by only seeding the pod cluster changes with the
ID of the pod cluster if it was returned in GetInitialClusters().
The behavior change of this is that a watch will be started for every
pod cluster, and a SyncCluster() call will also be called once per pod
cluster even if the view of the world hasn't changed, perhaps resulting
in some performance degradation when the syncer starts …

Fix a bug where a label watch wouldn't be started for some pod clusters

---

pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go

Previously a metrics.Timer was used, but it is more straightforward to
use a Gauge. The most recent processing time can be extracted with
gauge.Value()

Use a metrics.Gauge to measure pod cluster sync time

---

pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go

A histogram makes more sense here because pod cluster updates will be
frequent and fast, while a metrics graphing library may only sample
metrics every 30 seconds for example. A histogram metric will provide a
more useful average with an exponentially decaying window to smooth out
outliers.

Use a histogram instead of a gauge for recording pod cluster sync time

---

pkg/preparer/orchestrate.go
pkg/preparer/setup.go

apparently svlogdExec was unused before this change. The type change
did not cause any compiler error.

Support a configured pod blacklist for logbridge

---

bin/p2-bin2pod/main.go
bin/p2-install-hook/main.go
bin/p2-launch/main.go
bin/p2-replicate/main.go
bin/p2-verify-artifact/main.go
pkg/auth/artifact_verifier.go
pkg/auth/artifact_verifier_test.go
pkg/digest/verification.go
pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/hoist/test_helper.go
pkg/opencontainer/containers.go
pkg/pods/manifest.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/uri/uri.go
pkg/uri/uri_test.go

This paves the way for an upcoming change which will allow an
alternative method of specifying artifact download.

Make launchable.Location a url.URL type instead of a string

---

bin/p2-bin2pod/main.go
bin/p2-bootstrap/bootstrap.go
bin/p2-inspect/main.go
bin/p2-pcctl/main.go
bin/p2-rctl/main.go
bin/p2-replicate/main.go
bin/p2-restart/main.go
bin/p2-rm/main.go
bin/p2-run-hooks/main.go
bin/p2-ssh-monitor/main.go
bin/p2-sum/main.go
bin/p2-watch/main.go

Fixes a bunch of warnings raised by running "gometalinter" on all the
binary packages. Changes mostly eliminate dead code, check error
return values, and adjust variable names/cases.

Fix lint errors in binaries

---

pkg/kp/rcstore/consul_store_test.go

The TestPublishLatestRCs unit test failed with the following output:
Unexpected error on errCh: <nil>
The probable immediate cause is that the channel was closed while the
unit test was stopping. Once `quitCh` is closed, the goroutine that
feeds into `errCh` will eventually close that channel too. If the
error-monitoring goroutine exists after that happens, and if the
select statement receives from `errCh` instead of `quitCh`, the test
will unnecessarily fail.

Fix bug in flaky unit test

---

bin/p2-pcctl/main.go
pkg/pc/control/control.go
pkg/pc/control/control_test.go

This better matches the use cases we've encountered in reality.
Some duplicate code here, but I'm ok with it because it seems very unlikely that we'll change it in the near future. I wouldn't be surprised if we delete the label parameters for Get, Update, Delete

Add mutually exclusive ID command line flag

---

bin/p2-rctl-server/main.go
bin/p2-rctl/main.go
pkg/kp/consulutil/watch.go
pkg/kp/dsstore/consul_store.go
pkg/rc/farm.go
pkg/rc/replication_controller.go
pkg/rc/replication_controller_test.go
pkg/roll/farm.go
pkg/roll/run_update.go
pkg/scheduler/scheduler.go

Move rc/scheduler.go to its own package
scheduler.go used to be in the rc package, but because it will now
be used with daemon sets, it would make more sense for it to be
in its own package.
This will also fix the issues with the watch for daemon sets.

Move scheduler to its own package

---

pkg/preparer/setup.go

Prevents an NPE on `tlsConfig.InsecureSkipVerify` in the following code in `pkg/preparer/setup.go` by returning a `tls.Config` that trusts nothing instead of `nil`:
```
func (c *PreparerConfig) GetInsecureClient(cxnTimeout time.Duration) (*http.Client, error) {
tlsConfig, err := getTLSConfig(c.CertFile, c.KeyFile, c.CAFile)
if err != nil {
return nil, err
}
tlsConfig.InsecureSkipVerify = true
...
```

Return a TLS config that trusts nothing instead of nil to prevent NPE

---

pkg/ds/daemon_set.go
pkg/ds/daemon_set_test.go
pkg/kp/dsstore/dsstoretest/fake_dsstore.go
pkg/labels/consul_applicator.go
pkg/rc/replication_controller.go
pkg/rc/replication_controller_test.go
pkg/roll/update_test.go

This commit will:
Provide functionality for writing to the intent tree for daemon sets
Provide unit tests for this functionality
Fix kp/dsstore/fake_dsstore.go so that in-memory tests will work

Write pods to intent tree for daemon sets

---

pkg/pods/pod.go

Previously the behavior was to refrain from launching a launchable if
its post-activate script failed, but still consider the launch of the
pod successful. This results in a confusing user experience when the pod
is partially started due to post-activate failures.
This commit simply logs the post-activate failure but proceeds to launch
each launchable anyway. The launchable status check will hopefully
capture any actual problems resulting from post-activate failing to run,
which will cause a deploy to stall via rolling update.

Launch launchables even if post-activate fails

---

bin/p2-bin2pod/main.go
bin/p2-verify-artifact/main.go
integration/single-node-slug-deploy/check.go
pkg/artifact/downloader.go
pkg/artifact/registry.go
pkg/artifact/registry_test.go
pkg/auth/artifact_verifier.go
pkg/auth/artifact_verifier_test.go
pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/pods/manifest.go
pkg/pods/manifest_test.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/preparer/listener_test.go
pkg/types/types.go

We're planning to support two methods of specifying the location from
which a launchable may be downloaded:
1) using the "location" field in LaunchableStanza
2) using the "version" field in LaunchableStanza. This method is
currently not implemented to keep this commit smaller.
Previously all artifact downloads used the "location" field, and when
artifact verification is desired, the supplementary files needed to
verify the artifact (such as manifest and signatures) were inferred from
the artifact location by adding some special suffixes.
When the "version" scheme is used, an artifact registry will instead be
queried using the artifact metadata under the "version" key (as well as
other data) and the location of the artifact will be returned along with
the locations of the supplementary …

Modify auth.ArtifactVerifier interface to take VerificationData struct

---

pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/pods/pod.go
pkg/pods/pod_test.go

Normally we expect a launchable to have a location URI whose base is of
the form <launchable_id>_<version>.tar.gz. Prior to this commit, errors
would occur during artifact installation if the location did not match
these scheme, since no version can be parsed out of the location.
This commit simply logs a warning if this occurs, but otherwise will
proceed without the version information for backwards compatibility with
launchables that don't fit the format.
Version is primarily used to determine the name of the directory the
launchable will be installed in, using <launchable_id>_<version>. If
version is blank, the directory will just be <launchable_id>. This means
that launchables that do not have version information in their location
will fail to install new updates as the preparer will …

Support launchables with locations that don't match typical format

---

pkg/pc/fields/fields.go
pkg/rc/fields/fields.go

Due to the fact that the RC and PC structs contain custom types that do
not marshal to JSON automatically, representing them as JSON involves
going through an intermediary type named RawRC and RawPC, respectively.
This commit adds convenience functions for converting an RC or PC to the
corresponding json-friendly type.

Adds convenience functions for marshaling RC and PC types as JSON

---

pkg/roll/run_update.go

The message was "could not lock update", when in reality it is the
replication controller lock failure that is causing the message. This
commit changes that to "could not lock rcs"

Fix misleading log message in RU

---

pkg/health/checker/checker.go
pkg/kp/consulutil/watch.go
pkg/kp/consulutil/watch_test.go
pkg/kp/kv.go
pkg/kp/pcstore/consul_store.go
pkg/kp/rcstore/consul_store.go
pkg/kp/rollstore/consul_store.go
pkg/labels/consul_aggregator.go

The pause signifies the amount of time to wait after the consul server
returns a watch result. Clients that can tolerate a high degree of
staleness of returned data can specify a large pause interval to reduce
QPS on the consul store. This is still preferable to polling because the
client can remain responsive when data turnover is slow, but can
significantly reduce QPS if data turnover is high.

Add a configurable "pause" time duration to consulutil.WatchPrefix

---

pkg/kp/rollstore/consul_store.go

This adds some words that might make this error clearer to users of P2 not familiar with our objects' acronyms.

clarify error message

---

bin/p2-rctl/main.go
pkg/kp/rollstore/consul_store.go
pkg/kp/rollstore/consul_store_test.go
pkg/kp/rollstore/store.go

This is useful for being able to look up rolling updates by labels, for
example if you wanted to find the rolling update associated with a
particular pod cluster.

Make rollstore label the RU with a passed label set

---

pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/pods/test_manifest.yaml

Prior to this commit, the version detection code would do so incorrectly
on some artifact names. Now the regex enforces that the version is
a 40 character hexadecimal string with an optional hyphenated suffix.
This resulted in some bad install directory names. For example, a
launchable with id "foo_launchable.tar.gz" would be installed in a
directory named "foo_launchable_launchable/" because the launchable ID
was concatenated with the supposed version "launchable". The desired
behavior would have been for versionFromLocation() to return an error
and the ID of "foo_launchable" alone would be used to determine the
directory name.

Make version detection from location URL stricter

---

pkg/ds/daemon_set.go
pkg/ds/daemon_set_test.go
pkg/labels/applicator.go
pkg/labels/consul_aggregator.go
pkg/labels/consul_applicator.go
pkg/labels/consul_applicator_test.go
pkg/labels/fake_applicator.go
pkg/labels/fake_applicator_test.go
pkg/labels/http_applicator.go
pkg/rc/replication_controller.go
pkg/types/types.go

Minor changes:
Share the PodLocation structure between RCs and DSs
Ask the caller to WatchDesires to send a daemon set when a change has been made so that you can verify it
Fix tests to for the above change to WatchDesires
Major changes:
Add a WatchMatchDiff function for each daemon set process to detect changes in node tree
Provide and modify tests for the above WatchDiff function

Provide functionality to notice changes in node tree

---

pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/hoist/test_helper.go
pkg/manifest/manifest.go
pkg/pods/pod.go

This field is only used by hoist launchables, and enumerates the path to
a file or directory of files that should be used as entry points for
runit services. If there are no entry points enumerated, a default value
of bin/launch is used which matches the behavior of all hoist
launchables prior to this commit.
A constraint is enforced that no two runit services may have the same
name, which translates to entry points necessarily having differening
file names. For example, a manifest specifying ["bin/launch",
"bin/start"] for entry point is invalid if bin/start and
bin/launch/start are files in the tarball because those would result in
runit services with the same name.

Add support for the "entry_points" field in launchable stanza

---

bin/p2-cgroup-info/main.go

Add a new p2-cgroup-info command that displays information about which
cgroups contain running P2 launchables.

Add p2-cgroup-info command

---

pkg/labels/consul_applicator.go

Modify labels to notice the initial state of the labels store
Also removed an unnecessary nil value check on the values because  a check for the closed channel is already made
How this notices the intial state of the labels store is that by not
taking the initial state, the diff loop will believe that any initial
labels in the store are created and they will be signalled

Modify watch labels diff to notice the initial state

---

pkg/cgroups/cgroups.go

Add support for hierarchical cgroups to be created by including the "/"
character in a cgroup's name when passed to p2-exec.

cgroups: Allow hierarchical names

---

pkg/hoist/hoist_launchable.go
pkg/pods/pod.go

Refactor the hoist.Launchable struct so that the name of the cgroup it
will use is explicitly configured instead of being implicitly the same
as the service ID. A future change will alter the cgroup naming scheme.

Make cgroup name explicit in hoist.Launchable

---

pkg/pods/pod.go

Prior to commit f6635afd588c9a3d79e137565166f0cc8a399a66, each
launchable type would check exit the Install() function early if the
launchable was already installed. When this code was moved to the pods
package, the behavior was not preserved, and installation is always
attempted which would result in errors due to files already being
present.
These errors would result in the whole install directory being deleted
and the installation being reattempted, at which point it would succeed.

Restore the Installed() check before installing a launchable

---

pkg/ds/daemon_set.go

This is because it is not actually scheduling pods yet but rather
labelling them, this will reduce confusion in the log messages.

Change scheduling to labelling in daemon set

---

pkg/ds/daemon_set.go
pkg/ds/farm.go
pkg/kp/dsstore/dsstoretest/fake_dsstore.go

This is mainly for fixing some bugs with how locks are handled in the farm.
There is also a fix to cancel the replication when a daemon set is disabled.
There are also additional logging and removing an unnecessary check for whether a daemon set is in the map or not.
This also includes a change in the fake dsstore to imitate the real dsstore's locking mechanism.

Replication bugfixes and logging

---

bin/p2-bootstrap/bootstrap.go
bin/p2-rctl/main.go
bin/p2-rm/main.go
bin/p2-watch/main.go
pkg/health/checker/checker.go
pkg/kp/config.go
pkg/kp/consulutil/clients.go
pkg/kp/consulutil/consultest.go
pkg/kp/consulutil/session.go
pkg/kp/consulutil/session_controller.go
pkg/kp/consulutil/session_controller_test.go
pkg/kp/consulutil/watch_test.go
pkg/kp/dsstore/consul_store.go
pkg/kp/fixtures_test.go
pkg/kp/healthmanager.go
pkg/kp/kv.go
pkg/kp/pcstore/consul_store.go
pkg/kp/rcstore/consul_store.go
pkg/kp/rollstore/consul_store.go
pkg/kp/rollstore/consul_store_test.go
pkg/labels/consul_applicator.go
pkg/replication/common_setup_test.go

This will allow providing a fake *api.Client to stores for use in tests
that provides all of the necessary functionality. The main motivation
for this commit is to add more tests to the kp.consulStore struct.
Unfortunately this change required a bit of gymnastics around Go's type
system. *api.Client is a struct with KV() and Session() methods that
return structs providing functionality for interacting with consul keys
and consul sessions, respectively.
The ConsulClient interface captures the KV() and Session() functions
that return sub-interfaces that we use, since tests will ultimately want
to fake out the KV and session portions of consul functionality.
Unfortunately, a raw *api.Client does not implement the ConsulClient
interface because the return types of its KV() and Session() …

Mask *api.Client behind a ConsulClient interface in stores

---

pkg/kp/statusstore/consul_store.go

This makes it easier for 3rd party code to use the status store, because
kp.NewConsulClient now returns a ConsulClient interface backed by an
*api.Client instead of the client itself.

Make statusstore use a ConsulClient instead of *api.Client

---

pkg/ds/fields/fields.go
pkg/ds/fields/fields_test.go
pkg/kp/dsstore/consul_store.go
pkg/kp/rcstore/consul_store.go
pkg/rc/fields/fields.go
pkg/rc/fields/fields_test.go

When unmarshaling a JSON-encoded RC or DaemonSet, skip creating a
manifest object if the Manifest field is empty. This allows the zero
value for the RC and DaemonSet types to be decoded without being a parse
error. It was already OK for a zero value to be encoded. This leads to
strange errors where an object that contains an RC/DS can be encoded but
cannot be decoded.
RCs/DSs without a Manifest are still not valid, and their main Store
interfaces will still reject objects that do not contain a Manifest.
This preserves any existing consistency guarantees.

rc, ds: Permit unmarshaling zero values

---

pkg/ds/daemon_set.go
pkg/ds/daemon_set_test.go
pkg/ds/farm_test.go
pkg/health/checker/test/fake_checker.go
pkg/kp/kptest/fake_store.go
pkg/replication/common_setup_test.go
pkg/replication/replication.go

When unscheduling some pods, the replication needs to be cancelled, but
some pods were being scheduled even though they weren't supposed to
because of a counting error due to currentNodes not being updated.
Previously, an update to daemon sets would quickly cancel the
replication and re-enact it, but it does not wait for replication to
gracefully release the session locks, this commit will fix that problem.
The health has also been faked in the daemon set and daemon set farm test. 
The locks in replication have also been faked, but is a lazy implementation. 
Because of this, we can now remove the nil health checker condition for daemon set unit tests.

Fix unscheduling bug and daemon set update race conditions

---

pkg/ds/daemon_set.go

This will make daemon sets more robust to pod lock contention during
replication

Add functionality for daemon sets to retry replication on error

---

pkg/artifact/registry.go
pkg/labels/http_applicator.go

It is a hopeless task to debug a JSON decode error without knowing the
input document. Many JSON documents exist in P2 in a durable format
where they can be examined after a failures, e.g., a file on a disk or a
key in Consul. However, the response to a remote API call isn't always
reproducible, so this changes the error messages to include the first 80
characters of the response when querying the artifact registry and an
HTTP label applicator. I am guessing that 80 chars is enough to show
what kind of response was received without overwhelming the logs.

Include response output in remote API call errors

---

bin/p2-bootstrap/bootstrap.go
bin/p2-cgroup-info/main.go
bin/p2-install-hook/main.go
bin/p2-launch/main.go
bin/p2-restart/main.go
bin/p2-run-hooks/main.go
pkg/hooks/hook_env.go
pkg/hooks/hooks.go
pkg/hooks/hooks_test.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/preparer/listener.go
pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go

Add new config option to preparers that changes how they name cgroups.
Instead of creating a singe directory in the cpu and memory resource
controller named "{pod}__{launchable}", the new scheme uses a nested
hierarchy of "p2/{node}/{pod}/{launchable}".
To use the new cgroup name, set the "nested_cgroups" parameter in
the preparer configuration.

Create nested cgroup names

---

bin/p2-dsctl/main.go

I experimented with including more things here (NodeSelector, manifest SHA, etc) but it got a bit unwieldy. This is enough info to help one use `p2-dsctl get` or `p2-dsctl update` and get the full scoop on the DS you're interested in.

improve the information density of dsctl's list command

---

pkg/labels/http_applicator.go

Add an "Accept: application/json" header to the requests sent by the
httpApplicator type. Only JSON is accepted, and the server is only
allowed to return JSON, but having an explicit Accept header plays
nicely with HTTP middleware.

labels: Add "Accept" header to HttpApplicator requests

---

pkg/health/store/store_test.go

Found during unit testing:
{"Counter":0,"PID":94138,"cachedHealth":0,"level":"error",
"msg":"Cache miss!!","time":"2016-08-08T19:18:20Z"}
res [0xc8200f2aa0 0xc8200f2af0]{"Counter":1,"PID":94138,
"cachedHealth":0,"level":"error","msg":"Cache miss!!",
"time":"2016-08-08T19:18:20Z"}
--- FAIL: TestStartWatchBasic (0.00s)
store_test.go:76: expected health store to have podID1
FAIL
FAIL    github.com/square/p2/pkg/health/store   0.021s
Note the two cache miss log messages. There should only be one.
Fix the synchronization in the "pkg/health/store".TestStartWatchBasic() unit
test to ensure that the health store watcher processes at least one health
state before the first Fetch() operation.

Fix flaky unit test: TestStartWatchBasic()

---

pkg/replication/replication.go

Replication was taking too long and was always timing out because a
return statement was missing.
https://github.com/KoishiKomeiji/p2/blob/087a0abcbadf77d40302db123637866addba310b/pkg/replication/replication.go

Add a missing return statement in replication

---

pkg/ds/daemon_set.go

Based on our experience with Daemon Sets in the wild, it is more
valuable to have multiple Daemon Sets executing replications at once
than it is to mutually exclude them to prevent operator error.
Considering the failure cases of overlapping Daemon Set selectors - they
are similar under values of this boolean. If we mutex replications per
pod, then we experience an undefined state of intent/ on any hosts in
the intersection. If we remove the mutex, then this undefined behavior
is more apparent (as it may change multiple times per minute) but it is
no worse or better than in the case using the mutex.

override locks

---

pkg/pods/pod.go

When writing a pod's config and platform config files, make the
procedure a little more robust to rare errors:
* Fix nil pointer dereference when the open() fails
* close() earlier and detect its errors
An empty platform config file was observed on one host. I don't have any
particular insight into how that could happen, but these changes might
help.

pods: Write config files robustly

---

pkg/hooks/hook_env.go

The PodFromDisk() function returned an error if there was no
current_manifest.yaml on the disk for that node. This was to protect
agains thooks loadinga pod struct from disk before it is placed.
However, some hooks are knowingly loading the pod after it has been
installed but before the current manifest exists.
This check has been replaced with a check that the hook event is
BEFORE_INSTALL, in which case the pod should not be loaded from disk.

Remove buggy check in hookenv.PodFromDisk()

---

pkg/health/store/store.go
pkg/preparer/orchestrate.go

There are two routines that both had identical "Quitting..." log
messages, and it's unclear what they mean. Now the messages are more
specific to the functionality that is stopping.
Furthermore, the routine watching for pod updates would make it look
like the pod being managed itself is quitting, rather than the
p2-preparer quitting (usually for an update). This can cause confusion
as it makes it look like all of the preparer's pods are being shut down
at the same time.

Improve the "quitting" log messages in p2-preparer

---

bin/p2-ds-farm/main.go
bin/p2-rctl-server/main.go
pkg/kp/healthmanager.go
pkg/util/stream/publisher.go
pkg/util/stream/publisher_test.go

* p2-ds-farm: Remove string publisher
One subscriber doesn't need a publisher
* stream: Remove user-provided channels for subscriptions
It was never used
* p2-rctl-server: Move Subscribe() call near its use
Good hygiene

Minor updates to session publisher

---

bin/p2-norm/main.go

Add the "p2-norm" command. It reads a pod manifest and prints it in a
normalized format. This command is useful when comparing manifests where
one or both are hand-edited and may differ in trivial ways, like the
ordering of keys or spacing.

Add p2-norm command

---

pkg/types/types.go

This is done so that PodLocation can be used as an index in a map

Add json tags to PodLocation

---

pkg/kp/kv.go
pkg/kp/kv_test.go
pkg/kp/podstore/consul_store.go
pkg/kp/statusstore/podstatus/consul_store.go
pkg/types/types.go

The field was obviously used to differentiate PodUniqueKey structs that
signify a UUID from those that don't. Prior to this commit, the ID field
would be the consul key e.g. /intent/<node>/<pod_id> if IsUUID was
false.
After making use of PodUniqueKey, it's becoming clear that this struct
is ONLY useful in contexts where it's signifying a UUID. As a result,
this commit removes the IsUUID field and uses a nil pointer to a
PodUniqueKey to signify a legacy pod that does not have a UUID.

Remove IsUUID field from PodUniqueKey struct

---

bin/p2-wipe-reality/main.go
pkg/kp/flags/kingpin.go

This allows a host that has been manipulated by hand to be fully restored to the state set in Consul. For discussion: should we not operate on the preparer itself?

Add command to reset reality for a host

---

pkg/ds/daemon_set.go
pkg/ds/daemon_set_test.go
pkg/ds/farm_test.go
pkg/kp/kptest/fake_preparer.go
pkg/replication/replication.go
pkg/replication/replicator.go

Added a waiting function that can wait up to a total of 5 seconds for the farm to finish running when waiting for the ds farm to apply its labels.
I am going to test this on travis CI a couple times to make sure it works.

Un-flake daemon set tests and and fix replication bug

---

pkg/hooks/hooks.go

some hooks stop services that take as long as 60s to cleanly shutdown.

Double the hook timeout

---

pkg/health/checker/checker.go
pkg/kp/dsstore/consul_store.go
pkg/kp/pcstore/consul_store.go
pkg/kp/rcstore/consul_store.go

We observe a lot of network and disk read IO and we suspect it's related
to hungry watches on big trees. Presently, our consul trees are large:
/labels = 7 Megabytes
/intent,/reality = 57 Megabytes
/replication_controllers = 2.5 Megabytes
We need to be more cognizant about the costs of this data access pattern as it relates to our current datastore. I note, without comment, that differential watches are not coming soon to consul.

Increase WatchPrefix latency where appropriate

---

pkg/replication/replication.go
pkg/replication/replicator.go

Bugs fixed:
1) A 1 nanosecond ticker is not a safe default because that causes a lot
of CPU work. Now the ticker used for rate limiting will just be nil if
the specified wait interval is 0, and goroutines will only attempt to
read a value off the ticker's channel if the ticker is not nil.
2) Goroutines pulling values off the ticker's channel also read off of
the quit channel in a select, which will prevent workers from stalling
forever if the ticker is stopped before the workers exit.
3) A check for the ticker's channel being closed was removed because it
will never be closed according to time.Ticker's documentation.

Fix bugs related to rate limiting replications.

---

pkg/replication/replication.go

We scan reality before attempting to schedule any pods on any host
whatsoever. This will improve the performance and scalability of daemon
sets triggered by host restarts or changes in node label matches (ie. imaging).
This is a proof of concept - I still need to write tests for it.

[WIP] only replicate to nodes that we need to

---

pkg/ds/daemon_set.go
pkg/replication/replication.go
pkg/replication/replicator.go

InitializeReplicationWithCheck's first argument now controls whether
locks are skipped completely, rather than overridden (now they always
are).
InitializeReplicationWithCheck's first argument now controls whether
locks are skipped completely, rather than overridden (now they always
are).
This is the only place in the code where InitializeReplicationWithCheck
is called.
The behavior change: Now, daemon sets will ignore locks.
This change is desired:
Consider the case where two daemon sets with the same pod ID are
started.
Currently, the second one will override the lock of the first one, and
the first one will stop replicating completely.
That means some nodes do not get the pod installed (if the second one
does not cover all desired nodes)
Since this is undesirable, instead we will skip …

daemon_set: skip locking

---

pkg/launch/launchable.go

When serializing a launch.LaunchableStanza, omit the "location" and
"version.tags" fields when they are empty. This change makes a serialized
manifest a little prettier.

launch: Omit empty "location" and "version.tags"

---

pkg/logging/logging_test.go
pkg/logging/process_counter.go

ProcessCounter.Fire() contained a data race modifying the entry.Data map
to add the "Counter" and "PID" fields. Logrus makes a copy of the Entry
object, but it is shallow, so multiple loggers could share the same map.
The bug is fixed by having Fire() update a copy of Data.

logging: Fix data race adding "Counter" to entries

---

pkg/kp/consulutil/session_controller.go
pkg/kp/consulutil/session_controller_test.go

In SessionManager, once its "done" channel is closed, there is no
guarantee that any other goroutine will be reading its output channel.
The way to prevent blocking is to send inside a select statement. When a
session is acquired, SessionManager does this; when a session is lost or
released, that send wasn't guarded. As a consequence, the SessionManager
goroutine would never exit.
This problem is fixed by adding select around the second send.

consulutil: Fix deadlock when SessionManager exits

---

pkg/logging/logging_test.go

Fix a typo in a comment of commit 1500d3d.

logging: Fix typo

---

pkg/kp/rcstore/consul_store.go
pkg/kp/rcstore/fake_store.go
pkg/kp/rcstore/store.go
pkg/roll/run_update.go

Sometimes, AddDesiredReplicas isn't the desired amount of checking that
we would like to have. AddDesiredReplicas retries its mutation so that
it is resistant to *unrelated* changes (such as the changing of the
disable flag), but if someone else changes the desired replica count, we
want to know about it. Thus, a CAS for desired replicas.
---
We are experiencing cases where session losses cause replica count
increases to happen multiple times. This attempts to stop that.

roll: CAS desired replicas

---

pkg/roll/run_update.go

Recall that the roll algorithm declares a deploy complete when the new
RC **desires** as many nodes as specified in the deploy, and at least
the minimum number of new nodes are healthy.
Imagine this situation:
We are in the middle of a deploy with 2 nodes desired, 1 node min
healthy on a 2 node environment.
* Old RC: 1 desired, 1 healthy, disabled.
* New RC: 1 desired, 1 healthy, enabled.
Roll algorithm decides (rightfully) that it can roll forward:
* Old RC: 0 desired, 1 healthy, disabled.
* New RC: 2 desired, 1 healthy, enabled.
At this point, the termination condition of the roll algorithm is met.
Upon termination, it sets the old RC's count to zero (not materially
useful; it's already at zero), **enables it** (dangerous!), and then
deletes it.
* Old RC: 0 desired, 1 healthy, enabled. …

roll: Do not enable old RC on cleanup

---

pkg/metrics/metrics.go

A metrics package appears! This package will be shared throughout the code to decouple the production of metrics from their publishing to a metrics store.
Both Registry & ExpHandler and exposed for mutation by downstream code that wants to use a custom Registry or bind this handler into their app.

introduce pkg/metrics

---

pkg/kp/consulutil/session_controller.go
pkg/util/randseed/seed.go

Add an exponential backoff strategy to SessionManager to deal with
errors encountered while creating a session. Session loss is a
highly-correlated event, so jitter is added to mitigate a thundering
herd (mostly preparers) attempting to reestablish their sessions after a
loss occurrs.
Errors encountered while renewing a session are probably a symptom of an
overloaded Consul server, but it isn't clear how to use an exponential
backoff to mitigate that problem. This changes uses a heuristic of
sending the next create request after the maximum timeout from the last
successful create.

consulutil: Add exponential backoff to SessionManager

---

pkg/kp/healthmanager.go

Clients may unintentionally send enormous status strings in their status endpoint. While there is nothing inherently wrong with this, we do not want to store this full output in Consul. This sets an arbitrarily limit of 200 characters for status data before being truncated.
I verified that this worked using the integration test environment.

Only store 200 characters from health output

---

pkg/kp/consulutil/watch.go

Stale recursive consul list operations are 10x faster than consistent methods and nearly as safe.

Stale watches

---

bin/p2-run-hooks/main.go
pkg/hooks/hook_env.go
pkg/hooks/hooks.go
pkg/hooks/hooks_test.go
pkg/preparer/setup.go

Sometimes a hook will need to initialize a pod struct based on the
hooked pod manifest. This is useful when the pod's launchables need to
be initialized, for example in order to place a special directory in
each launchable contained in the manifest.
Commit e8d2f903 changed the way pods are initialized such that instead
of initializing a pod by knowing its $POD_HOME (i.e. the concatenation
of the system pod root and the pod id), a caller must first instantiate
a pod factory using the system root (e.g. /data/pods) and then instruct
the pod factory to instantiate a pod of a specified ID. The goal of that
commit was to reduce the number of code sites that compute a pod's home
directory, so that logic can more easily be changed.
A side effect of this change is that a hook can no longer …

Add a Pod() function to HookEnv to initialize hooked pod.

---

pkg/artifact/registry.go
pkg/artifact/registry_test.go
pkg/hoist/hoist_launchable.go
pkg/launch/launchable.go
pkg/launch/launchable_test.go
pkg/pods/pod_test.go

This adds greater type safety when working with launchable version IDs.
This is useful for systems that support upgrading or otherwise modifying
the launchable version ID within a pod manifest.

Add a LaunchableVersionID typedef backed by a string

---

pkg/roll/run_update.go

This commit fixes a bug that would occur when attempting to count the
number of healthy nodes in a replication controller if there is no
reality manifest for the pod in question.
This can easily occur if a pod has been scheduled for the first time
on a bad host which will result in the reality manifest remaining empty.

Fix RU bug if reality manifest is missing.

---

bin/p2-ds-farm/main.go
bin/p2-dsctl/main.go
pkg/ds/daemon_set.go
pkg/ds/daemon_set_test.go
pkg/ds/farm.go
pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go
pkg/kp/rollstore/consul_store.go
pkg/labels/applicator.go
pkg/labels/consul_aggregator.go
pkg/labels/consul_applicator.go
pkg/labels/consul_applicator_test.go
pkg/labels/fake_applicator.go
pkg/labels/fake_applicator_test.go
pkg/labels/http_applicator.go
pkg/labels/http_applicator_test.go
pkg/rc/replication_controller.go
pkg/rc/replication_controller_test.go
pkg/scheduler/scheduler.go

This change introduces a new parameter to the `Applicator.GetMatches`
function, `staleMatch`. It permits clients to specify whether or not
they tolerate cached results from the applicator or not.
The `ConsulApplicator` has been modified to use this flag to indicate
relying on underlying Consul aggreagator's cached label set, instead of
querying Consul for the full tree on each query.
The `HttpApplicator` has been altered to pass a `staleMatch` query parameter
to the receiving service.
The ds farm implementation has been given a struct field that can
be set to enable stale queries for all daemon sets. All other usages
of `GetMatches` keep `staleMatch` disabled for now.

`cachedMatch` flag for `GetMatches`

---

pkg/kp/kptest/fake_store.go

Fix unit test error:
fatal error: concurrent map read and map write
goroutine 359 [running]:
runtime.throw(...)
runtime/panic.go:566
runtime.mapaccess2(...)
runtime/hashmap.go:340
github.com/square/p2/pkg/kp/kptest.(*FakePodStore).Pod(...)
github.com/square/p2/pkg/kp/kptest/fake_store.go:70
This commit acquires and releases locks around *all* access to the
podResults field. Commit 4462d61 appears to address the same problem.
However, it only serialized writes to the field, leaving reads to race.

Fix concurrent map access in FakePodStore

---

pkg/kp/kptest/fake_session.go
pkg/kp/kptest/fake_store.go

It looks like FakePodStore is supposed to hold a single map ("locks")
and mutex to guard access to the map ("locksMu") that are both shared
among many fakeSession values. However, the existing code passed the
mutex by value. sync.Mutex values shouldn't ever be copied, and this
also undermines the intent of the fake stores.
This commit passes the mutex by reference so that fakeSessions can share
one value.

Share the mutex in fakeSession

---

pkg/kp/consulutil/clients.go
pkg/kp/consulutil/fake_kv.go

Includes additional methods in the ConsulKVClient and
ConsulSessionClient interfaces. This brings these interfaces closer to
the actual method set of api.KV and api.Session structs.

Expand Consul*Client interfaces

---

.travis.yml
bin/p2-wipe-reality/main.go
pkg/auth/artifact_verifier_test.go
pkg/config/config.go
pkg/ds/farm.go
pkg/health/store/store_test.go
pkg/hoist/hoist_launchable.go
pkg/kp/consulutil/fake_kv.go
pkg/kp/kptest/fake_pod_store_test.go
pkg/kp/kptest/fake_session.go
pkg/kp/kv_test.go
pkg/kp/pcstore/consul_store.go
pkg/kp/podstore/consul_store_test.go
pkg/kp/rcstore/consul_store_test.go
pkg/kp/rollstore/consul_store_test.go
pkg/kp/statusstore/statusstoretest/fake_status_store.go
pkg/labels/consul_aggregator_test.go
pkg/labels/http_applicator.go
pkg/logbridge/logbridge_test.go
pkg/opencontainer/containers.go
pkg/opencontainer/default.go
pkg/pods/pod_test.go
pkg/preparer/listener_test.go
pkg/preparer/orchestrate_test.go
pkg/rc/farm.go
pkg/roll/farm.go
pkg/runit/runit_service.go
pkg/runit/servicebuilder_test.go
pkg/util/mkdir.go
pkg/util/stream/publisher_test.go

Simplifies the source code formatting via "gofmt" and fixes many questionable practices flagged by "go vet".

Fix warnings found by analysis tools

---

pkg/kp/dsstore/consul_store.go
pkg/kp/dsstore/consul_store_test.go
pkg/kp/dsstore/dsstoretest/fake_dsstore.go
pkg/kp/dsstore/store.go

The test watches the daemon set channel returned by WatchAll, and the
test times out if a value is not sent on the channel after 5 seconds.
However, WatchAll() had a hardcoded 5 second time duration to wait after
receiving a daemon set update from WatchPrefix. This meant that the test
would always fail.
Now the pause time is passed in as a function argument, with a value of
0 used in the test so that it proceeds as fast as possible.

Fix the TestWatchAll test in dsstore package.

---

bin/p2-label/main.go

This doesn't do "show $ID" as a separate command yet, but it can be implemented by a partial label query.
Here's an example session:
```
➜  p2-label git:(p2-label) ./p2-label $(p2-headers) --selector "sq/hostname in (aam12.sjc1.square,aam13.sjc1.square)" --add "sq/test1=one" --labelType node
The current labels are: sq/datacenter=sjc1,sq/hardware=metal,sq/hostname=aam12.sjc1.square,sq/zone=admin
labels to be added: sq/test1=one
Continue?
Type "y" to confirm [n]: y
The current labels are: sq/datacenter=sjc1,sq/hardware=metal,sq/hostname=aam13.sjc1.square,sq/test1=two,sq/zone=admin
labels to be added: sq/test1=one
Continue?
Type "y" to confirm [n]: y
➜  p2-label git:(p2-label) p2-select "sq/test1=one"
aam12.sjc1.square
aam13.sjc1.square
➜  p2-label git:(p2-label) ./p2-label $(p2-headers) …
```

Basic functionality for p2-label

---

pkg/watch/health.go
pkg/watch/health_test.go

This matches the convention of other backend systems and protects us from any extra bytes in the response.

[RFC] Perform a HEAD request instead of a GET

---

bin/p2-inspect/main.go

Prior to this change `err` was either nil or contained a value from a
previous, unrelated error message.

Showing the correct error from AddKVPToMap

---

pkg/preparer/setup.go

As noted in https://golang.org/doc/go1.6#http2.
It would appear from https://golang.org/pkg/net/http/#Transport that we
were inadvertently enabling HTTP/2 when we did not want to.

preparer: disable HTTP/2 by setting TLSNextProto to empty map

---

bin/p2-label/main.go
pkg/health/checker/checker.go
pkg/kp/kv.go
pkg/kp/kv_test.go

Two unrelated commits in this PR. 
First, there is a bugfix for health watches. You can accidentally get the health for any service matching the string prefix of the name.
The other is a small feature for `p2-label` to allow setting labels on specific entities.

Fix health path and add feature to p2-label

---

pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/launch/launchable.go
pkg/opencontainer/containers.go
pkg/pods/pod.go
pkg/pods/pod_test.go

The previous behavior was to shut down with the following sequence:
1) disable 1st launchable
2) stop 1st launchable
3) disable 2nd launchable
...
The new behavior is to disable all launchables before stopping
launchables. This allows a launchable that depends on others for
successful operation to do shutdown handling prior to the other
launchables receiving term or kill signals.

Disable each launchable before stopping any of them.

---

pkg/labels/batcher.go
pkg/labels/http_applicator.go
pkg/labels/label_http_server.go

The HTTP label server does not need to have access to the Watch functions yet.

Further constrain the interface required for the HTTP label server.

---

bin/p2-ds-farm/main.go
bin/p2-dsctl/main.go
bin/p2-inspect/main.go
bin/p2-label/main.go
bin/p2-pcctl/main.go
bin/p2-rctl-server/main.go
bin/p2-rctl/main.go
bin/p2-replicate/main.go
bin/p2-rm/main.go
bin/p2-schedule/main.go
bin/p2-watch/main.go
bin/p2-wipe-reality/main.go
pkg/kp/dsstore/consul_store.go
pkg/kp/dsstore/consul_store_test.go
pkg/kp/flags/kingpin.go
pkg/kp/pcstore/consul_store.go
pkg/kp/pcstore/consul_store_test.go
pkg/kp/rcstore/consul_store.go
pkg/kp/rcstore/consul_store_test.go
pkg/kp/rollstore/consul_store.go
pkg/kp/rollstore/consul_store_test.go

This reduces the number of hardcoded instantiations of
`labels.NewConsulApplicator` in favor of injected labeler
interfaces that are constrained to the needs of the given client.
It also allows all CLIs to use HTTP applicators as a default option
in `kv.ParseWithConsulOptions`.

Inject labelers whenever possible

---

pkg/kp/healthmanager.go
pkg/kp/healthmanager_test.go
pkg/watch/health.go

When shutting down a consulHealthManager, its Close method will now wait for
its Consul session to be destroyed. This new behavior makes it more likely that
a clean restart of p2-preparer will be able to immediately write health values.
Otherwise, the new p2-preparer will have to wait for its previous session to
expire.

kp: HealthManager waits for session termination

---

bin/p2-rctl-server/main.go
bin/p2-rctl/main.go
bin/p2-rm/main.go
pkg/ds/daemon_set.go
pkg/ds/farm.go
pkg/ds/farm_test.go
pkg/kp/fixtures_test.go
pkg/kp/kptest/fake_store.go
pkg/kp/kv.go
pkg/kp/kv_test.go
pkg/preparer/setup.go
pkg/rc/farm.go
pkg/replication/common_setup_test.go
pkg/replication/replication.go
pkg/replication/replicator.go
pkg/roll/farm.go
pkg/roll/run_update.go
pkg/watch/health.go

kp.Store was a massive interface which makes it hard to implement with
new stores. This commit breaks up the interface into package-defined
interfaces where they are needed that only contain the functions that
are used.
This will enable implementing individual store interfaces with a GRPC
storage server.

Break up kp.Store interface into subsets

---

pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/launch/launchable.go
pkg/manifest/manifest.go
pkg/opencontainer/containers.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/runit/servicebuilder.go
pkg/runit/servicebuilder_test.go

This will allow greater flexibility in the way pods are composed and
run. For example, the scheduled pod may have an entry point that should
only run once, such as a job like a database backfill. There may be
supporting launchables that need to be up to support the job, e.g. an
instance of stunnel which should be restarted if it crashes. However,
the job should not be restarted.

Make restart policy a per-launchable setting instead of per-pod.

---

bin/p2-bin2pod/main.go
integration/single-node-slug-deploy/check.go
pkg/launch/launchable.go
pkg/manifest/manifest.go
pkg/manifest/manifest_test.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/preparer/listener_test.go

Currently P2 has two notions of launchable_id, one being the key in the
launchable stanza map, and the other being the value under
launchable_id: in the launchable stanza itself. Typically these are the
same and they cause confusion to our users.
Since maps always need keys, it makes sense to remove the inner
launchable_id key from launchable stanza and use the map key instead.

Remove launchable_id key from launchable stanza

---

pkg/preparer/setup.go

missed this when i added the finish reporting stuff

Remove unused finish_exec preparer config option

---

bin/p2-launch/main.go
pkg/constants/constants.go
pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go
pkg/preparer/setup.go
pkg/replication/replicator.go
pkg/replication/replicator_test.go

Many other packages refer to this constant, but pkg/preparer has many
dependencies that are not necessary to import to other places. Notably,
libraries wishing to use this constant would be importing sqlite
libraries and maybe even need to vendor them.
Additionally, rename POD_ID to PreparerPodID.

Move POD_ID constant from pkg/preparer to pkg/constants

---

pkg/preparer/podprocess/reporter.go

This gets around the umask for the process creating the directory with
permissions other than 0777.
Additionally, fix a bug where if the directory already existed and was
not executable, it would not be made executable (because chown 0666 was
used instead of 0777).

Chmod 0777 sqlite database directory after creating it

---

pkg/preparer/podprocess/reporter.go

Generating log messages for every finish event written to the sqlite
database can be very chatty. This commit makes these messages debug
level.

Make the exit code reporter log at debug level

---

bin/p2-rctl-server/main.go
pkg/kp/rcstore/consul_store.go
pkg/kp/rcstore/fake_store.go
pkg/kp/rcstore/store.go
pkg/rc/farm.go

The RC tree size can grow up to a few Mb in large deployments, which
means that running many instances of the RC farm results in a sizable
amount of bandwidth consumption.
This commit adds a configurable time.Duration to the RC farm which
causes it to pause in between watches on the entire RC tree. This trades
responsiveness to new replication controllers for a decrease in request
rate to the datastore (and thus a bandwidth reduction).
Individual RC watches are unaffected, so once an RC is noticed and
adopted by a farm, changes to replicas_desired will still be processed
very quickly.

Add configurable pause time between RC watches in RC farm.

---

bin/p2-preparer/main.go

P2-preparer waits for some channels to close before exiting after
receiving a SIGTERM. Commit 6d4e158e93a393b3e90f4b8fa5b39e9f9714f1e4
removed the goroutine for syncing hooks from consul, and therefore does
not close one of the channels being waited on, meaning the preparer had
to be SIGKILL'd. This PR remove the unused channel and allows the
preparer to exit after TERM.

Remove unused hook quit channel from p2-preparer entry point.

---

bin/p2-dsctl/main.go
pkg/labels/applicator.go
pkg/labels/applicator_test.go

The Kubernetes labels package ships with helper `labels.Nothing()` that returns a selector that cannot match anything. Unfortunately, this helper selector is not serializable to and from strings - attempts to do `labels.Parse(labels.Nothing().String())` result in parse errors. 
This adds a helper to P2's labels package to create a selector that is serializable.

use a serializable Nothing()

---

pkg/artifact/registry.go
pkg/artifact/registry_test.go
pkg/launch/launchable.go
pkg/pods/pod.go

Instead of always passing only the launchable ID, we need to allow the
manifest to specify an override for the launchable.
An artifact_name field is added to the version stanza of a launchable
stana for this purpose.
At the same time, we need to also pass the pod ID to the discover
endpoint (and for this there is no override), so that we can check
whether the artifact<->pod pair makes sense.
So now the pod ID is passed as the parameter in the URL, while the
launchable ID is passed as a query parameter.

artifact: Pass both pod ID and artifact name to discover endpoint

---

pkg/rc/farm.go
pkg/roll/farm.go

The replication controller and rolling update farms run many workers in
separate goroutines. Since panics such as nil pointer dereferences
happen from time to time, each worker is wrapped in a recover() in order
to catch panics and log them. However, only the panic message e.g.
"runtime error: invalid memory address or nil pointer dereference" was
being shown, with no line number or stack information.
This commit adds stack information to the output of the log message,
making it trivial to find where the original panic occurred.

Add stack to recovered panic output in farms.

---

pkg/inspect/inspect.go
pkg/launch/launchable.go

Launchables are not required to specify a Location anymore, which
changes the way we want p2-inspect to show version information.

Make p2-inspect able to understand launchable versions.

---

README.md

We listed our external dependencies. Now we'd like to list the internal
dependencies as well. An untracked internal dependency led to preparers
not being able to start, so it's good to keep track of them.

README: document internal dependencies

---

bin/p2-rm/main.go

When removing a uuid pod, the uuid is passed on the command line instead
of the node name since a node name is not necessarily enough information
to uniquely identify the pod to be removed.
However the output at the end of the script was always depending on the
node name, resulting in weird output like ": successfully removed
<app>". The output is now dependent on whether the pod removed was a
UUID pod or not.

Fix p2-rm output when removing a uuid pod.

---

integration/single-node-slug-deploy/check.go
pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/hoist/test_helper.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/preparer/setup_test.go

Commit b22751cc08446367b6181ee5b602fc0d3a469c0e had modified the naming
scheme for runit service directories (i.e. /var/service/*).
Prior to that commit, the directory names were built like the following:
"/var/service/{podID}__{launchableID}__{filepath.Base(entryPointPath)}
yielding "/var/service/some-pod__some-launchable__launch" for a pod
named "some-pod", launchable named "some-launchable" with the bin/launch
entry point used.
After that commit, the naming scheme was modified to include information
about the directory hierarchy to the entry point relative to the root of
the artifact: e.g. bin__launch is used for the entry point portion
instead of just the file basename. This allows artifacts to have
multiple entry points with the same filename (in different directories).
This commit …

Restore old naming scheme for runit service directories for legacy pods.

---

pkg/preparer/podprocess/finish_service.go
pkg/preparer/podprocess/finish_service_test.go
pkg/preparer/podprocess/reporter.go
pkg/preparer/podprocess/reporter_test.go

In order to publish information about the exit status of processes
started by a uuid pod, a runit hook is written that writes information
about each process exit to a local sqlite database. The preparer has a
"pod process reporter" which routinely polls this database for new
entries and writes them to consul.
To track the highest ID it has already seen in the database, it writes
the ID to a file at the end of each processing loop.
Sometimes we see the file end up with 0 bytes in it which means the pod
process reporter gets an error on every loop and can't do its job.
This commit adds the ability for the reporter to repair the file by
looking up the last ID in the database and writing that to the file.
This means that some finish data may be lost, but the alternative is to
double submit …

Add ability to repair the workspace file in pod finish reporter.

---

bin/p2-launch/main.go

This will allow p2-launch to launch pod manifests that have launchables
expressed using "version:" syntax instead of "location:" because that
requires doing an artifact discovery query against a registry.

Add artifact-registry-url flag to p2-launch.

---

bin/p2-ds-farm/main.go
pkg/ds/daemon_set.go
pkg/ds/farm.go
pkg/ds/fields/fields.go
pkg/replication/health_aggregator.go

We'd like to get more insight into how our daemon sets are doing
health-wise. Adding this reporting will help us do that.

ds: report eligible and healthy pods per daemon set

---

bin/p2-dsctl/main.go

This makes it easier to take a high level view of all daemon sets, for
example "show all of the node selectors currently in use".

Add --json flag to the "list" subcommand on p2-dsctl

---

pkg/labels/label_http_server.go

Two error handling functinos defined on the label server HTTP handler
would cause the server to crash in an infinite recursive stack overflow.
Now they correctly set the error code on the http response object and
update the corresponding metrics emitter.

fix stack overflow in labels http server

---

pkg/ds/daemon_set.go

Since the two logs lines are the same, I couldn't figure out which was
which, and mistook a deleted line for a not-deleted line. I would
propose making them distinguishable.

ds: Differentiate deleted/not deleted unschedule logs

---

pkg/ds/daemon_set.go
pkg/ds/daemon_set_test.go
pkg/ds/farm_test.go

It is expected that all daemon sets have non-empty target node sets at
all times.
If our label store ever indicates otherwise, we assume the label store
has erroneously returned empty results, and do nothing, to be safe.
This is similar to the p2-preparer's failsafe where it refuses to act if
it does not see its own key in intent.
The proper way to unschedule a daemon set on all its current nodes is to
delete it.

ds: failsafe: If no nodes are eligible, do nothing (and supporting commits - test changes)

---

pkg/store/consul/pcstore/consul_store.go
pkg/store/consul/pcstore/consul_store_test.go

To protect against data loss or misfiring consul queries, this commit
adds a failsafe to the pcstore.WatchAndSync function in which it will
not call "SyncCluster" or "DeleteCluster" when the pod cluster watch
returns no data.
This is because a syncer may wish to perform destructive action at the
time of a pod cluster deletion, and if the entire set goes away it may
be disastrous.

Add fail safe in pcstore.WatchAndSync to protect missing pod clusters.

---

pkg/ds/farm.go

Instead of showing the full details of all daemon sets, one per log
line, we show the count, then all IDs, in one log line.

ds: Show created, updated, deleted daemon sets more compactly

---

bin/p2-finish-env-extractor/main.go
pkg/preparer/podprocess/env_extractor.go

p2-finish-env-extractor is a binary that p2-preparer wires into runit to
capture the exit code of the processes that runit manages. In the case
of uuid pods p2-finish-env-extractor writes a row to a sqlite database
on disk to capture the exit code.
This scheme can result in lost information because writing to a sqlite
database always locks the entire database, so if multiple processes exit
at the same time they will compete for the ability to write to the
database.
This commit adds the ability to make p2-finish-env-extractor retry
errors writing to the database to improve the likelihood of a row making
it into the database.

Add retry behavior to p2-finish-env-extractor.

---

bin/p2-shutdown/main.go
pkg/runit/runit_service.go

There is a desire to gracefully shutdown pods while preserving their /intent
records. An example of when this is desirable is when performing host
maintenance on a pet host.

introduce p2-shutdown

---

pkg/labels/http_applicator.go

Prior to this commit, the http applicator's GetMatches() function only
returned an error if there was an error executing the http request: not
if the successfully-returned http response had an http error code.
This commit considers anything other than 200 to be an error that
calling code should care about.

Return error in GetMatches() for non-200 code in http applicator.

---

pkg/store/consul/consulutil/watch.go

"Stale" requests can be handled by any server node, which will then
service the request from its local state. While unlikely, it is possible
that two consecutive client requests might be serviced by two different
nodes operating under two different versions of state. This could allow
the client's second request to return data that is older than its first
one.
Fortunately, it's straightforward to check for this problem: responses
contain logical clocks, so older data can be identified by looking for a
decreasing clock. This commit adds such a check and ignores data that is
known to be old.

store: Ignore old data produced by stale Consul queries

---

pkg/rc/farm.go
pkg/rc/fields/fields.go
pkg/rc/fields/fields_test.go
pkg/roll/update_test.go
pkg/store/consul/rcstore/consul_store_test.go

This adds to the safety of the RC farm, because it allows us to
distinguish a JSON RC missing the replicas_desired field completely from
one that has it but a 0 count for the value.
It is an error to unmarshal an RC that does not have a replicas_desired
field.
This protects us against a scenario where the json tag might be changed
such that all stored RCs will have replica counts of zero. There is
already a failsafe in place that prevents the farm from taking action of
the sum of all of the rc replica counts is zero, but this adds an
additional layer of safety.

Make unmarshaling an RC with missing replicas_desired an error.

---

Godeps/Godeps.json
pkg/grpc/podstore/protos/podstore.pb.go
vendor/github.com/golang/protobuf/AUTHORS
vendor/github.com/golang/protobuf/CONTRIBUTORS
vendor/github.com/golang/protobuf/proto/encode.go
vendor/github.com/golang/protobuf/proto/extensions.go
vendor/github.com/golang/protobuf/proto/text_parser.go
vendor/google.golang.org/grpc/README.md
vendor/google.golang.org/grpc/balancer.go
vendor/google.golang.org/grpc/call.go
vendor/google.golang.org/grpc/clientconn.go
vendor/google.golang.org/grpc/metadata/metadata.go
vendor/google.golang.org/grpc/rpc_util.go
vendor/google.golang.org/grpc/server.go
vendor/google.golang.org/grpc/stats/handlers.go
vendor/google.golang.org/grpc/stats/stats.go
vendor/google.golang.org/grpc/stream.go
vendor/google.golang.org/grpc/tap/tap.go
vendor/google.golang.org/grpc/transport/control.go
vendor/google.golang.org/grpc/transport/handler_server.go
vendor/google.golang.org/grpc/transport/http2_client.go
vendor/google.golang.org/grpc/transport/http2_server.go
vendor/google.golang.org/grpc/transport/transport.go

69b215d01a5606c843240eab4937eab3acee6530 and update gRPC to v1.0.5.
Background: I'd like to upgrade the version of gRPC that Square uses,
and that requires generating proto messages with protobuf that is
consistent with what gRPC uses. (Otherwise we will get a compile error
since SupportPackageIsVersionX does not exist.)
This commit will upgrade P2's protobuf to use the latest upstream
master that is same as Square's internal fork. We also need
to upgrade gRPC to avoid the same compile error inside the p2 repo.
Run the following commands to update the dep:
```
> godep restore
> cd ~/Development/go/src/google.golang.org/grpc/
> git co v1.0.5
> cd -
> cd ~/Development/go/src/github.com/golang/protobuf/
> git co 69b215d01a5606c843240eab4937eab3acee6530
> cd -
> godep update …
```

This commit updates protobuf to

---

pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go

oneoff pods don't need to have their disable/enable scripts run because
they are oneoff jobs with immutable state. Furthermore running
disable/enable scripts may impact other pods with the same pod ID on the
same physical hardware depending on the implementation if
enable/disable.
This commit creates a (artificial at this point) distinction between
uuid pods and oneoff pods. A uuid pod is a pod whose data is stored in
the pods/ consul tree with an associated uuid. A oneoff pod is a pod
that is meant to run once and does not represent a repeatedly running
service like a web server.
These two concepts are tied together currently but now there is a
IsOneoff() function on the hoist launchable type which may change at
some point.
This commi

Don't run disable/enable for oneoff pods.

---

pkg/artifact/downloader.go
pkg/gzip/gzip.go
pkg/gzip/gzip_test.go

As we've seen time and time again, it's very difficult to get our custom
tar code right (see #116, #373, #374, #376, #623). We have decided
simply to call `tar`, dropping privileges to the RunAs user of the pod.
Using `tar` insulates us from any more edge cases we missed as long as
`tar` was the tool used to create the tarball, and dropping privileges
lets Unix permissions prevent any unintended system file modifications.

gzip: replace custom code with call to tar

---

pkg/artifact/downloader.go
pkg/gzip/gzip.go
pkg/gzip/gzip_test.go

This reverts commit c2d478a9633c68bef0d64845d56c492b7df94890, reversing
changes made to 94d5805d6a377b16ff2e2b440efad37345aee5f9.
We're not quite ready for this to go out yet, since:
1. The **tmp directory** (to which files are downloaded) needs to be
world-readable, and it is not on some machines.
2. We're not sure whether it's safe to make it world-readable, or why it
is not.

Revert "Merge pull request #739 from petertseng/gzip-as-user"

---

pkg/logging/logging.go
pkg/logging/socket_hook.go
pkg/logging/socket_hook_test.go

p2-preparer's logger allows adding a hook that will write log messages
to a socket in addition to stdout/stderr. This is useful to have another
program consume the log messages from the socket.
To allow this to work, we were always using logrus's JSON formatter
since parsing json is much easier for the program on the other end of
the socket. However this is a worse experience for humans trying to read
log messages.
This commit makes the logging package use the text formatter but makes
the socket hook a special case that will always use the JSON formatter
regardless of the formatter actually set on the logger.

Use text formatting for log messages except for in socket hook.

---

bin/p2-rm/main.go

Commit 67002b46ed79 intended to make p2-rm easier to run on oneoff pods
by making the pod ID argument optional and showing a confirmation prompt
instead. However that commit failed to remove the kingpin requirement on
the pod argument, making p2-rm fail if the argument was not provided.
This commit makes it required only for deleting legacy pods as it should
be.

Make pod argument to p2-rm optional for uuid pods.

---

pkg/preparer/setup.go

Prior to this commit the hook manifest (fetched from preparer manifest
config) was compared to the current manifest written to disk for hooks.
If the manifests were the same, hook installation was skipped.
This commit removes this check and just unconditionally installs the
hooks.
This is for two reasons:
1) Installing is low-cost anyway. We don't redownload artifacts if
they're present on the disk, and the rest is just linking and writing of
the current manifest file.
2) It's possible that the hooks might have been removed but the
current_manifest.yaml file for them was untouched, which will cause the
preparer to incorrectly not install them.

Unconditionally install hooks on preparer startup.

---

pkg/rc/replication_controller.go
pkg/roll/run_update.go

As noted in the comments, if we enable before it has met its desire, we
may momentarily unschedule a node (most likely to happen in times of
high consul latency).
---
~~WIP: probably not yet ready for merge for reasons I will explain in a comment.
If you want it urgently, you can merge it, because the code is believed functional.
But there is a small matter of code cleanliness to deal with first.~~

roll: Ensure current == desire before enabling new RC; rc: extract CurrentPods

---

bin/p2-rctl-server/main.go
bin/p2-rctl/main.go
pkg/roll/farm.go
pkg/roll/run_update.go
pkg/roll/update_test.go

The roll farm/factory took some alerter and scheduler args for the sole purpose of passing them to `rc.New`. However, with https://github.com/square/p2/pull/792/commits/59c5525c8bc80dd0d33780662904460223301d4c in #792, we no longer construct an RC, so we don't need these arguments. This PR cleans them up.

roll: cleanup unused (scheduler, alerter) args

---

pkg/grpc/podstore/client/client.go

Even though the context is currently ignored on the server side for
these functions, it's idiomatic to allow contexts to be passed all the
way through.

Take a context.Context argument in podstore client functions.

---

pkg/hoist/hoist_launchable.go

The "last" symlink points to the launchable version that was previously
running. It is used by hoist launchable pruning code to preserve the
last launchable to make sure that rolling back a pod doesn't require
re-downloading the launchable from the network.
A launchable which has a stop error such as missing entry points (which
is sometimes the desired state for a pod) was not having its last
symlink updated, and therefore a very old launchable install was being
preserved by pruning code.

Set the "last" symlink even if there is an error stopping a launchable.

---

bin/p2-rctl/main.go
integration/single-node-slug-deploy/check.go

The p2-rctl set-replicas command is very useful and powerfull, however
it's easy to make a typo and cause a problem. If the replica count being
set is lower than the currently set one, it will cause pod
uninstallations.
This commit adds a confirmation prompt which will give a user time to
confirm that the count they typed in was in fact what they wanted.

Ask for confirmation before changing RC replica count in p2-rctl.

---

pkg/roll/run_update.go
pkg/roll/update_test.go

When the logrus logger format was changed from JSON to text format, an
unintended side effect was that struct field names are no longer
printed. This commit fixes a pain point where the rolling update logger
would print structs with no field names.

Fix the format of log output of the rolling update farm.

---

.travis.yml
integration/common-provision.sh
integration/single-node-slug-deploy/check.go
pkg/store/consul/consulutil/clients.go
pkg/store/consul/consulutil/fake_kv.go
pkg/store/consul/consulutil/watch.go
pkg/store/consul/rcstore/consul_store.go
pkg/store/consul/rcstore/fake_store.go
pkg/store/consul/rcstore/store.go

TransferReplicaCounts() "transfers" a number of replicas from one RC to
another utilizing consul's transaction functionality. This allows
invariants to be maintained about the total of the replica counts of two
RCs even across consul server failures.
An integration test was added to test this functionality since it is
hard to implement a fake consul server that has the full transaction
capability.

Add TransferReplicaCounts function to consul RC store.

---

bin/p2-norm/main.go

This causes the output to be written to the file it was read from.  An error is
returned if p2-norm is reading from stdin and is passed -w / --write

Add a new -w/--write flag to p2-norm

---

pkg/roll/run_update.go
pkg/store/consul/rcstore/fake_store.go

This makes the updating of RC counts during a rolling update
transactional which means if the p2-master server or consul cluster
faults the invariant of RC count totals will not be violated.
This change notably removes the old check-and-set functionality on
updating RCs, but given that the RC mutation locks are held during a
rolling update we have reasonable confidence that the RC counts were not
mutated underneath the rolling update loop.

Make rolling update loop use rcstore's TransferReplicaCounts()

---

bin/grpc/clients/podstore/podstore.go
pkg/grpc/labelstore/client/client.go
pkg/grpc/podstore/client/client.go

The raw consul applicator implementation of WatchMatches() continually
makes HTTP requests to consul to fetch the latest labels and then
applies the selector in question. This scheme is tolerant of broken or
failed connections to the server due to retries.
The gRPC implementation did not preserve this self-healing behavior if
the connection to the server dies: it would make one RPC call initially
and then loop reading values fromt he stream. This commit retries the
RPC call if the stream is broken for any reason.

Make grpc WatchMatches() implementation retry after connection loss.

---

pkg/ds/farm.go
pkg/ds/farm_test.go
pkg/store/consul/consulutil/watch.go
pkg/store/consul/dsstore/consul_store.go
pkg/store/consul/dsstore/dsstoretest/fake_dsstore.go

Without this change, if a farm crashes, no other farm will pick up the
daemon sets managed by the former farm.
This means that if a daemon set gains a new node, nothing will schedule
onto the new node.
Attached test fails without attached code change.
Note that this is a very low-effort way to effect this change. The code
could be restructured to look more like an RC watch and get rid of
WatchDiff, but this requires more time to work with the code.

ds: Attempt to acquire unchanged daemon sets

---

integration/single-node-slug-deploy/check.go
pkg/roll/run_update.go
pkg/store/consul/rcstore/consul_store.go
pkg/store/consul/rcstore/fake_store.go

Commit feb411da55cd07df531e9614a92d12cfccaaa30d changed the rolling
update loop to batch its RC count changes into a single consul
transaction. However, there was a regression in safety introduced in
that commit which is addressed by this one.
The old code would make separate calls of CASDesiredReplicas for each
RC. That function fetches the RC, ensures that the replica count matches
one passed to the function call, and only then does a CAS operation on
the RC. This prevents a situation where the rolling update loop computes
a RC count change based on a previous count that might have changed by
the time the change is applied.
This commit makes the TransferReplicaCounts() function take similar
parameters: StartingToReplicas and StartingFromReplicas. The function
will not apply the …

Increase safety of rolling update loop via TransferReplicaCounts().

---

bin/p2-rctl/main.go
pkg/roll/farm.go
pkg/roll/run_update.go
pkg/roll/update_test.go

As a result of splitting up the giant preemptive *.Store interfaces, it
became clear that the rolling update store was passing a store that
watches RCs just to instantiate a ReplicationController struct which
wouldn't even use that parameter.
Now that it is completely unused, we can delete it from the roll farm
completely.

Remove replication controller watchers from roll farm.

---

pkg/roll/farm.go

Using a constructor is preferable in many cases to manually creating
structs because it makes the compiler complain if the constructor adds
or removes a field that is being passed.

Add constructor for the roll.UpdateFactory type.

---

pkg/replication/replication.go

The AggregateHealth was never being stopped. Luckily, since nobody reads
off the channel, it blocks sending on the channel. So we leak
goroutines, but at least it's not as bad as continually hammering
Consul.
This is safe: The only use of aggregateHealth is as an argument to
updateOne, and updatePool will stop the function from returning (and
Stopping the aggregateHealth) until all updateOne have finished.
First discovered in:
https://github.com/square/p2/pull/738#discussion_r98260867

replication: Stop health watch when done

---

pkg/ds/farm.go
pkg/ds/farm_test.go

If we have just acquired a lock on a daemon set, necessarily it is not
one of our children. Therefore, any attempt to send on its updated
channel will trigger a nil dereference. This code has never worked.
Attached test demonstrates, though "Attempt to acquire unchanged daemon
sets" of #813 alleviates the problem slightly. With #813, the attached
test only sometimes dereferences nil because sometimes the lock is still
held when the second farm attempts to access and the daemon set moves to
the "unchanged" or "same" category.
A similar mistake was fixed in #753.

ds: spawn child when acquiring lock on updated DS

---

pkg/artifact/downloader.go
pkg/gzip/gzip.go
pkg/gzip/gzip_test.go
pkg/preparer/setup.go

New commit means we are ready for this:
preparer: chmod TempDir on setup
As explained in code comments: If we extract as target user, we need to
allow them to see the tmpdir.
Original:
As we've seen time and time again, it's very difficult to get our custom
tar code right (see #116, #373, #374, #376, #623). We have decided
simply to call tar, dropping privileges to the RunAs user of the pod.
Using tar insulates us from any more edge cases we missed as long as
tar was the tool used to create the tarball, and dropping privileges
lets Unix permissions prevent any unintended system file modifications.

Reapply "Merge pull request #739 from petertseng/gzip-as-user" 

---

pkg/store/consul/healthmanager.go

This reverts commit d0c7826a82520be8c927ee4a625443cd1451d589.
To achieve this effect, we'll instead turn on debug logging via preparer
config.

Revert "raise log level of health manager from Debug to Info"

---

pkg/preparer/setup.go

Hooks are just a pod, but they're installed in a separate code path when
the preparer boots up since the hook manifest if found within
p2-preparer's config. An unintended consequence of this change is that
old installs of hook launchables were not getting pruned. This commit
prunes old hook launchables after installing the new ones.

prune old hook launchable installs

---

pkg/labels/consul_aggregator.go
pkg/labels/consul_aggregator_test.go
pkg/labels/consul_applicator_test.go

The ConsulAggregator is designed to allow performing "watches" on a
label selector for a certain label type, while only actually performing
one watch routine per process. The aggregator maintains a linked list of
"watchers" which represent a particular selector, and every time the
overall label watch returns new values, the list is iterated and each
watcher's selector is applied to the full dataset, with the results
being sent to the watcher's channel.
In practice, if the dataset is large (e.g. ~1.6Mb) and the number of
watchers is high (e.g. ~1700), it can take a noticeable amount of CPU
time in order to process a watch value. This is bad because a mutex
guarding access to the aggregator's linked list is held while these
computations are being performed.
This mutex must also be acquired …

Parallelize sending updates to each watcher in consul aggregator.

---

bin/p2-exec/main.go

An alternative to https://github.com/square/prodeng/pull/54 and #810.
The two above would require a coordinated rollout, while this change to
p2-exec can be rolled out without coordination.

p2-exec: Setpgid to create new process group

---

pkg/gzip/gzip.go

This preserves the behaviour present before #739 / #821, for apps that
run_as root, since the custom gzip code would explicitly chown those
files to root.
So this can be considered as a fix to a regression caused by #821.
As code comment states: this helps apps that run_as root ensure that
their files are in fact owned by root rather than some unknown user
dictated by the build system.

gzip: Always extract with --no-same-owner

---

pkg/grpc/labelstore/client/client.go
pkg/grpc/podstore/client/client.go

A common pattern in P2 code is to call a function that returns a channel
of results, the values on which are the result of calls to Consul.
Errors connecting to consul are typically swallowed and retried.
When providing a gRPC implementation of this same interface, a similar
approach was taken where an error making the gRPC call results in
continuous retrying forever. In the event of a broken TCP connection,
these RPC calls would fail immediately, resulting in a lot of log
messages.
This commit disables the "fail fast" call option when retrying an rpc,
which means that the call will wait until a TCP connection is ready
before returning. This will reduce the amount of logging when the TCP
connection breaks, but doesn't simplify the code because there are still
certain errors that could …

turn off fail fast call option for gRPC retries

---

pkg/hooks/audit_logger_sqlite.go

This will support us in case the hook_schema_versions table is faulty.

DEFENSIVE MIGRATION SYNTAX

---

pkg/store/consul/flags/kingpin.go

As is traditional, our token file ends with a newline. Reading from the
file preserves the newline, but this causes an error when trying to send
a request:
net/http: invalid header field value "CENSORED\n" for key X-Consul-Token
Thus we should trim the spaces.

flags: strip spaces out of token read from token file

---

bin/p2-rctl/main.go
pkg/grpc/auditlogstore/audit_log_store.go
pkg/grpc/auditlogstore/audit_log_store_test.go
pkg/labels/consul_applicator.go
pkg/labels/fake_applicator.go
pkg/store/consul/auditlogstore/consul_store.go
pkg/store/consul/auditlogstore/consul_store_test.go
pkg/store/consul/auditlogstore/integration_test.go
pkg/store/consul/rcstore/consul_store.go
pkg/store/consul/rcstore/fake_store.go
pkg/store/consul/rollstore/consul_store.go
pkg/store/consul/rollstore/consul_store_test.go
pkg/store/consul/rollstore/integration_test.go
pkg/store/consul/transaction/transaction.go
pkg/store/consul/transaction/transaction_test.go

This commit changes function signatures for consul store operations to
take a context.Context instead of a *transaction.Tx. This means we're
providing a more standard interface and additionally callers can specify
deadlines or cancellation signals for applying a transaction.

Make all functions take a context.Context instead of transaction.Tx

---

pkg/grpc/auditlogstore/audit_log_store.go
pkg/grpc/auditlogstore/client/client.go
pkg/store/consul/rcstore/consul_store_test.go

This will allow clients to operate using the "raw" audit log types
rather than the primitive types that are ncessarily used by generated
protobuf code.

Add client library wrapper for audit log store grpc operations.

---

pkg/store/consul/kv.go
pkg/store/consul/kv_test.go

This allows for transactionally transforming a number of pod manifests
in some way. A first use case is to replace a signature.

store/consul: Add MutatePod

---

bin/p2-rctl/main.go

Using an HTTP applicator is allowed by most of our CLIs and generally
desirable over using direct consul access where possible, however
p2-rctl also instantiates a rolling update store which has a hard
dependency on direct consul access for writing labels in order to
perform transactions.
This commit simply instantiates a direct-consul-access applicator for
use in the roll store while still using the labeler according to common
flags for other purposes.

Fix p2-rctl when configured to use http applicator.

---

bin/p2-pcctl/main.go
pkg/pc/control/control.go
pkg/pc/control/control_test.go

pc/control: Only accept/use session in Create
The constructors were all taking a session but only using them in
Create. Might as well only take in Create.
History: The session argument used to be used in Mutate as well, but
that was removed in #524. After this point, Create is the only user of a
session, so it can be the only function that takes one.
---
p2-pcctl: Only create session when creating a PC
Thus, if someone does not have permission to create a session but can
still read from the PC store, they will still be able to use all
non-Create operations, which seems desirable.

pc/control: Only accept/use session in Create; p2-pcctl: Only create session when creating a PC

---

pkg/audit/ru.go
pkg/audit/ru_test.go
pkg/roll/farm.go
pkg/roll/integration_test.go

Previously audit log records that were created to mark the cancellation
or successful completion of a rolling update did not contain information
to identify the pod cluster the RU belonged to. This commit adds that
information because audit log systems will likely want to be able to
look up this information based on pod cluster.

Add pod cluster identifying info to RUCompletionEventDetails

---

pkg/labels/consul_applicator.go
pkg/labels/integration_test.go

The intention was that that call wouldn't actually remove labels, it
would just add an api.KVTxnOp to the passed transaction within the
passed context to do so, and the actual deletion wouldn't occur until
the transaction was committed. However the code had the exact same
behavior as the synchronous deletion in RemoveAllLabels().
This commit reimplements the function as intended and adds a regression
test.

Fix RemoveAllLabelsTxn in consul applicator.

---

pkg/grpc/podstore/podstore.go

There was a race where a goroutine might panic sending on a closed
channel. This commit gives responsibility of closing the channel
to the goroutine writing to it.

Fix a panic case in WatchPodStatus() grpc handler.

---

pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/hoist/test_helper.go
pkg/pods/pod.go

This change is intended to cut down on error noise in p2-preparer. The
hoist artifact spec historically required all "entry points" for an
artifact to be located at bin/launch whether it's a directory of entry
points or a file. At a later point in time the pod manifest spec was
extended to allow specifying alternate entry points, at which point it
was considered an error if an entry point is missing.
However it is not uncommon for an artifact to have no entry points, for
instance when the intention is just to deploy some scripts to a server
and not run any processes. These cases now generate errors which pollute
preparer logs and exception systems.
This commit tries to take the best of both worlds by considering a
missing entry point to be an error only if it was explicitly enumerated
in …

Do not consider a missing implicit entry point an error.

---

Godeps/Godeps.json
Rakefile
pkg/preparer/setup.go

- change godep back to v77
- add temp fix for Rakefile (Go version < 1.8.1 and Command Line Tools 8.3)
- prevent chmod'ing in preparer setup when not root (no permissions - fail when testing on local machines)

Fixes for installation and running tests

---

bin/p2-rctl/main.go
pkg/roll/farm.go
pkg/roll/integration_test.go
pkg/roll/run_update.go
pkg/roll/update_test.go

Previously the RU farm would always zero out the old RC's replica count
and then delete it if the "LeaveOld" flag was not set. This can lead to
bad situations if a math error is encountered when creating an RU
because we might delete an RC that was managing pods and then those pods
become orphaned.
This commit causes the RU farm to only delete the old RC if its replica
count is zero. Otherwise it will send an alert so a human user can
correct the situation.

roll farm: only delete old RC if replica count is zero. otherwise page.

---

.travis.yml
Rakefile

We're working around https://github.com/square/p2/issues/832
We're refining the method used in https://github.com/square/p2/pull/831
It becomes harder to maintain the list of packages that will get
excluded from the race detector (and thus must be rerun without it), so
we will just run all tests without and all tests with.
Since we desire not to slow down the tests by running them twice, we
hope to mitigate the slowdown by running the two in parallel.

travis: Run once with the race detector and once without

---

bin/p2-rctl/main.go
pkg/store/consul/rcstore/consul_store.go

This new command will be useful in emergency or otherwise tricky situations that would heretofore require manual interaction with the consul DB.

rctl has learned manifest mutate

---

bin/grpc/clients/label-store-client/main.go
integration/single-node-slug-deploy/check.go
pkg/grpc/labelstore/client/client.go

The grpc label client is intended to implement some functions from the
labels.Applicator interface which benefit from centralizing queries on a
server. Recently WatchMatches() had its function signature change to
make the aggregation rate of queries configurable, however the grpc
client did not have a similar change made to its function signature.
This commit brings them into lockstep.

Fix function signature of WatchMatches() on grpc label client.

---

pkg/store/consul/consulutil/watch.go
pkg/store/consul/statusstore/podstatus/consul_store_test.go
pkg/store/consul/statusstore/podstatus/integration_test.go

Some metrics histograms are updated to track things like consul latency.
However in the WatchKeys() function, the queryMeta return value from the
consul List() operation was being used to update histograms before
checking that the response came back without an error. If there is an
error then queryMeta will be nil which will cause a server panic.

Fix a nil pointer exception in consulutil.WatchKeys()

---

pkg/preparer/orchestrate.go

After the preparer launches a oneoff pod, it writes a status record for
that pod indicating that it has launched. It is intended to retry
forever until the record is written successfully.
However a typo in the for loop condition did the opposite, it will retry
forever if it succeeds and only exit when an error is hit (even if there
was no successful write).

Fix an inverted for loop exit condition.

---

pkg/labels/http_applicator.go

If this case fails, it's likely that the labels returned follow a different
schema. The error case in which the response is totally invalid JSON already
returns an error.

Remove "expected" warn

---

pkg/labels/applicator.go

This will allow labeling config values with information that can be used
to identify the pod cluster that the config value corresponds to.

Add label tree constant for config

---

pkg/store/consul/configstore/store.go
pkg/store/consul/configstore/store_test.go

Golang's JSON marshal doesn't support arbitrary types as keys, probably because
JSON itself does not support this.

change config's type to string -> interface{}

---

pkg/store/consul/configstore/store.go
pkg/store/consul/configstore/store_test.go

The type of map used by pkg/manifest is map[interface{}]interface{} so it
behooves us to match that. The map[string]interface{} change was to support JSON
marshalling of config stanzas, which seems less important now than it once did.

Effectively revert a change made in #890

---

integration/single-node-slug-deploy/check.go
integration/travis.sh

This addresses travis errors where consul won't start with the following
error:
2017-07-20_18:14:35.22743 ==> Error starting agent: Failed to get
advertise address: Multiple private IPs found. Please configure one.

Pick a private IP for consul to bind to.

---

bin/p2-preparer/main.go

The preparer captures TERM signals to buy time to get the work it's
doing into a logical stopping place before exiting. It does this by
creating a bunch of quit channels, one for each function the preparer
performs and then signalling exit via the quit channels.
Prior to this commit it would send a value on the quit channels to
signal that an exit should happen, however if a preparer function shared
the quit channel across goroutines this would cause only one of them to
quit.
This commit instead closes the channel which will cause any watcher on
the quit channel to fire and exit.

Close quit channels on shutdown rather than send a value

---

pkg/store/consul/consulutil/watch.go

As P2 was scaling, it was thought that we could spread load across
consul servers better by using stale queries within "watch" loops since
a stale query can be answered by whichever consul node receives the
request rather than requiring another round trip to the consul leader
node.
This was thought to be completely safe since using an index along with
the query guarantees that successive queries can't "time travel"
backwards.
However, some scalability wins in other areas (mainly the query-batching
capabilities within the labels HTTP server) have made this an
unnecessary complexity of the system. Additionally, after restarting
consul nodes we have occasionally seen a stale query return a 404
response which can have bad consequences if the proper failsafes are not
in place. We believe that …

Use consistent rather than stale queries in watches.

---

README.md

`rake integration` will not work if Vagrant and VirtualBox are not installed. This adds instructions to install those to the README.

Update README with Vagrant installation instructions.

---

integration/single-node-slug-deploy/check.go
integration/travis.sh
pkg/hooks/hooks.go
pkg/preparer/orchestrate.go
pkg/store/consul/consulutil/watch.go

Up until this commit, hook failures woul not stop a pod from being
installed and having reality updated. Hook failures were logged but
otherwise ignored.
This commit changes this by treating a hook failure as a critical
failure which will cause the entire pod installation routine to be
retried (the same way a download failure is treated, for example).
This means that P2 operators will have confidence that if reality is
updated for a pod, that all of its hooks must have succeeded. Previously
this was not the case and the philosophy was that P2 applications should
check for conditions they expect hooks to put in place within their
health checks, which will prevent a rolling update from rendering all
pod instances within a pod cluster to be nonfunctional

Treat hook failures like normal failures.

---

bin/p2-dsctl/main.go
pkg/ds/daemon_set.go
pkg/ds/daemon_set_test.go
pkg/ds/farm.go
pkg/ds/farm_test.go

This will be useful in order to pass a context containing a partial
consul transaction that ensures that the daemon set farm still holds the
lock that it's supposed to be when it performs consul operations. This
will be useful to protect against multiple daemon set farms writing the
same daemon set status entry with conflicting information.

Use contexts for cancellation in daemon set farm.

---

pkg/preparer/orchestrate.go

Up until recently, p2-preparer would never halt the installation process
of a pod if a hook failure was experienced. This meant that pods could
be installed/updated if a hook was broken but also created situations
where it would appear that everything worked but in fact something that
a hook was supposed to do would be incomplete.
A recent commit made p2-preparer treat hook failures as critical ones,
which would cause the entire pod update to restart.
This created an unintended issue when a hook failure affects the
p2-preparer updating itself, in which the preparer might stop itself but
then fail to start itself again if an error is encountered during the
"before_launch" hook cycle or earlier.
This commit makes it so that hook failures are still ignored when run on
the p2-preparer pod, …

Exempt p2-preparer itself from hook failure handling.

---

pkg/pods/factory.go
pkg/pods/pod_test.go

NewFactory was taking a fetcher and then not using it, instead using a
defaultFetcher.
This is inappropriate for situations where we must configure specific
settings on the fetcher in order to be able to download artifacts (for
example, CA file)
`newPodWithHome` must accept a fetcher and then use it, and `NewUUIDPod`
and `NewLegacyPod` must pass the fetcher given from `NewFactory`.
Recall that the certificates we issue require that we be able to
configure specific CAs.
This was partially done in #826, but it was not made to apply to Pods,
which internally contain Fetchers as well.

pods: Pass fetcher from factory to pods

---

pkg/replication/replication.go

Prior to this commit the message "Replication is over" would appear no
matter how the replication ended. Now there are specific messages for
replication cancellation, successful completion, and halts due to losing
the consul session holding the replication's lock.

Make replication termination logging more descriptive

---

bin/p2-install-hook/main.go
pkg/pods/factory.go
pkg/preparer/setup.go
pkg/preparer/setup_test.go

pods: Take/use fetcher in NewHookFactory
As in #915, it seems necessary to configure a fetcher, otherwise I predict (but have no hard evidence to support) that we will be unable to install any hooks.
I'm unsure of the necessity of this one but it's here if we need it.

pods: Take/use fetcher in NewHookFactory

---

bin/p2-ds-farm/main.go
pkg/ds/farm.go
pkg/ds/farm_test.go

This will allow farms to be configured such that they only handle
certain pod IDs. This is useful for creating staging environments where
only a certain pod ID is serviced and can be excluded from the
production environments.

daemon set farm: add configurable pod blacklist and whitelist

---

pkg/ds/farm.go

This fixes a bug where a daemon set whose pod ID is in the farms'
blacklist will have its lock held forever since the lock is never
released.
It makes more sense to check the blacklist before even acquiring the
lock to avoid the issue.

ds farm: check if daemon set should be worked on before locking

---

pkg/ds/farm_test.go
pkg/store/consul/consultest/fake_session.go
pkg/store/consul/session.go
pkg/store/consul/session_test.go

This commit reworks the way LockTxn() works on a consul session. Prior
to this commit you had to pass in 3 different context.Context values
each with an inner consul transaction, and LockTxn() would load each of
them up with the respective consul operations that enable locking,
unlocking, and checking that the lock is held within consul
transactions.
In practice this is very cumbersome since callers acquiring locks must
prepare all of the contexts ahead of time, and preserve the contexts and
their cancellations everywhere where they are needed.
This commit changes the LockTxn() function to only take a single context
intended for locking the key and returns an interface which can be used
to load up contexts with unlocking and check-locking operations
respectively.
This will means callers …

Improve transactional locking API

---

pkg/store/consul/statusstore/rcstatus/status.go
pkg/store/consul/statusstore/rcstatus/store.go
pkg/store/consul/statusstore/rcstatus/store_test.go
pkg/store/consul/statusstore/store.go

As part of better host idling, RC's will keep track of their status to know when they are performing a node transfer. To do this they will need to Get the status to see if a node transfer is in progress, Set the status when they are performing a node transfer, and Delete the status when they are finished.  Those three behaviors are implemented and tested.

Add RC Status store

---

pkg/store/consul/statusstore/rcstatus/status.go
pkg/store/consul/statusstore/rcstatus/store.go
pkg/store/consul/statusstore/rcstatus/store_test.go

Add transactional check and set CASTxn(). Also update
names based on go code review guide.
Cleaned up rc status store text, added CASTxn to use in the replication controller, and updated rc status struct name based on https://github.com/golang/go/wiki/CodeReviewComments#package-names. This commit also includes the NodeTransfer as a pointer change.

Refactor rc status store

---

pkg/hoist/hoist_launchable.go
pkg/launch/launchable.go
pkg/opencontainer/containers.go
pkg/pods/pod.go
pkg/pods/pod_test.go

An internal request for exposing the restart_timeout has prompted this change. The alternative is having the customer parse the manifest (bad) & copy the knowledge of the default timeout (very bad!)

Env var for restart timeout

---

bin/p2-rctl-server/main.go
pkg/alerting/alerter.go
pkg/alerting/alertingtest/alerter.go
pkg/alerting/nop_alerter.go
pkg/alerting/pagerduty.go
pkg/alerting/pagerduty_test.go
pkg/ds/farm.go
pkg/rc/farm.go
pkg/rc/farm_test.go
pkg/rc/replication_controller.go
pkg/roll/farm.go
pkg/roll/integration_test.go
pkg/roll/run_update.go

The alerting package provides an interface for sending alerts when
something goes wrong within P2, and has an implementation of that
interface that uses the pagerduty API.
This commit adds the ability to configure the pagerduty alerter with
high and low urgency service keys to use with pagerduty's API as well as
the ability to specify whether an alert is high or low urgency. The
correct key will be used depending on the urgency of the alert.

pkg/alerting: support different pagerduty urgency levels in alerts

---

pkg/ds/daemon_set.go
pkg/ds/farm.go

This commit removes some noisy log messages that aren't very useful at
the farm level, such as the ones that list all of the daemon sets.
It also trades general messages (e.g. "daemon set updated") for specific
ones (e.g. "daemon set disabled").

Enhance daemon set logging

---

pkg/rc/replication_controller.go
pkg/store/consul/kv.go

This will be used by the replication controller to schedule a new node
during a node transfer. By using a check and set with a modify index of
0, it is guaranteed that the intent/ key does not yet exist. If the CAS
fails, another RC has already taken over the node and we can rollback
the node transfer.

Add LockIfKeyNotExistsTxn() function

---

pkg/preparer/setup.go

We expect that responses might take up to 5 minutes (the wait time we
specify for consul operations) to return, but any longer than that is an
indication that the request isn't going to return. This commit sets a
timeout of 6 minutes on http requests to consul so that they will be
retried.

Add a http timeout of 6 minutes to consul clients

---

bin/p2-pcctl/main.go
pkg/pc/control/control.go
pkg/pc/control/control_test.go
pkg/pc/fields/fields.go
pkg/pc/fields/fields_test.go
pkg/rc/fields/fields.go
pkg/store/consul/pcstore/consul_store.go
pkg/store/consul/pcstore/consul_store_test.go
pkg/store/consul/pcstore/pcstoretest/fake_pcstore.go

This strategy field will be a long-term place to store the desired
configuration for the RC strategy for RCs created within this pod
cluster (since RCs are ephemeral).

Add allocation strategy field to pod clusters

---

pkg/replication/replication.go

This bug resulted in log messages that said "could not read reality for
this node" when in fact the read was successful but there was just a
missing key. It's clear the code meant to separate these two situations
but the missing key block was unreachable.

Fix an error checking bug in replication package

---

pkg/store/consul/rcstore/consul_store.go

This will make it easier for scripts to make multiple changes in a
single update or to mutate new fields for which a mutator function
hasn't been written yet

Export MutateRC in the rcstore

---

pkg/rc/replication_controller.go

This change prevents the chance of a logical error in which
AllocateNodes() would return the same node that DeallocateNodes() just
removed. While that wouldn't happen if we set the cologroup of the deallocated
node correctly, it is nice to ensure it can't happen even in the event of
cologroup oversight.

Call allocate before deallocate in node transfer

---

pkg/rc/auditing_transaction.go
pkg/rc/auditing_transaction_test.go
pkg/rc/farm.go
pkg/rc/replication_controller.go
pkg/rc/replication_controller_test.go
pkg/store/consul/rcstore/consul_store.go

Prior to this commit, the main replication controller loop would start
by calling the Watch() function on the RC store, passing it a pointer to
an RC struct and also a mutex. Whenever the watch goroutine detected a
change to the RC, it would lock the mutex and then mutate the RC
pointer.
This meant that whenever the main RC loop tried to access a field on the
RC pointer, it would need to grab a mutex while it did so. This is
untenable as new references to the field are added all the time and it's
hard to remember to hold the mutex, creating data races.
Furthermore, it's hard to reason about what happens if the RC is mutated
in the middle of a meetDesires() invocation.
To address this, this PR changes the way Watch() on the rc store works
so that it returns a channel of RC structs (not …

pkg/rc: stop using an RC pointer passed to a watch function

---

pkg/hoist/hoist_launchable.go
pkg/p2exec/p2_exec.go

p2-exec has a --clearenv argument. We ought to be using it when invoking bin scripts!

clear the env for bin scripts

---

.travis.yml
bin/p2-exec/main_linux.go
bin/p2-rctl/main.go
pkg/roll/run_update.go
pkg/roll/update_test.go
pkg/store/consul/consulutil/ops.go
pkg/store/consul/consulutil/watch.go

An UpdateFactory was required to return an Update interface which has a
'Run() bool' function, however the code that calls it was not looking at
the return value. This commit removes the return value from the
interface and fixes the places that return it to not do so

Update signature of Run() roll.Update interface

---

pkg/rc/auditing_transaction.go
pkg/rc/replication_controller.go
pkg/rc/replication_controller_test.go
pkg/roll/update_test.go

Background: the RC handler routine is expected to kick off a "node
transfer" if the scheduler tells it that one of its "current" nodes are
not eligible to run the pod anymore. This is complex to get right
because there might be 2 RCs that share the same resources (nodes) from
the scheduler when a rolling update is in progress.
What should happen when a node is ineligible is that the RC will request
a new node from the scheduler to replace it, from then on we want one of
the RCs to schedule the pod on that node, but we don't really care which
one during a deploy situation. As a result, an RC scheduling a node
transfer will attempt to schedule the new node using a lock and then
later clean up that lock when the node transfer is complete.
However, if the lock operation fails because the node …

node transfers: only write label for new node if it was locked

---

bin/p2-preparer/main.go
pkg/pods/factory.go
pkg/preparer/setup.go
pkg/preparer/setup_test.go
pkg/preparer/testdata/test_current_manifest.yaml
pkg/store/consul/podstore/consul_store.go
pkg/types/types.go

- if a node is missing the reality tree on startup, apply rebuild reality logic to prevent orphaned pods
- an orphaned pod will have its data still in /data/apps but not exist in intent
- also fix a bug in pkg/pods/factory.go PodFromPodHomeWithReqFile where it wasn't parsing the uuid of pods correctly

Add rebuild reality logic to p2-preparer setup

---

bin/p2-rm/main.go
bin/p2-rm/rm.go
pkg/hoist/hoist_launchable_test.go

Typically p2-rm assumes that a pod either does not have a
replication_contoller_id label (and thus is safe to unschedule) or it
does have one, and decrementing the replica count on the managing RC is
the proper course of action.
However in practice a pod will occasionally end up in a state where it
has the replication_controller_id label but no RC with that ID exists,
which means that we should use the manual method of removing the pod.
This commit adds a --remove-orphan flag which will make p2-rm do an
extra check that the replication controller ID returns actually exists
Additionally this commit makes p2-rm remove the labels for any pods it
deletes

p2-rm: allow flag to check for missing RC

---

pkg/ds/daemon_set.go
pkg/ds/daemon_set_test.go
pkg/replication/replication.go

The daemon set runner responds to some changes to daemon sets such as
the manifest, but it did not until now respond to changes to the
timeout. This is something that someone might want to take effect before
the daemon set server is restarted.

daemon set farm: update replication timeout

---

pkg/manifest/manifest.go

This change adds a manifest builder function that creates a stanza for pod level resource limits. 
This will be used for manifest upgrades so that all deployed manifests will have pod level resource limits.

Add function to add pod resource limits to manifest

---

pkg/manifest/manifest.go

I previously merged this PR [](https://github.com/square/p2/pull/994) that added a setter to the manifest builder to set pod level cgroup resource limits. This PR adds a getter to the manifest to return that created stanza. It will be a nice function to have to interact with those resource limits.

Add ResourceLimitsStanza getter to manifest

---

pkg/roll/run_update.go
pkg/roll/update_test.go

This change returns early from the RU Run() function if the call to
NewRUCompletionEventDetails() returns an error. Previously the function
did not return, and nil details could be passed to a subsequent function
call.
Returning early is chosen behavior now because that is what was
done in error cases from the subsequent auditlogStore.Create() function
call anyway and because when Run() returns false, the RU is not deleted
giving another RU farm the chance to pick it up and perform the cleanup.

Return early if RU fails to create audit details

---

pkg/hooks/hooks.go
pkg/hooks/hooks_test.go
pkg/hooks/types.go

Most preparer log messages have the associated "pod" key using the
logrus logger, however inadvertently when executing hooks a created
sublogger was not being passed through, which caused some fields to be
dropped. For example, when a hook fails there's no "pod=" key to tell
the user which pod the hook failed for.
This commit plumbs the sublogger through to every place in the hook
runner that needs it

Add missing log fields to hook messages

---

pkg/rc/replication_controller.go

We have observed some RCs "get away" from their rolling updates and sit around with 0 replicas. This sort of check is only interesting when we're looking at apps that are managing nodes. This change should greatly reduce the false positive rate for this alert.

we are not interested in RCs that don't have any replicas

---

pkg/rc/replication_controller.go

We aren't _that_ interested in missing artifacts that we need alerts every hour

Drastically increase the artifact checker cycle period.

---

bin/p2-cgroup-info/main.go
bin/p2-exec/main.go
integration/common-provision.sh
integration/single-node-slug-deploy/check.go
integration/travis.sh
pkg/cgroups/cgroups.go
pkg/cgroups/cgroups_test.go
pkg/cgroups/config.go
pkg/cgroups/subsystem.go
pkg/hoist/hoist_launchable.go
pkg/manifest/manifest.go
pkg/manifest/manifest_test.go
pkg/p2exec/p2_exec.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/preparer/orchestrate.go
pkg/preparer/setup_test.go

This is maybe as nice as the commit history will get.
There's a lot here, so let me go over the strategy.
Cgroups for pods are optional, for now. If the manifest has a `resource_limits` key at the top level, the preparer shall parse the file and write the limits to $pod/config/resource_limits.yaml. This file will be referenced in the p2-exec command line so that the cgroup is created (possibly redundantly) when the app starts (or restarts). 
The cgroup directory structure is nested underneath a new top-level group (called "p2") and then under the hostname. This fixes a long-standing bug where we couldn't properly cgroup things that ran inside of containers. Launchable cgroups are underneath pod cgroups where you'd expect them to be.

Pod Cgroups

---

pkg/hoist/hoist_launchable.go

This doesn't have a behavioural effect (that depends on the resource file which
depends on the top level manifest key resource_limits:) but it does allow us to
roll out a version of this code that understands the argument without calling
it, providing us with n-1 version backward compat

gate the pod arg to p2-exec on the param

---

bin/p2-restart/main.go
bin/p2-shutdown/main.go
bin/p2-stop/main.go
pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/launch/launchable.go
pkg/opencontainer/containers.go
pkg/pods/pod.go
pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go

When set, this option instructs P2 to skip the "sv stop" portion of the
normal manifest update process. This is useful for processes that are
designed to gracefully reload without service interruption. However, P2
does not arrange for a signal to be sent to the process, pods that need
this functionality should implement their own signal handling in
bin/post-activate.
There are certain circumstances in which the no_halt_on_update setting
will be ignored, for instance if an operator is shutting down all pods
on the host or if a pod is being uninstalled (manifest deleted from the
intent tree).

Add no_halt_on_update launchable option to launchable stanza spec

---

bin/p2-ds-farm/main.go
bin/p2-inspect/main.go
bin/p2-rctl-server/main.go
bin/p2-rctl/main.go
bin/p2-replicate/main.go
bin/p2-watch/main.go
pkg/ds/daemon_set.go
pkg/ds/farm.go
pkg/health/checker/checker.go
pkg/health/checker/checker_test.go
pkg/health/checker/test/fake_checker.go
pkg/health/client/client.go
pkg/health/store/store.go
pkg/health/store/store_test.go
pkg/manifest/manifest.go
pkg/rc/farm.go
pkg/rc/replication_controller.go
pkg/replication/common_setup_test.go
pkg/replication/health_aggregator.go
pkg/replication/replication.go
pkg/replication/replicator.go
pkg/roll/farm.go
pkg/roll/run_update.go
pkg/roll/update_test.go

Changes required for rolling updates to use the health service client for health checks while still using the consul health tree in parallel. These changes will test reliability of health service client.
- Created a separate healthChecker type in checker.go called ShadowTrafficHealthChecker that will utilize both the health service client and old consul tree checking code
- Old health checker was renamed from ConsulHealthChecker to HealthChecker so that in the future when the health service client is deemed reliable we can rename ShadowTrafficHealthChecker to HealthChecker
- WatchService and Service functions defined for new HealthChecker to be used by rolling updates
- WatchService uses both health service client and consul health tree
- Service uses either consul or health service …

use new health service with rolling updates

---

bin/p2-bootstrap/bootstrap.go
bin/p2-launch/main.go
bin/p2-shutdown/main.go
pkg/hooks/hook_env.go
pkg/hooks/hooks.go
pkg/hooks/types.go
pkg/manifest/manifest.go
pkg/pods/factory.go
pkg/pods/pod.go
pkg/pods/pod_test.go
pkg/pods/read_only_policy.go
pkg/preparer/orchestrate_test.go
pkg/preparer/setup.go

To be honest, I'm a little out of my depth here.
That said, I'm attempting to have p2-preparer be configurable to set default readonly policy for deployed pods. Pods will be able to override this policy by setting the `ReadOnly` flag in their manifest (as they currently do today). To allow for a graceful changeover, the preparer manifest will supported a flag for whether or not readonly deploys should be the default, a list of PodIDs that should be deployed readonly by default, and a list of PodIDs that should not be deployed readonly by default.
We'll start out by having ReadOnly default to false, and manually deploying the preparer with a whitelist of readonly-clean pods. This list will grow over time. In the event of an error on our part, pod owners can explicitly deploy with ReadOnly …

Read only in pod manifest

---

bin/p2-launch/main.go

This will support bootstrapping a service in a way that it will not
actually be able to execute until a particular file is on disk.
p2-preparer already supports writing runit services this way, but it
couldn't be done by p2-launch.

Add --require-file flag to p2-launch

---

bin/p2-exec/main.go

Right now, a cgroup limit of 0 for either CPUs or memory in the manifest
(or the omission of the cgroup limit) translates to an actual cgroup
limit of -1, i.e. unrestricted. To facilitate an automated adoption of
reosurce_limits based on existing launchable limits, we should allow
manifest limits of 0 (at least for now). Otherwise we will have to
impose new limits that did not previously exist and that will slow down
the migration to pod resource_limits.

Allow resource_limits of 0 in pod manifests

---

pkg/store/consul/pcstore/consul_store.go

There was logic in the MutatePC function where it would write labels for
the pod after doing a mutation, and if the label write fails it would
delete the pod cluster. It doesn't make sense to be touching labels at
all here, and it certainly doesn't make sense to delete the pod cluster
unless that's what the caller wanted. Looks like this was a bad
copy/paste from the Create() function, where it does make sense to
delete a pod cluster for which a label write failed.

Remove out-of-place code snippet in the pod cluster store.

---

bin/p2-rctl-server/main.go
bin/p2-rctl/main.go
pkg/health/checker/checker.go
pkg/health/checker/test/fake_checker.go
pkg/roll/run_update.go
pkg/roll/update_test.go

Fix up logic in WatchService of checker.go
Add refresh logic in run_update.go for the case of node transfer or other reason causing the current pods in an RU to change.

Health service into rolling update fixes

---

pkg/cgroups/cgroups.go

It is possible to have a pod with cpu restrictions and an
unrestricted launchable. When that happens, the pod has a cgroup
cpu.cfs_period_us of 1,000,000. Then, for the launchable's unrestricted cpu limit, we
switch to the default period of 100,000. Having a period of 100,000
nested within a cgroup that has a period of 1,000,000 is invalid.
This change switches to always using a period of 1,000,000 for
consistency and to prevent failed writes. Those failed writes would block pod
installation.

Always use cpu.cfs_period_us of 1,000,000

---

integration/common-provision.sh

Previously starting docker under systemd was failing, the error seems to
go away if we use the docker installation instructions from
https://docs.docker.com/install/linux/docker-ce/centos/#install-docker-ce-1
which also gets us a more recent version

Fix docker installation in vagrant integration test

---

pkg/rc/replication_controller.go

When the watchHealth go routine times out waiting for a new node to come
up healthy, the routine ends. In this case, we want the node transfer to
be retried with the same old and new nodes, and that is possible because
they have been persisted in the Consul replication controller status
tree. However, because the local rc.nodeTransfer struct would have a
non-nil quit channel, the replication controller did not retry because
it thought the watch health go routine was still operating in the
background. By setting the rc.nodeTransfer struct to the empty struct,
the node transfer will be correctly retried.

Retry node transfers on health check timeout

---

pkg/manifest/manifest.go

The node requirements key is based on Kubernetes's podSpec nodeSelector.
It is map of key value pairs that can be added to a replication
controller's node selector. For a pod to then be scheduled on a node,
the node needs to have each of the key-value pairs as labels.

Add node_requirements key to pod manifests

---

pkg/manifest/manifest.go
pkg/manifest/manifest_test.go

This is useful for programmatically building a manifest that has node
requirements

Add function to manifest builder to set node requirements

---

pkg/docker/docker.go
vendor/github.com/docker/docker/client/container_exec.go
vendor/github.com/docker/docker/client/interface.go

- ContainerExecAttach takes wrong type but it doesn't matter for us since we pass an empty struct

Revert vendor change in docker pkg container_exec.go

---

pkg/pods/pod.go

The `currentManifest.GetLaunchableStanzas()` just below will cause a nil dereference panic if the current manifest is nil. There is nothing else this function needs to do if the manifest is nil, so we can return here.

Fix nil manifest dereference bug

---

bin/p2-rctl/main.go
pkg/roll/farm.go
pkg/roll/integration_test.go
pkg/roll/run_update.go
pkg/roll/update_test.go

Because rolling updates and node transfers can no longer occur at the
same time, marking a node as ineligible during a rolling update can
cause a "deadlock" where the roll cannot move forward because an
ineligible does not count as healthy.

Ignore ineligible nodes during in rolling updates

---

bin/p2-bootstrap/bootstrap.go
bin/p2-preparer/main.go
integration/single-node-slug-deploy/check.go
pkg/constants/constants.go
pkg/pods/factory.go
pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go
pkg/preparer/setup.go
pkg/util/PodError.go
pkg/util/readfile.go
pkg/watch/health.go

Introducing pod whitelist file, which contains a list of while list pods. Particular uses case is after an host is re imaged, there may still be some sticky apps' manifest remain in node's intent store,  previously, once p2-prepare boosts, it starts to watch intent store immediately and download and install the app binaries, even without other fundamentals of the host are ready. 
So here we introduces pod whitelist file, when p2-prepare is initialized, and before start normally working, we force p2-prepare to keep checking pod whitelist file, install all the pods in the whitelist, keep checking for update, until the pod whiltelist file is empty, which services as a signal that p2-prepare can proceed to play with it's full functionality.

Modify p2-preparer to read pod whitelist from pod_whitelist_file

---

pkg/rc/replication_controller.go

If no health result is returned for a pod, the preparer on the node may
be down. That should be treated as a sufficient condition for a node
transfer if that node is also ineligible.

Treat no health result as unhealthy in transfer

---

pkg/rc/replication_controller.go
pkg/rc/replication_controller_test.go

Specifically, when the old RC has only ineligible nodes and replicas that it does not desire.

Allow some node transfers during rolling updates

---

pkg/preparer/setup.go

We can also use this PR to discuss setting other fields like `MaxIdleConns` that people see as helpful to reduce the number of connections the preparer keeps open to Consul.

Set IdleConnTimeout on http transport

---

pkg/preparer/setup.go
pkg/util/net/socket/http_client.go
pkg/util/net/socket/http_client_test.go

~~This is an initial, MVP for deploying an Envoy sidecar launchable
alongside p2-preparer to handle HTTP traffic between preparers and
Consul. It works by using a custom Transport that sends requests to
the Envoy unix socket along with other request metadata Envoy needs to
route the request to Consul.~~
This is largely shamelessly stolen from @mpuncel's prior work in configuring an Envoy-compatibile Go HTTP client internally at Square.
This commit adds new http client sends requests to a unix socket
specified by an environment variable in the preparer's pod manifest.
When the environment variable is set in the manifest, outbound requests
to Consul will be sent to the socket.

Support unix socket http client in p2-preparer

---

bin/p2-rctl-server/main.go
pkg/rc/farm.go
pkg/rc/replication_controller.go
pkg/rc/replication_controller_test.go

Systems that have a delay between changes to P2 pod cluster membership
and changes to the membership of their service discovery and load
balancing systems should not let those two diverge further through node
transfers.
The RC Farm now accepts the ServiceDiscoveryChecker interface, and RC's
will call its IsSyncedToCluster() function to ensure that the service
discovery system is synced enough to support a transfer.

Check service discovery synced before node swap

---

pkg/hooks/hooks_test.go

- Fix issue when timeout is 1 ms. This results in the file being cleaned up before it is fsync() to the filesystem resulting in the temp script missing and thus can't be executed.
- Ensure hook script executes longer than 1 sec.
- Use `/usr/bin/env sh` for the hook script. Using `env` is the standard why of calling environments and platform agnostic. Switching to `sh` because we don't need a full bash environment.

increase TestHookRunWithTimeout from 1 msec to 1 sec

---

bin/p2-log-bridge/main.go

Environments that use systemd-journald may be affected by a bug in which
logbridge write()s will fail with EPIPE if systemd-journald restarts. To
avoid this, we can update the STDOUT and STDERR file descriptors to
point at /dev/null.
[Context](https://bugs.freedesktop.org/show_bug.cgi?id=84923)

Discard STDOUT and STDERR in p2-logbridge

---

pkg/preparer/setup.go
pkg/util/net/socket/http_client.go
pkg/util/net/socket/http_client_test.go

When the preparer is communicating with Consul through a unix socket,
there is now an additional manifest config that will allow the preparer
to add any additional headers to all requests to Consul.

Add extra Consul headers config

---

Godeps/Godeps.json
vendor/golang.org/x/net/http2/client_conn_pool.go
vendor/golang.org/x/net/http2/configure_transport.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/go111.go
vendor/golang.org/x/net/http2/go17.go
vendor/golang.org/x/net/http2/headermap.go
vendor/golang.org/x/net/http2/hpack/huffman.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/not_go111.go
vendor/golang.org/x/net/http2/not_go17.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/net/http2/write.go
vendor/golang.org/x/net/internal/socks/socks.go
vendor/golang.org/x/net/trace/trace.go

Just keeping it up-to-date.
Relevant changelog:
* 4dfa2610: all: fix typos in comments
* 26e67e76: internal/socks: fix socket descriptor leakage in Dialer.Dial
* 922f4815: http2: reduce init-time work & allocations
* f4c29de7: trace: better error message for double init
* 22bb95c5: http2/hpack: lazily build huffman table on first use
* 32f9bdbd: http2/hpack: reduce memory for huffman decoding table
* 49c15d80: http2: revert CL 107295 (don't sniff Content-type in Server when nosniff)
* c4299a1a: http2/h2c: add h2c implementation (unencrypted HTTP/2)
* 3673e40b: http2/h2demo: flush headers earlier in demo /ECHO handler
* a680a1ef: http2: fix typo in comment
* 179114c9: http2: reject large SETTINGS frames or those with duplicates
* d0887baf: http2: fix bug in earlier CL 123615
* a1d68217: …

Update golang.org/x/net to 49bb7cea

---

bin/p2-run-hooks/main.go
pkg/hooks/hooks.go
pkg/hooks/hooks_test.go
pkg/manifest/manifest_test.go
pkg/preparer/orchestrate.go
pkg/preparer/orchestrate_test.go
pkg/preparer/setup.go
pkg/preparer/setup_test.go
pkg/preparer/test_preparer_config.yaml

Adding a feature to add a required list of p2-preparer hooks. The executed hook will be checked against `hooks_required: []` if it fails to see if the `err` should be returned. If the p2-preparer hook is not listed it should retain the previous functionality to log a warning and continue.
Simple preparer config:
```
id: hooks
launchables:
req-hook:
opt-hook:
config:
hooks_required:
- req-hook
```
This will result in failures to `req-hook` returning an err and `opt-hook` logging but continuing.

add feature to mark platform hooks as required in preparer config

---

Rakefile
integration/hello/hello.go
pkg/rc/replication_controller.go
pkg/rc/replication_controller_test.go
pkg/store/consul/consultest/fake_session.go
pkg/store/consul/session.go

There were 2 session leaks found:
* When locking to do a node transfer, we were not cleaning up the session if we failed to get the lock.
* After returning to `attemptNodeTransfer()` from `canNodeTransfer()`, we were only unlocking the lock once complete and doing nothing with the underlying session object.
Also had to make a couple changes to improve tests:
* Increase the timeout for go tests as we were consistently exceeding the 20s timeout with the `pkg/rc/*.go` tests.
* Fix up the hello integration in the repo so `go test` would succeed.
* Modify test setup order in TestNodeTransferNoopIfLockHeld to remove surprise errors from the logs when that test does fail.

Ensure session cleanup is done consistently

---

pkg/manifest/manifest.go
pkg/manifest/manifest_test.go
pkg/pods/pod.go

Sometime disable scripts run for 2h blocking p2-preparer to proceed. We should add termination grace period and kill the disabling process when too long time consumed. Default set to 1 hour considering not affect current process, and added `termination_grace_period` field in pod manifest to enable customization.

added customizable termination grace period for disable scritps

---

pkg/docker/docker.go
pkg/hoist/hoist_launchable.go
pkg/hoist/hoist_launchable_test.go
pkg/hoist/successful_scripts_test_hoist_launchable/installs/testLaunchable_abc123/bin/disable
pkg/launch/launchable.go
pkg/opencontainer/containers.go
pkg/pods/pod.go

For hosit launchable, terminate the disable script when grace period is met;
for docker launchable, we do not need to terminate the disable process, just unblock the p2-preparer waiting for the disable script, and proceed killing the container.
Also not only for disable script, this commit enables p2 to have termination grace period on any step.

modified the way to terminate disable script with commandContext

---

pkg/cgroups/cgroups.go

When processes hit their CPU quota, they are throttled
for the remainder of the time in the configured period.
Pausing pods or launchables for up to 1 second is too
high and could lead to throughput drops.

cgroup: decrease cpu period duration

---

pkg/pods/pod.go
pkg/pods/pod_test.go

We need a case to just install pods but not start it.
I have split pod.Launch into 2 more functions.
1. PostActivate runs post activate for all launchables.
2. StartLaunchables starts up all launchables.
3. Made BuildRunitServices public

Spliting Launch function

---

bin/p2-setup-runtime/main.go

p2-setup-runtime sets up runtime environment for an already installed pod.
It runs hooks, post-activate scripts, builds run scripts for a pod.
It will not start services of a pod.
It is useful for setting up a pod environment on a node where p2-preparer
is not running

p2-setup-runtime

---

pkg/auth/artifact_verifier.go

Before, we failed to see the error message that triggers the fallback to the build verifier. By saving all the error strings, we are able to better inspect why we end up in the fallback.

Get better logging from composite verifier process

---

pkg/ds/farm.go

I've noticed that multiple P2-master nodes emit these metrics, but only one is correct.
I think calling Unregister will stop them from being reported.

Unregister metrics when stopping monitoring them
