pkg/reality/reality.go
This is pretty much just copy the intent store, change its name, remove
the watch, add a lookup. I lose some DRY points for doing ths.
=> Add the reality store

bin/p2-preparer/main.go, pkg/preparer/orchestrate.go, pkg/preparer/orchestrate_test.go
I was working pretty fast on this one so there might be stupid mistakes. I'll rebase #53 onto this once it's merged.
=> Refactor shared arguments of preparer into struct

pkg/intent/intent.go, pkg/intent/intent_test.go, pkg/pods/manifest_parser.go, pkg/pods/manifest_parser_test.go, pkg/preparer/orchestrate.go
Mostly need some feedback on the placement of this code right now. Tests are broken on this branch.
e: to be exact, the last commit is the one that bothers me; I think the other three are harmless but they can be tweaked too if needed.
=> Add service registration to preparer

pkg/preparer/orchestrate.go, pkg/preparer/orchestrate_test.go
We should probably wait to merge this until after #59 (I'll rebase it back onto master once that's done), but let me know what you think of the code so far.
This is also an opportunity to investigate writing more complex tests for pkg/preparer (eg testing handlePods or WatchForPodManifestsForNode).
=> Fix tests in pkg/preparer

.travis.yml, bin/p2-preparer/main.go, pkg/hooks/listener.go, pkg/hooks/listener_test.go, pkg/intent/intent.go, pkg/pods/pod.go, pkg/preparer/orchestrate.go
Will add some additional checks in the integration test to show that hooks are getting executed.
=> use hook listener in preparer

bin/p2-schedule/main.go, bin/p2-watch/main.go
Some new features for p2-watch and p2-schedule. I'm still thinking about how to test `pkg/kp` so I probably won't have a PR for that today.
=> p2-watch/schedule features

.travis.yml, pkg/pods/fake_chpst, pkg/pods/hoist_launchable.go, pkg/pods/hoist_launchable_test.go, pkg/pods/pod.go, pkg/pods/pod_test.go, pkg/pods/test_helper.go
also fixes a minor bug regarding our tarball code
=> Implement post-activate

.travis.yml, pkg/config/config.go, pkg/config/config_test.go, pkg/pods/hoist_launchable.go
Two more features commonly used to read free-form YAML config.
=> ReadMap, panic-proof

pkg/pods/hoist_launchable.go
Fixes the bug with folders being owned by root: they only contained other folders, so after mkdirAll, the chown would only affect the bottom folder in the chain.
=> Create folders one by one during tar unpack

pkg/kp/kv.go
Ping the consul agent that a Store is connected to. If the store is reachable and has a leader, it'll respond 200 to the request, and the special header `X-Consul-Knownleader` will be true, therefore this method will return nil. If the agent has no leader, the agent will respond 500 with the special header set to false. This method will propagate the 500 error back to the caller. Finally, if the agent is outright unreachable, there'll probably be a tcp dial error that also gets returned to the caller.
=> Add kp Ping

bin/p2-preparer/main.go, bin/p2-run-hooks/main.go, integration/single-node-slug-deploy/check.go, pkg/hooks/hooks.go, pkg/pods/pod.go
This a debugging utility to make running hooks for apps a little
easier. This also fixes the integration test, which changed when
users were given ownership of their pod directory.
=> Add p2-run-hooks

bin/p2-bootstrap/bootstrap.go, bin/p2-inspect/main.go, bin/p2-preparer/main.go, bin/p2-replicate/main.go, bin/p2-schedule/main.go, bin/p2-watch/main.go, pkg/preparer/orchestrate.go, pkg/preparer/orchestrate_test.go
=> ACL token support for all p2 consul-interacting binaries

integration/single-node-slug-deploy/check.go
Fix is needed after bootstrap stopped running consul as root (aa071cd)
=> Create integration test consul user

pkg/hoist/hoist_launchable.go
Inside a tarball, the target of a hard link is encoded as a path relative to the tarball root, rather than from the hard link itself. The original code I wrote to handle hardlinks assumed they were encoded like symlinks when in fact that was wrong, so this is the fix.
=> Fix tar hardlinks

bin/p2-inspect/README.md, pkg/pods/pod_manifest.go, pkg/pods/pod_manifest_test.go
=> Use SHA256 in pod manifests

pkg/digest/verification.go, pkg/digest/verification_test.go, pkg/pods/pod.go, pkg/pods/pod_manifest.go, pkg/preparer/orchestrate.go, pkg/preparer/orchestrate_test.go
WIP. Code to check signatures should be complete, code to actually perform signature checking is on the way.
=> Artifact signature verification

pkg/preparer/orchestrate.go, pkg/preparer/orchestrate_test.go, pkg/preparer/setup.go
=> Forbidden Pod IDs

integration/common-provision.sh, pkg/hoist/hoist_executable.go, pkg/hoist/hoist_launchable.go, pkg/preparer/listener.go
The special-case behavior of hooks vs other pods definitely deserves a closer look in the future.
=> Fix cgroups hooks

bin/p2-bin2pod/main.go, bin/p2-bootstrap/bootstrap.go, bin/p2-launch/main.go, bin/p2-replicate/main.go, bin/p2-run-hooks/main.go, bin/p2-schedule/main.go, integration/single-node-slug-deploy/check.go, pkg/allocation/allocation.go, pkg/hooks/hook_env.go, pkg/hooks/hooks.go, pkg/hooks/hooks_test.go, pkg/kp/kv.go, pkg/kp/service.go, pkg/pods/manifest.go, pkg/pods/manifest_test.go, pkg/pods/pod.go, pkg/pods/pod_test.go, pkg/preparer/listener.go, pkg/preparer/listener_test.go, pkg/preparer/orchestrate.go, pkg/preparer/orchestrate_test.go, pkg/replication/replication.go, pkg/replication/replication_test.go
Programmatic rename of PodManifest -> Manifest plus various other abbreviations that follow therefrom
=> Rename PodManifest -> Manifest

bin/p2-bootstrap/bootstrap.go
First step in making consul scheduleable. Confirmed that preparer does not attempt to restart consul immediately after bootstrapping.
=> Schedule consul in intent and reality during bootstrap

bin/p2-inspect/main.go, bin/p2-replicate/main.go, bin/p2-schedule/main.go, pkg/kp/kv.go, pkg/util/net/client.go
Like so:
`p2-schedule --header X-Foo=bar --header X-Qux=baz manifest.yaml`
=> Custom HTTP headers

bin/p2-inspect/main.go
Allows inspect to gracefully react to multiple health checks on a single service, choosing the poorest of them.
=> Refactor inspect to use pkg/health

bin/p2-exec/main.go, bin/p2-exec/main_darwin.go, bin/p2-exec/main_linux.go
plus various refactors. Thanks @syamp. cc @anthonybishopric @eam
=> Handle return values in p2-exec before checking errno

pkg/auth/policy.go
When a manifest is signed with a key that isn't in the keyring, P2 will now
display an error message that includes the key ID:
unknown signer: 0123456780ABCDEF
This should make it easier to understand why a manifest was rejected.
=> Show PGP key ID when signer is not found

.gitignore, Rakefile
Standard rake task to create builds to use in tagged versions of P2
=> Add package utility

pkg/auth/policy_test.go
=> use chtimes to backdate files, eliminate sleep

bin/p2-inspect/main.go
=> fix error casing

bin/p2-inspect/main.go, pkg/inspect/inspect.go
Some of the structs in p2-inspect may be useful elsewhere (ie p2-show-health),
so I have moved them into their own package.
Also adds JSONManifest to the pods package. JSONManifest is a JSON encodable
version of the Manifest struct in the pods package.
=> Creates inspect pkg

bin/p2-preparer/main.go, integration/single-node-slug-deploy/check.go, pkg/kp/kv_test.go, pkg/preparer/setup.go, pkg/preparer/setup_test.go, pkg/watch/health.go
* Fixes a failing unit test
* Uses preparer's TLS configuration consistently
* Misc changes to prettify the code
=> Misc fixes

bin/p2-bootstrap/bootstrap.go, pkg/kp/kv.go, pkg/kp/service.go, pkg/preparer/orchestrate.go, pkg/preparer/orchestrate_test.go
This reverts commit e734d764d1eb14062547397a0cdda6414a6cc1e3, reversing
changes made to 18ca0e3d8c0d49220fedc040d77d3ac318681931.
=> Revert "Merge pull request #201 from robertabbott/abbott/removeCatalog"

pkg/kp/service.go, pkg/preparer/orchestrate.go, pkg/preparer/setup.go
Some bug fixes and improvements I've been working on related to Consul's health checking
* Fix faulty Consul health check
* Create Consul health checks with explicit hostname
* Add feature flag for Consul health checks
=> Misc Consul health checks

integration/single-node-slug-deploy/check.go, pkg/watch/health.go
=> I had http and https backwards

pkg/kp/fixtures_test.go, pkg/kp/kv.go, pkg/kp/kv_test.go, pkg/kp/lock.go, pkg/preparer/listener.go, pkg/util/stream/publisher.go, pkg/util/stream/publisher_test.go, pkg/watch/health.go
This PR contains some preliminary commits that need to be in place before I introduce the main PR for session-based health checks. Those changes aren't quite ready for a PR, but I think the changes here are of high quality and not likely to change, so I'd like y'all to start looking these over.
I recommend reviewing one commit at a time, rather than looking at the entire "files changed" view for the PR.
=> Preliminary commits before session-based health checks

pkg/watch/health.go
In this commit, even services that don't declare any health check will still
have a health check written to the KV with "passing" status. This happens to be
the same behavior that the catalog-based health checks have.
=> Write KV health status for all services

pkg/labels/applicator.go, pkg/labels/consul_applicator.go, pkg/labels/consul_applicator_test.go
=> Use labels.Selector interface instead of implementation

pkg/health/checker/checker.go, pkg/health/checker/checker_test.go, pkg/health/health.go, pkg/health/health_order.go, pkg/health/health_state.go, pkg/health/health_test.go
Simplifies the interface for some of the defintions and comparison methods in
"pkg/health".
=> Cleanup health package

bin/p2-watch/main.go, pkg/kp/kv.go, pkg/preparer/listener.go, pkg/preparer/listener_test.go, pkg/preparer/orchestrate.go, pkg/preparer/orchestrate_test.go, pkg/replication/replication.go
=> WatchPods should return []kp.ManifestResult

bin/p2-launch/main.go, bin/p2-replicate/main.go, pkg/pods/manifest.go
You may think it's not so bad that it's duplicated in two places but I'm
about to add a third, so I think it helps to do this.
=> De-duplicate ManifestFromURI code

pkg/digest/verification.go
Tested in universe and verified that it works. It would be nice if we could fix the bug that dragged in the absolute symlinks, but ffi makefiles still don't make sense to me, and that gem creeps into almost every ruby app in the company, bringing an absolutely-symlinked header file with it. So I think this is an acceptable patch-up.
=> Do not stat absolute symlinks during verification

pkg/pods/manifest.go
Refactors the various constructors for a `Manifest` so that they duplicate no
code. Adds documentation for each.
=> Unify and document Manifest constructors

pkg/hooks/hook_env.go, pkg/hooks/hooks.go, pkg/hooks/hooks_test.go, pkg/kp/kv.go, pkg/preparer/orchestrate.go, pkg/preparer/orchestrate_test.go, pkg/preparer/result_set.go, pkg/preparer/result_set_test.go
please review code for sanity, not ready for merge. I haven't tested it or implemented intent safety checks.
=> Implement pod DELETE

pkg/labels/consul_applicator.go
This deals with <id> containing "/" in it. Without this commit, an <id>
of, for example, "a/b" (resulting in consul key "labels/pod/a/b") will
cause the type to be inferred as "a" instead of "pod" and ID to be
inferred as "b" instead of "a/b"
=> ConsulApplicator: split by "/" instead of using path

pkg/hooks/hook_env.go
I should have added this to the global hooks PR, but I only just realized it would be useful.
=> Add hooks ExitUnlessEvent

pkg/watch/health.go
see commit message. Tests pass on this branch. The semantics of the change "feel" straightforward so my instincts say it should work. I'll see if I can give it a test run.
=> Remove reality polling from health monitor

pkg/hoist/hoist_launchable.go
Pretty self-explanatory. The error return from os/exec is rarely useful (`exit status 1`) so the `Error()` function returns the output instead.
=> Capture output from enable/disable

pkg/hooks/hooks.go, pkg/preparer/orchestrate.go, pkg/preparer/orchestrate_test.go
Some actions must be taken after we have turned off the old version of the app
=> add before_launch hook type

pkg/preparer/setup.go
we should have probably done this a long time ago
=> Configure preparer log level

pkg/labels/fake_applicator.go, pkg/labels/fake_applicator_test.go
This will be useful for testing the new replication controllers.
=> Add fake applicator and test

pkg/rc/replication_controller.go, pkg/rc/replication_controller_test.go
We wouldn't want to make our clients have to deal with references to
unexported types, since then all they can do is something like `myrc :=
rc.New(...)`. They can't refer to the type to use it as a function
argument or return type, for instance. Too restrictive. So we add an
interface.
This also adds documentation, and now we need to export an Id as well
=> replication_controller: Add interface

bin/p2-bin2pod/main.go, bin/p2-restart/main.go, pkg/kp/kv.go, pkg/pods/pod.go
This is a useful on-host binary for gracefully stopping and starting a service. Also a few commits for small issues I noticed.
=> Add p2-restart command

pkg/hoist/hoist_launchable.go
Bug: when a network transfer failed, the tar extractor would (highly likely)
fail due to an unexpected EOF and report its error correctly. However, the
partially-extracted artifact wasn't cleaned up correctly, and the _next_
attempt to install would use the bad install directory.
This commit fixes the bug by downloading to a temporary file first, then
extracting files. Cleanup is easy: just delete the file.
=> Correctly fail installation on artifact transfer errors

bin/p2-watch/main.go, pkg/preparer/listener.go, pkg/replication/replication.go
communicate an empty []ManifestResult
=> Fix bugs in callers of WatchPods()

bin/p2-rcfarm/main.go, pkg/rc/farm.go
=> Add RC manager

bin/p2-rcfarm/main.go, bin/p2-rctl/main.go, pkg/kp/rcstore/consul_store.go, pkg/kp/rcstore/fake_store.go, pkg/kp/rcstore/store.go
Supports create, delete, set replicas, list and get. I decided not to support disable because there's no enable method right now. Might add shortly. Other suggestions for what to add are also welcome.
e: before I forget, I should also adjust the rcstore api to support force-deletion (ignoring open replica count) and implement that here as well
=> Add p2-rctl

pkg/hoist/hoist_launchable.go
This enables custom automation that makes use of various scripts not
directly related to the deploy lifecycle.
=> Export InvokeBinScript() on the hoist.Launchable struct.

pkg/kp/rcstore/consul_store.go, pkg/kp/rcstore/fake_store.go, pkg/kp/rcstore/store.go, pkg/rc/farm.go, pkg/rc/replication_controller.go, pkg/rc/replication_controller_test.go
intermediate PR for things that RU depends on, but are not themselves part of RU.
=> Minor RC refactors part 3

pkg/pods/manifest.go
Adds a check that validates the input data of a manifest when it is being read.
Invalid manifests will be rejected.
Currently, the validity checks only verify that required fields are provided.
=> Check validity of input manifests

bin/p2-exec/main_linux.go
If the user we want to run p2-exec as is the current user, there is no
need to set uid or gid. This allows scripts to run p2-exec as their own
user without having to do checks of their own to leave out the -u
argument
=> Only change user in p2-exec when necessary.

pkg/hoist/hoist_launchable.go, pkg/opencontainer/containers.go, pkg/opencontainer/default.go, pkg/opencontainer/specs.go, pkg/p2exec/p2_exec.go, pkg/p2exec/p2_exec_test.go, pkg/pods/pod.go, pkg/util/param/param.go
This is definitely experimental code, but it kind of works!
I'd like to merge this to master at this preliminary stage so that I can commit the work I've made so far. Not sure when I'll get back to it.  By default, the new type is disabled and fairly self-contained, so it shouldn't pose any risk.
=> Preliminary OpenContainer support

bin/p2-sum/main.go
Installs a standard usage message and fixes a couple of missing newlines.
=> Fix error formatting for p2-sum

pkg/kp/rcstore/consul_store.go, pkg/labels/applicator.go, pkg/labels/consul_applicator.go, pkg/labels/consul_applicator_test.go, pkg/labels/fake_applicator.go, pkg/labels/http_applicator.go
=> Remove all labels when deleting RC

bin/p2-rctl/main.go, pkg/roll/farm.go, pkg/roll/fields/update.go, pkg/roll/run_update.go
Necessary to attach a pod field to the logs produced by RUs.
=> Add pod field to roll farm logs

pkg/kp/healthmanager.go, pkg/util/limit/bucket.go, pkg/util/limit/bucket_test.go
A couple patches to reduce the Consul write rate for troublesome services.
=> Limit output

bin/p2-schedule/main.go, bin/p2-watch/main.go, integration/single-node-slug-deploy/check.go, pkg/hooks/hooks.go, pkg/preparer/listener.go, pkg/preparer/listener_test.go
=> Remove typed hooks

bin/p2-inspect/main.go
Adds a new flag "--format list" to the options for p2-inspect that lets it
print its data in a new format. The old format has been named "tree" because it
resembles a nested tree where app instances are grouped first by app then
labeled by hostname:
```
{
"mypod": {
"myhost": {
"keys": "values", ...
},
...
},
...
}
```
The new "list" output format prints a flatter JSON structure that has a list of
app instances, one object for each host:
```
[
{
"node": "myhost",
"pod": "mypod",
"keys": values", ...
},
...
]
```
This output format allows for easier processing by filters, e.g., using the
"jq" command.
=> Add "list" format for p2-inspect

pkg/labels/fake_applicator.go
=> Fake applicator races

pkg/kp/rollstore/store.go
really wish 404 was an error case rather than a nil kvp
=> Do not panic on nonexistent update

pkg/roll/run_update.go
When a rolling update executes, it acquires locks on the RCs involved in the
change, and those locks should be released when the update is finished.
However, the existing code never verifies that the locks are actually released.
Transient errors could allow the updater to leak a locked RC, preventing
anything from modifying that RC until the updater's Consul session is
restarted.
This change reduces the capacity for deadlocks among rolling updates by
retrying all unlock operations. As long as Consul is accessible, the unlocks
should eventually succeed. During prolonged Consul outages, the updater's
session could expire, also dropping the locks and allowing the rolling update
to restart.
=> Always release RC locks in a rolling update

pkg/util/stream/publisher.go
A bug in the stream package was found while running unit tests for an unrelated
change. The test failure was:
--- FAIL: TestUnsubscribeIndependence (0.00s)
publisher_test.go:254: sub2 got unexpected sequence: [foo]
A subscriber should have received the current value of the StringValuePublisher
as of the time of the Subscribe() call; in this execution, that initial value
was skipped.
Root cause: when the subscriber unsubscribes, it closes its "canceled" channel
to signal the publisher that it shouldn't wait when sending to the subscriber.
Then, in the presence of an active reader, it is possible for sendFirst() to
non-deterministically choose to abort its send while the main publisher read()
loop non-deterministically chooses to send a subsequent value.
This commit fixes the ordering …
=> Fix ordering violation in stream package

pkg/replication/replication_test.go
In TestStopsIfLockDestroyed, the fake health checker would report
healthy for the first node in the replication, but then assert that the
second node is not deployed. This is incorrect behavior and creates a
race where replication might move onto the second node before the test
is performed. Reporting unhealthy for all nodes properly creates the
behavior where replication will only be applied to a single node
=> Fix flake in replication test by reporting unhealthy for all nodes

pkg/roll/run_update.go
This is a bug introduced by https://github.com/square/p2/pull/402, in
which the library that handles consul locking was changed. Previously
you could call session.Unlock(key) on a key that you may or may not
hold, and it would not panic the process.
Now, however, session.Lock(key) returns a kp.Unlocker object that is
used to unlock a key. The code fixed in this PR had assumed that it was
okay to call unlock on a key that wasn't held, but this resulted in a
panic if the unlocker was nil
=> Only attempt to unlock an RC if the lock is held

pkg/rc/replication_controller.go
This solves a use case in which a deployer wants to know which node will
be scheduled first by a new RC.
=> When an RC schedules nodes, use a sorted list

pkg/roll/run_update.go
This removes the old block for healthy nodes that was effectively a
reimplementation of slice divisors. This check is unnecessary because
`rollAlgorithm` already ensures safe operation. Removing it has the
benefit of allowing deploys to proceed with more parallelism - if one
node is slow to become healthy but there is health headroom, the deploy
can proceed to other nodes in the meantime. This was not possible with
the block in place.
The other benefit is that in the case of a deploy where minimum health
requested is zero, the deploy terminates as soon as all nodes have
converged, without waiting for nodes to become healthy. This is useful
in the case where we are knowingly deploying a bad sha, for which nodes
will never become healthy.
=> roll: Finish update when new healthy > minimum requested

pkg/roll/run_update.go
We ran into a situation today where a deploy was in a state where one
canary node was desired, but two nodes had appeared on the new side.
Examination of the logs produced the following
{
"msg": "Adding 1 new nodes",
"new": {
"Desired": 0,
"Current": 0,
"Real": 0,
"Healthy": 0
},
"next": 1,
"old": {
"Desired": 19,
"Current": 19,
"Real": 19,
"Healthy": 18
},
"pod": "censored",
},
This is expected.
{
"msg": "Adding 1 new nodes",
"new": {
"Desired": 1,
"Current": 1,
"Real": 1,
"Healthy": 0
},
"next": 1,
"old": {
"Desired": 18,
"Current": 19,
"Real": 19,
"Healthy": 18
},
"pod": "censored",
}
This was unexpected, but (assuming minimum healthy was < 18)
understandable because in `rollAlgorithm`, `headroom` would be > 1 and
`remaining` would be 1, so we would schedule one node.
This is a direct …
=> roll: If update is done but just waiting on healthy, don't schedule

pkg/rc/farm.go, pkg/roll/farm.go
A farm will spawn many goroutines that are activated by changes in
consul data, and it is common to run multiple farms on a server (e.g.
rc farm and roll farm). Since consul data is not transactional, there
have been repeated issues of null pointer dereferences in farm
goroutines crashing the entire process.
While pointers are now pessimistically dereferenced to avoid these
issues, it is probably good to have an additional level of protection to
stop bad data in consul from grinding the farms to a halt if a nil
pointer dereference is missed.
=> Recover from panics in a goroutine spawned by a farm

pkg/kp/rcstore/consul_store.go
* Fix a few places where errors were not wrapped in util.Errof (and
therefore do not show line numbers in logs)
* Fix a few places where errors from the underlying consul API are not
wrapped in a ConsulError (and thus might leak consul tokens)
=> Fix up error handling in rcstore's ConsulStore

pkg/preparer/setup.go
This comment is a lie! Eradicate it.
=> Correct comment to match reality

pkg/roll/update_test.go
While making #442 we discovered that #408 kind of made the fuzz test do
odd things: It wasn't necessarily removing the number of nodes it said
it would be removing.
We'd like to keep the current fuzz test, as it seems to be useful in the
mutable world (where the old RC gets disabled thus doesn't necessarily
remove any nodes).
Now we'd like to add a new test that shows how things will progress in a
world of immutable deployments, where the old RC will indeed remove
exactly the number of nodes specified.
=> roll: Add fuzz test for strict removals

pkg/kp/pcstore/pcstoretest/fake_pcstore.go
=> names the pcstoretest package appropriately

pkg/labels/consul_aggregator.go, pkg/labels/consul_aggregator_test.go, pkg/labels/consul_applicator.go
Adds three metrics per aggregator; the number of cached `labels.Labeled`, the number of outstanding watchers, and the number of watchers that missed a selector update.
=> Add metrics to the Consul label aggregator

.travis.yml, Rakefile, pkg/config/config.go, pkg/consultest/consultest.go, pkg/hoist/hoist_launchable.go, pkg/hoist/test_helper.go, pkg/kp/consulutil/session.go, pkg/kp/consulutil/session_controller.go, pkg/kp/pcstore/consul_store.go, pkg/labels/consul_aggregator.go, pkg/labels/consul_applicator.go, pkg/opencontainer/containers.go, pkg/pods/manifest.go, pkg/preparer/setup.go, pkg/rc/farm.go, pkg/rc/replication_controller.go, pkg/replication/replication.go, pkg/runit/servicebuilder.go, pkg/runit/test_helper.go, pkg/uri/uri.go, pkg/watch/health.go
This list populated by `errcheck -ignoretests github.com/square/p2/pkg/... | grep -v defer`
I ignored defer cases because they are tricky to get right. I also wanted to get this merged ASAP as I caught a few pretty scary ignored errors!
Some discussion on err handling in defer can be found here: https://github.com/kisielk/errcheck/issues/55, https://github.com/kisielk/errcheck/issues/77
=> errcheck the repo

pkg/types/types.go
There's no cycle to work around in my use case, but I like the idea of having one package of types. Thoughts?
=> Add a NodeName type

pkg/kp/statusstore/statusstoretest/fake_status_store.go
I knew i would regret not implementing these
=> implement the two remaining functions on fake statusstore

pkg/kp/pcstore/consul_store.go, pkg/kp/pcstore/consul_store_test.go
Previously func handlePCUpdate() operated under the assumption that the
first update would always have a nil value for the previous state of a
pod cluster. However, now that the ConcreteSyncer interface includes
GetInitialClusters(), this is a faulty assumption.
This would result in a pod cluster pod membership watch not being
started.
=> fix bug with initial conditions in pcstore.WatchAndSync

pkg/health/checker/checker.go, pkg/health/store/store.go
=> These selects should be long-running

pkg/kp/pcstore/consul_store.go
Previously we were only measuring the time it takes for the
SyncCluster() call to execute from start to finish. It's more
interesting to track the time between a change being noticed and
SyncCluster() being finished.
In other words, we want to include the time it takes for handlePCUpdates
to actually trigger the SyncCluster() call as well.
=> Fix measurement of cluster sync time

pkg/kp/pcstore/consul_store.go, pkg/kp/pcstore/consul_store_test.go
To implement pod cluster update.
=> Hzeng.pc update

pkg/hooks/hooks.go, pkg/hooks/hooks_test.go
- Create `Hook` struct; use it for executing hooks
- Add `RunWithTimeout` method to `Hook`
- Test it with some temp files
- Default timeout to 5s
It feels like the hook package is ready for a refactor to take into account the Hook type (which feels really natural for this package), but I feel that's out of scope of this PR.
Please double-check my style and adherence to convention.  I'm still picking up the idioms of Go.
=> Time out hook execution after 60s

Godeps/Godeps.json, Godeps/_workspace/src/golang.org/x/net/LICENSE, Godeps/_workspace/src/golang.org/x/net/PATENTS, Godeps/_workspace/src/golang.org/x/net/context/context.go, Godeps/_workspace/src/golang.org/x/net/context/go17.go, Godeps/_workspace/src/golang.org/x/net/context/pre_go17.go, Godeps/_workspace/src/golang.org/x/time/LICENSE, Godeps/_workspace/src/golang.org/x/time/PATENTS, Godeps/_workspace/src/golang.org/x/time/rate/rate.go, bin/p2-log-bridge/main.go, pkg/logbridge/logbridge.go, pkg/logbridge/logbridge_test.go
I'm not sure what numbers to fill in here yet. Will need to deploy & observe the results of my previous PR to determine the constants.
=> Log bridge rate limits

bin/p2-pcctl/main.go, pkg/pc/control/control.go, pkg/pc/control/control_test.go
Basic functionality about create, show & delete is here. Will add update in a following change
=> Introduce p2-pcctl

bin/p2-pcctl/main.go, pkg/pc/control/control.go, pkg/pc/control/control_test.go
I'm scared to add any more complexity than this to PC mutation - I'd
prefer to merge the JSON by hand using a good tool for the job (ie. a
scripting language).
=> Basic overwriting update command for PodClusters

bin/p2-pcctl/main.go
Previously, p2-pcctl was using kv.NewUnmanagedSession which
(confusingly) takes a string argument for a session ID, however it
expects the session ID to correspond with a valid session in consul.
This commit uses kv.NewSession() instead which actually creates a
session in consul.
=> fix p2-pcctl session creation

bin/p2-dsctl/main.go
CLI commands for create, get, list, enable, disable, delete, and update.
=> Hzeng.dsctl

pkg/preparer/orchestrate.go
In cases where a pod's launch or shutdown time is very long, we
do not want this wait time to block other ongoing deploys. While
pods own their update channel, it is possible for the primary
intent watching channel to get stuck trying to notify a pod routine
of a new manifest.
Another fix is required to time out long or stuck installations during
a self-update or graceful shutdown scenario, present at orchestrate.go:133
but achieving this safely is less clear.
=> Do not block main update loop if individual pod is stuck.

bin/p2-ds-farm/main.go, pkg/ds/daemon_set.go, pkg/ds/daemon_set_test.go, pkg/ds/farm.go, pkg/ds/farm_test.go
This will allow you to run ./bin/p2-ds-farm to call `replication` to schedule nodes
=> Enable replication in ds farm

pkg/replication/health_aggregator.go, pkg/replication/replication.go
The replication.AggregateHealth() call would return a podHealth object whose
health values would never change from those gathered in an initial query. As
used, the replication package would update a node and then only observe its
health from before the update, not after the update. This could allow a bad
update to be ~~pusehd~~ pushed to all nodes. The p2-replicate command and daemon set
updates are affected.
This bug happened because intended mutable shared state (a podHealth object)
was being passed by copy. The fix implemented in this commit is to pass by
reference.
There is also a potential for deadlock if the update thread encountered any
Consul error. It would send that error on a channel that was never read. This
mitigates the error by draining the channel.
=> replication: Fix health aggregation

pkg/ds/farm.go, pkg/ds/farm_test.go, pkg/kp/dsstore/dsstoretest/fake_dsstore.go, pkg/kp/kptest/fake_store.go
This is to add in tests in the daemon set farm for to test for multiple farms running
=> Hzeng.ds replication

pkg/ds/daemon_set.go, pkg/replication/replicator.go
Will also return an error when initialization fails
=> Modify daemon sets to skip the preparer check

bin/p2-ds-farm/main.go, bin/p2-dsctl/main.go, bin/p2-replicate/main.go, pkg/ds/daemon_set.go, pkg/ds/daemon_set_test.go, pkg/ds/farm_test.go, pkg/ds/fields/fields.go, pkg/kp/dsstore/consul_store.go, pkg/kp/dsstore/consul_store_test.go, pkg/kp/dsstore/dsstoretest/fake_dsstore.go, pkg/kp/dsstore/store.go, pkg/replication/common_setup_test.go, pkg/replication/replication.go, pkg/replication/replicator.go
Adds a timeout to daemon sets when replicating.
Also modified p2-ds-farm to gracefully shutdown and remove its locks.
=> Hzeng.replicator timeout

bin/p2-dsctl/main.go
The createAZ and updateAZ has been removed and replaced with createSelector and updateSelector.
=> Remove the old dsctl's availability zone with a raw selector

pkg/ds/daemon_set.go
Previously, when the daemon set encounters an error during replication,
it would sleep for 5 minutes and then retry. It was not able to take in
updates or deletes until after the retry happens.
Now with this change it can take in updates in between this time period
and if the updates produce no error on replication it would cancel the
retry.
=> Allow the daemon set to act on changes when an error occurs

bin/p2-dsctl/main.go
The argument was used in both the "create" and "update" commands when
creating a daemon set, allowing the daemon set's pod id to differ from
the pod ID in its manifest, which would be an invalid configuration.
This commit does the following:
1) when creating a daemon set, infer the daemon set's PodID field from
the pod ID of the manifest. This removes the possibility of errors where
the two wouldn't match, and also reduces the number of flags necessary
to create a daemon set.
2) When updating a daemon set's manifest, reject the update if the
manifest's ID does not match the pod ID of the daemon set. This reduces
the possibility of error of setting the manifest for a different pod
onto a daemon set.
=> Remove --pod arguments from p2-dsctl

pkg/hooks/hook_env.go
Add the HookEnv.Node() method to allow hooks to easily get the name of
the node they're running on. This is similar to what is done in cdb4a9c.
Also refactors the PodFromDisk() method to use Node() (et al.) to avoid
repeating error messages.
=> hooks: Add convenience function to get node name in hooks

pkg/util/stream/publisher.go, pkg/util/stream/publisher_test.go
Return a buffered output channel when subscribing to a
StringValuePublisher. A slow reader will skip some updates instead of
blocking all other subscribers.
This eliminates a potential problem when sharing one publisher among
many different users, not all of which are equally responsive. In
practice, the subscribers used in P2 are already written in such a way
that they don't care if they receive all updates.
Buffering output also makes the publisher code easier, since it doesn't
have to deal with sends potentially blocking.
=> stream: Buffer subscriber output

pkg/ds/farm.go
quickfix to stop these from paging
=> session expiry is not an alert

pkg/replication/replicator.go
This is to reduce consul load.
=> Limit the number of updates to at most 50.

pkg/roll/farm.go
If a rolling update exists in consul and is missing either its new or
old RC, the rolling update cannot be handled because the enable/disable
step at the beginning of the roll handler will fail.
This commit validates that both RCs in an RU exist before attempting to
run it. If one of the RCs is missing, the RU is deleted.
=> Make the roll farm robust to RUs with missing RCs.

pkg/replication/replication.go
A msising case in an if statement when checking whether an error
occurred during a single node replication resulted in an error message
being logged even if there was no error. This commit fixes that.
=> Fixes a bug where error message is logged even without an error

pkg/kp/flags/kingpin.go, pkg/preparer/setup.go, pkg/util/net/client.go, pkg/util/net/tls.go
This addresses an internal issue related to calling to Consul from a CLI.
=> add TLS key flags to CLI defaults

pkg/ds/farm.go, pkg/rc/farm.go, pkg/roll/farm.go
=> ds, rc, roll: Record number of DS, RC, RU in farms

pkg/preparer/setup.go
When creating a Store for the preparer, cache a single instance and
always return that one. This allows consulStore's HTTP client to have a
global view of all requests to Consul.
=> Use only one Store in the preparer

bin/p2-exec/main.go
Default of 0022 matches our datacenter's config
=> Configurable umask for p2-exec

pkg/preparer/orchestrate.go
By design, failures in the installAndLaunchPod() function are retried
constantly, so that transient failures do not leave a deploy unfinished.
The only way to recover from permanent errors is to schedule a new
version of the pod that succeeds.
However, trying to download a pod every second can have undesirable
consequences to the download server in times of high load. This commit
adds an exponential backoff to mitigate this issue.
The backoff time begins at 1 second as before, and every sequential
failure doubles the backoff time, with a ceiling at 1 minute.
=> Add exponential backoff to preparer installAndLaunchPod()

pkg/labels/applicator.go, pkg/labels/consul_applicator.go, pkg/labels/fake_applicator.go, pkg/labels/http_applicator.go
This is useful for secondary caches that can retrieve the full list of labeled entries
=> List labels by type

pkg/preparer/orchestrate.go
Commit f98b0a1116cc82caab27a6202d91aea4d0b1019f introduced an
exponential backoff for pod installation and launching when an error
occurs. The backoff starts at 1 second and doubles on each error. The
backoff time is only reset when a pod launch is successful.
This commit also resets the backoff time if a new manifest is received,
which will reduce the amount of time it requires for a "fixed" pod
manifest update to be processed. For example, if a manifest is deployed
with a bad launchable URL and the backoff time rises to a minute, it is
desirable that a corrected manifest can be scheduled and processed
immediately, instead of after a large backoff time.
=> Reset pod installation backoff time if new manifest is received.

pkg/health/checker/checker.go, pkg/health/checker/checker_test.go, pkg/health/health.go, pkg/kp/healthmanager.go, pkg/kp/kv.go, pkg/watch/health.go, pkg/watch/health_test.go
This will break dependencies of pkg/, please merge with care
=> Remove references to deprecated health Output field

pkg/labels/label_http_server.go
Adds latency histograms for each HTTP verb • label tree combination, in addition to some counters for 503s and 400s.
=> Measure label server traffic

bin/p2-preparer/main.go
When exiting, stop the health checker as the last action of the process.
The preparer is slow to exit, especially if there is a pod update in
progress. There could be a substantial amount of time between the start
of a shutdown (when a SIGTERM arrives) and when the preparer finally
exits. This change keeps the health checker alive during this time to
minimize the amount of time when pod health is not published.
=> p2-preparer: Stop the health checker last

pkg/preparer/orchestrate.go
This change reduces the number of error messages
emitted by the preparer when a manifest is signed by
a GPG key that has expired, but was not expired when
the installation took place.
=> Verify pod authenticity after SHA comparison

pkg/ds/daemon_set.go, pkg/ds/farm.go, pkg/replication/replication.go, pkg/replication/replication_test.go
I still need to verify this code works via integration test. It's a fairly big change, so I thought I'd solicit opinions early. Commits are fairly isolated, please review commit by commit.
=> Daemon set bugfixes & cleanup

pkg/pods/pod.go
This function is useful as a library function for generating a
deterministic unique string for a pod. For instance a hook may wish to
manage per-pod files using this string in the filename to avoid filename
collisions while programmatically being able to clean up or otherwise
locate them.
=> Export pod.uniqueName() function.

pkg/pods/pod.go
Disable scripts that hang forever or run for a very long time are a
common source of confusion during p2 deploys, because they result in
p2-preparer appearing slow to accomplish the update. Emitting warning
messages to the logs makes it easier to identify when a slow launchable
lifecycle script is to blame.
=> Emit warning messages if a launchable script is running for minutes.

pkg/preparer/orchestrate.go
When installing a pod, the PodStatus field will be set to
"launched".
When uninstalling it will be set to "removed".
=> Correctly set pod status field for uuid pods.

pkg/store/consul/healthmanager.go, pkg/store/consul/healthmanager_test.go
p2-preparer executes health checks on the pods it has deployed, and
writes the health value to consul if and only if that health value has
changed since the last time it was written. This is done to reduce QPS
of health checks on Consul.
This means that the preparer must keep a copy of its view of the health
value that is stored remotely in order to make the decision of whether
to write or not.
Additionally, services with flapping health will have their health
updates throttled. This is implemented by writing an "unknown" health
value to Consul, and ceasing all health writes until the service stops
flapping.
This commit fixes a bug where a throttle would cause "unknown" to be
written to Consul, however the local view of the remote health value
would be set to the actual service health …
=> Fix bug in recovery from throttling of health publishing.

pkg/ds/farm.go
In the case where a daemon set is deleted, but nobody has a lock on it,
some daemon set farm must grab a lock on it and spawn it so that it can
react to its deletion signal.
Previously, any daemon set farm attempting to do so would not spawn the
daemon set, which has two bad effects:
1. No deletion actually occurs for the daemon set.
2. The farm dereferences nil when checking whether the nonexistent child
has errored or reacted to its delete signal.
The second effect has the effect of making our tests sometimes fail.
=> ds: spawn a daemon set before deleting it

pkg/hoist/hoist_launchable.go
Historically, the hoist artifact spec was rigid in its requirement that
any services that should be started under runit must be at or under the
bin/launch location in the artifact. Under this scheme, it was not
considered an error for an artifact to not have bin/launch, it would
simply be downloaded, and have bin/enable run after starting no
processes.
P2, however, has added the option of specifying alternate entry points
within an artifact in your pod manifest. At this point it became an
error if entry points were missing (including the implicit bin/launch if
the option is not overridden). This had the side effect of causing
bin/enable to not be run for apps that do not start any services.
This commit returns to the behavior of running bin/enable if the only
startup error was related to …
=> Run bin/enable even when there are missing entry points.

pkg/watch/health.go, pkg/watch/health_test.go
I'm trying a new static analyzer (https://github.com/dominikh/go-unused) and this is what it found for `pkg/watch/health`. Let's wait for the build on this one.
=> remove unused code

bin/p2-rm/rm.go
A pod's uuid contains all the information necessary to delete that pod.
For safety, p2-rm historically required you pass the uuid as well as the
pod ID to confirm that the user is deleting the pod they expect they
are.
However this makes it harder to use the tool. This commit adds a
confirmation prompt that tells the user the pod ID of the pod being
deleted to preserve safety while adding some ease.
=> Make it easier to delete a uuid pod for which pod ID is not known.

pkg/preparer/setup.go
In large deployments of P2, a lot of bandwidth from the consul server is
used by potentially thousands of preparer instances pulling manifests
that might be multiple Kb constantly. When no intent data for a node is
changing, this means a request completes every 5 minutes, returning the
full data.
This commit makes it easy to change the wait time on consul watches
performed by p2-preparer so that bandwidth usage during periods of
steady data can be tuned.
=> Make the default consul wait time configurable in p2-preparer.

pkg/roll/run_update.go
If the new RC is already disabled, the only thing that can cause the new
RC's number of labeled nodes to meet its desired number (assuming the
desired number is too high) is for the other RC to steal some nodes from
it. If the other RC is disabled before it can possibly do that,
deadlock.
Note that my ideal solution in this situation is actually to change the
desired counts of the two RCs to match what they already have labeled,
but I was worried that a transactionless update might fail in an
inppoortune place. I suppose the risk of that is no greater than what it
already is.
=> roll: Disable old RC after convergence check

pkg/store/consul/consulutil/watch.go
As with the other watch functions, this allows us to see where we are spending
our time in Watch-land. Of particular interest to us is time spend blocking on the
output channel, it may motivate us to change the dataflow patterns.
=> Add Watch histograms for new-ish WatchKeys function

bin/p2-watch/main.go
I wrote this code to debug an issue and I think it's generally useful. If yes, I'll polish it up for a proper review.
=> [WIP] p2-watch can watch the health tree

pkg/rc/farm.go
the <-rcKeyWatch block here is potentially slow and upstream code blocks on
writing to this error channel
I am open to an all encompassing discussion about the sanity of error channels.
=> [WIP] WatchKeys is sometimes latent

pkg/config/config.go, pkg/config/config_test.go, pkg/config/fake_config_file.yaml
I want to put a list of strings in my config.  This is basically modelled after config.ReadMap above it.
=> Add a config.ReadStringSlice

bin/p2-install-hook/main.go, bin/p2-run-hooks/main.go, pkg/hooks/hook_env.go, pkg/hooks/hooks.go, pkg/hooks/hooks_test.go, pkg/hooks/types.go, pkg/preparer/orchestrate.go, pkg/preparer/orchestrate_test.go, pkg/preparer/setup.go
=> Hook Linting

pkg/hooks/audit_logger_sqlite.go
3 commits for 2 lines (net). What do I win?
=> Retry hooks more

pkg/store/consul/configstore/store.go, pkg/store/consul/configstore/store_test.go
This PR is WIP but it breaks the API somewhat.
=> Config store

pkg/store/consul/configstore/store.go, pkg/store/consul/configstore/store_test.go
Add transaction versions of `PutConfig` and `DeleteConfig` ... `PutConfigTxn` and `DeleteConfigTxn`! With tests! That pass!
=> Transactions in config store!

pkg/store/consul/configstore/store.go, pkg/store/consul/configstore/store_test.go
=> Fix #891 - check some missed errors and fix travis build/test

pkg/health/checker/checker.go
There are a couple places where a value is sent on a channel that might
not be listening anymore. This commit makes the sends happen within a
select on the quit channel so that the goroutine will not fail to exit.
=> Fix potential goroutine leak in health checker

pkg/rc/replication_controller.go, pkg/rc/replication_controller_test.go
The main RC processing loop is designed in a paranoid fashion in which
it will only schedule nodes if the replica count becomes larger than its
current membership and it will only unschedule nodes if the replica
count becomes smaller than its current membership.
Node eligibility was only considered when unscheduling or scheduling.
This means that situations can arise where the nodes on which the RCs
pods are scheduled might become "ineligible" and the RC won't take any
action, and human operators might not notice for a long period of time.
This commit makes the RC consider the set of eligible nodes every loop
and send an alert if any of the current pods are scheduled on ineligible
nodes. It does not attempt to take any corrective action because this
likely requires input from human …
=> rc: send an alert if any "current" pods are on "ineligible" nodes

bin/p2-shutdown/main.go
This is useful for shutting down apps but not core services
=> Add excludePods option to not shutdown pods

pkg/ds/farm.go
This will make it easy to unmarshal yaml or json config directly into
the config struct
=> Add YAML and JSON tags to ds farm config

bin/p2-shutdown/main.go, bin/p2-shutdown/main_test.go
Add a test that ought to have appeared in the original PR
=> Straighten out the logic around excluded pods

pkg/ds/daemon_set.go, pkg/ds/daemon_set_test.go
This will hopefully fix a bug we've observed where the daemon set
handler responds every 5 minutes as if the timer has fired. This might
be occurring because we don't properly drain the timer's channel after
we stop it.
=> Fix usage of timers in daemon sets.

pkg/ds/daemon_set.go, pkg/ds/daemon_set_test.go, pkg/ds/farm.go
I started looking for the daemon set contention check and found a lot of unused code!
=> Results of `unused ./pkg/ds/...`

pkg/ds/farm.go
Commit 643738a9006582eb9d4df9f9469f26be5b97a188 attempted to collapse a
lot of duplicated code into a single function in the daemon set farm,
however an unintended side effect was that the daemon set farm is slow
to pass updates to a daemon set to the goroutine that is responsible for
carrying out the update.
The reason is that daemon set contention checks were being performed
regardless of whether the daemon set had been updated, so every time the
daemon set watch would fire a contention check would be run against
every daemon set. This is an expensive calculation because it requires
performing label select operations for every daemon set and then looking
for overlaps between sets.
This commit performs the check only if the daemon set is new or has been
updated.
=> Fix an issue with daemon set responsiveness

bin/p2-pcctl/main.go
This new command allows changing the strategy on a pod cluster, which
is recommended to serve as a long-term storage mechanism for the default
strategy for an RC. It's recommended to copy the strategy for an RC from
its pod cluster
=> Add --update-strategy command to p2-pcctl

pkg/store/consul/rcstore/consul_store.go, pkg/store/consul/rcstore/consul_store_test.go
Inspired by the function of the same name for PodClusters, this function allows
client code to pluck out the RC for a PodCluster using 3 convenient labels.
=> FindWhereLabeled for ReplicationControllers

pkg/rc/replication_controller.go
It used to be possible (albeit unlikely) for a node transfer to finish
before ensureConsistency was called. Therefore the old node would be
unscheduled but still be in the `current` slice. It would therefore be
scheduled again despite having just been intentionally removed.
This change checks for node eligibility in ensureConsistency to remove
that chance.
=> Update ensureConsistency to remove race

pkg/preparer/orchestrate.go
The p2-preparer has a main goroutine that watches a key prefix in consul
and converts the data into pod manifests each time the watch fires
(either because a manifest changed or because the watch timeout was
hit). If no goroutine exists for a particular pod ID, the preparer will
spawn a goroutine dedicated to handling updates to the manifest for that
pod.
Each pod goroutine consumes manifests on a channel, and if the manifest
differs from the manifest in the reality tree then an update will occur.
In order to prevent blocking the main preparer goroutine on pods that
are slow to install (due to slow enable or disable scripts, or large
downloads for example), the channel is written within a select statement
that contains a default case. The thought was that the next time the
watch fires the …
=> ensure that the preparer is always using the latest pod manifest

pkg/rc/replication_controller.go
Some debugging log lines were accidentally committed, this commit
removes them
=> Remove debug log lines

pkg/store/consul/consulutil/ops.go
This was an experiment that accidentally got checked in
=> Remove an attempt to set CPU profiler labels

bin/p2-rctl-server/main.go, integration/common-provision.sh, pkg/artifact/registry.go, pkg/artifact/registry_test.go, pkg/rc/farm.go, pkg/rc/replication_controller.go, pkg/rc/replication_controller_test.go, pkg/uri/uri.go
- get artifact url with artifact registry
- do get request to artifact url
- if not 200 status response then create low urgency alert
If I do Head request to artifact url then it will always return 200 even artifact url is invalid.
With Get request, 200 on artifact existing and downloadable, 404 if artifact url is invalid.
=> RC checks for missing artifacts in meetDesires call

pkg/rc/replication_controller.go, pkg/rc/replication_controller_test.go
Node transfers used to call AllocateNodes() on the scheduler to find a
node to transfer the ineligible pod to unconditionally. This commit
makes the RC first check if there is an eligible node that is already
unused (not scheduled with the pod the RC manages) and uses it instead
if it's empty.
This can prevent situations where AllocateNodes() returns a timeout
error for example, but the scheduler ends up allocating a node.
Additionally it can handle cases where a node is allocated out of band
in advance of the node transfer
=> node transfers: check for unused allocations before allocating

bin/p2-start/main.go, bin/p2-stop/main.go, pkg/auth/auth_policy.go, pkg/p2start/p2_start.go, pkg/p2stop/p2_stop.go
- p2-start and p2-stop modeled after p2-restart but checks if user is authorized to run the script with authPolicy
=> Implement p2-start and p2-stop

bin/p2-start/main.go, bin/p2-stop/main.go
had to fix some errors in the authorize fail case and p2start pkg incorrectly used in p2start script.
=> P2 start p2 stop fix

pkg/rc/replication_controller.go
Before this change, if there was an error building the final node
transfer transaction, whether due to a network partition or otherwise,
the node transfer would fail but would not rollback. This prevented
future node transfers from occurring.
This change adds a retry around the finishTransfer() call so that
something like a temporary network partition will not stop a node
transfer. In the event that the node transfer still fails after the
retries, there is likely an underlying problem so we now alert.
=> Add retry with backoff to finishTransfer() call

pkg/opencontainer/containers.go
The goal of the post-install hook was to give a container a chance to
set up its config.json file just before being launched. However,
post-install is problematic because it might depend on system setup such
as environment variables which aren't available until later in the life
cycle.
This commit instead allows for a pre-launch script which runs just
before launching (after some validation of the config.json has been
performed).
=> opencontainer: change out post-install for pre-launch

pkg/labels/http_applicator.go
Lately we've seen network errors cause this function to fail with some
frequency. This changes adds naive retries with a simple linear backoff
to reduce the return of errors due to fleeting network failures. At the
same time, it tries to not dramatically increase latency (where latency
is defined as the time it takes getMatches to return, successfully or
not).
=> Add naive retries with backoff to getMatches

pkg/health/checker/checker.go, pkg/health/checker/checker_test.go
- fix for health service bug that will treat all pods as healthy after nodes were refreshed
- regression test and test coverage for checker code
=> Bug fix: pod considered healthy after node refresh 

pkg/docker/docker.go
This obviates the need to provide the username to uid/gid mapping in a
container's /etc/passwd file
=> Convert docker usernames to uid:gid format

pkg/docker/docker.go
Environment variables are configured via P2 hooks by placing files into
the "pod env dir" and each "launchable env dir". The former is useful
for setting environment variables on all processes in a pod, and the
latter is useful for when environment variables differ by launchable.
With hoist launchables, conflicts are addressed by preferring the
launchable-specific environment variables over the pod-wide ones. This
commit makes docker launchables the same.
=> Account for env variable conflicts between pod and launchable env vars

pkg/docker/docker.go, vendor/github.com/docker/docker/client/container_exec.go, vendor/github.com/docker/docker/client/interface.go
- attach to stdout and return enable or disable error if cmd has exit code != 0
=> Mimic behavior of docker PostStart/PreStop with hoist enable/disable

pkg/docker/docker.go, pkg/pods/pod.go, pkg/pods/pod_test.go
- actually pull docker image by sha
- remove image pull logging as it's not useful
- add docker pruning at uninstall step
=> Image pull and prune resources

pkg/rc/replication_controller.go, pkg/rc/replication_controller_test.go
Node transfers will still send a low urgency alert if the subsequent
deallocate or scheduling calls fail because in that case allocations
will not match reality and will need to be fixed.
=> Do not alert on node transfer allocate failure

bin/p2-preparer/main.go, pkg/grpc/scheduler/client/client.go, pkg/hooks/hook_env.go, pkg/hooks/types.go, pkg/preparer/setup.go
move when hooks are installed for p2-preparer from after preparer init to within preparer init
create new hook type PreparerInit to be ran after hooks are installed in preparer initialization
=> move preparer hook installation and create preparer init hook type

pkg/rc/replication_controller.go
Allocating a new node is not idempotent so the call should not be
retried on failure.
=> rc: don't retry AllocateNodes

bin/p2-install-hook/main.go
=> refined p2-install-hook

pkg/cgroups/cgroups.go
set cpu period back to default, and added safe layer for changing cpu period to avoid invalid input holding back pods to be launched.
=> Changes to cpu period and cpu quota

.travis.yml
debug info, prepurge runit as cargocult, and then install its systemd unit file too
=> Working to fix Travis builds
